### ISSUE TITLE
iOS App for MyCaert

### ISSUE THREAD

**Issue by bguerrettaz** [MyCaert/Issues-Enhancements#106]
This is the creation of an iOS app that allows single sign-on for students.  The students would download the MyCaert app from the iTunes store and sign-in once.  They will have the option to save the login information so they won't have to login again.

-Creation of mobile student landing page
-Ability to launch into full site mode
-Ability to log-off
-Includes the submission and back-and-forth with Apple
-Includes artwork needed for the app

Estimate: 50-60 hours for iOS app creation and simple landing page (current list view of Student's calendar).

**Comment by bguerrettaz** [comment]
Just wanted to check and see if there was any more info on this item?

**Comment by dpentony** [comment]
Is your estimate of 50 to 60 hours still the same?

**Comment by bguerrettaz** [comment]
Sorry, just noticed I never responded to this.  Yes, I think I can get what we talked about in the past done for around that:

-Creation of mobile student landing page
-Ability to launch into full site mode
-Ability to log-off
-Includes the submission and back-and-forth with Apple
-Includes artwork needed for the app

Estimate: 50-60 hours for iOS app creation and simple landing page (current list view of Student's calendar).

**Comment by bguerrettaz** [comment]
Are you still interested in this or not really?

**Comment by dpentony** [comment]
Not really. We're more interested in the Google Classroom applications and will make a final decision before year end.

**Comment by bguerrettaz** [comment]
Sounds good, thanks.
