### ISSUE TITLE
Redesign Maintain E-Units/PPT's Page

### ISSUE THREAD

**Issue by bguerrettaz** [MyCaert/Issues-Enhancements#109]
Redesign of the maintain e-units/PPT's page.  (6 pages in total will need redesigned).

Get rid of the secondary page that allows you to set dates and make teacher notes.  Create additional columns on the main page to account for these making it much easier for the user to maintain these items.

Also, color code each row as expired or active.

This will allow for a more seamless flow and give the teachers the ability to manage their material in one location.

Rough estimate: 25-35 hours

**Comment by bguerrettaz** [comment]
I have completed the eUnits portion of the redesign.  It is live under maintain eUnits.  

I have only implemented the eUnit portion, not the PPT portion.

Quite a bit of time and testing has gone into just the eUnit.  Please test this out and assure that it works to your liking and that you don't see any issues.

Once you have confirmed that you like everything, I'll work on completing the PPT version.

As for 'All' quiz classes and students, it is completely different than individual quiz classes and students, so that code base has not changed.  It is a different logic path altogether.  Just an FYI when you are testing.

Please let me know of any questions/concerns.  If you do find a bug, I can back out these new changes.

Blake

**Comment by mnichols13** [comment]
First glance I think it looks good.   One thing to note, we need to change the banner - where it says to click on the calendar icon - since we have removed it, the wording should be changed.

I am wondering if we should replace the banner with something that informs teachers that the dates are optional in this area?

**Comment by dpentony** [comment]
I like the idea that the days are optional.

**Comment by bguerrettaz** [comment]
Sure, I think we should change that as well.  I can either remove it or
replace it with wording...if you want the latter, what would you like it to
say?

**Comment by mnichols13** [comment]
Please note that assign dates and due dates are optional.  These dates will determine if and when your students will be able to view the materials and will need to be updated manually by the teacher.

**Comment by bguerrettaz** [comment]
I have made this change...please confirm that it looks the way you'd like.

After this is complete, would you like me to implement the PPT changes?
They are almost completed as well.

Blake

**Comment by dpentony** [comment]
@bguerrettaz  - please wait for Mindy to give final OK on the Eunits. Once given, feel free to move on to the PPTs.

One change - could you put the following in bold red type? Please note that assign dates and due dates are optional. These dates will 
> determine if and when your students will be able to view the materials and 
> will need to be updated manually by the teacher.

**Comment by mnichols13** [comment]
Can we put an asterisk next to the words Assign Date and Due Date in the headings?  This might help direct their eyes up to the message we posted about the dates being optional.

**Comment by dpentony** [comment]
Yes. the asterisks sound good if Blake can do it.

**Comment by bguerrettaz** [comment]
I have included the asterisks on Assign Date and Due Date as well as made
the font bold red.

All look good now?

**Comment by dpentony** [comment]
I am OK with it as longs as Mindy is.

Looks like we will need to implement the changes for PPTs.

**Comment by mnichols13** [comment]
It looks good to me.  Lets proceed with the ppts page.

**Comment by bguerrettaz** [comment]
I have implemented the same changes for the PPT's maintain page.

Please test and confirm all functionality is working to your liking.

Blake

**Comment by dpentony** [comment]
@mnichols13 - this looks good to me. If all looks OK to you, please close the issue.

**Comment by mnichols13** [comment]
The save button on the bottom of this page says 
SAVE UPDATED STATUS TO ASSIGNED E-UNITS..... SHOULD SAY TO ASSIGNED POWERPOINTS

**Comment by bguerrettaz** [comment]
I've changed it to PPT's, please take a look.

**Comment by mnichols13** [comment]
I am getting an error message when I try and save a date.
Microsoft OLE DB Provider for SQL Server error '80040e07'

The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.

/Teachers/Students/ppt-update.asp, line 158

**Comment by bguerrettaz** [comment]
What date are you trying to save?

**Comment by mnichols13** [comment]
assign date 1/15/2015
due date 1/19/2015

**Comment by bguerrettaz** [comment]
Before I submitted:
[image: Inline image 1]

After I submitted:

[image: Inline image 2]

I cannot recreate that error message.  Are you manually entering the dates
or using the calendar?

**Comment by mnichols13** [comment]
I cannot recreate either.  I'm not sure why I got the error previously.  If we hear of issues, I will let you know.
