### ISSUE TITLE
Creating a Course Outline by LIBRARY OUTLINE does not work

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#119]
Under Generate a List of MYcaert materials - the last option is by Library Outline.  
We had a NJ teacher try to create or add lessons in this manner, they get an error message

Microsoft VBScript runtime error '800a01a8'
Object required: 'cnMatrix'
/Teachers/course-outlines/lesson-plan-library/Outline_SelectLessons_NJ.asp, line 697 

When I tried to recreate the error on my IL account I did not get this error.   It may be an issue for that state or other states only?

**Comment by bguerrettaz** [comment]
Yes, this issue was specific to NJ.

I have fixed this issue, it occurred in two places.

Hours: 1

**Comment by mnichols13** [comment]
Ok this is really confusing for the teacher.  When I selected the 
lessons from Library Outline to add it took me to the next screen and I 
named the outline but did not select the lessons a second time.   I 
didn't do this on purpose, I just didn't realize I needed to select them 
again.  I got three conflicting responses

1 - Success
2 - No lessons have been associated
3 - All lesson have been expired.

It should have only given me #2



*/


      Mindy Nichols
      CAERT, Inc.
      P.O. Box 50
      Danville, IL 61834

/*

**Comment by dpentony** [comment]
Any progress on this issue?

**Comment by bguerrettaz** [comment]
In looking through this issue and the code, on a save, I think it does make sense that the following two messages show, when no lessons are selected:

-Success: Your Course Outline has been successfully saved.  
-No Lessons have been associated to this Course Outline.

Because the outline did successfully save and in this case, no lessons were associated.  Do you agree?

I do agree that this message should not show in this instance, I will have to work to correct the logic around this message:

-All the Lessons have been expired to this Course Outline.

Thoughts?

**Comment by mnichols13** [comment]
No I don't agree.  If no lessons were chosen, then the course outline is not created, therefore it was not a success.

**Comment by bguerrettaz** [comment]
So do we want to block creation if no lessons are selected?  What exactly
are we looking for here?  There could be many changes needed.

**Comment by dpentony** [comment]
It seems to me that a course outline should contain at least one lesson. So, if no lessons are selected, it makes sense that a course outline cannot be saved. A message would need to come up saying you have to select at least one lesson in order to save the course outline.

**Comment by bguerrettaz** [comment]
Ok.  I'm not sure how you want me to handle this.  The page where I would
have to build an alert that they didn't select a lesson are unique and they
are unique per state.

This one here is by select Library Outline.  The end of the URL also says
Outline_SelectLessons_IL.asp, which means this way of building an outline
is state specific.


[image: Inline image 1]

Another example is here, by Learning Area, also state specific; you can
tell that by looking at the URL again and noting the IL in the middle.

[image: Inline image 2]

So to get an alert into all of these pages is some work, I just wanted to
make sure I let you know there are many many pages to do.

That is really the only way to stop them from saving a course outline.  The
next screen is after saving, where it states that there are no lessons
associated, success, etc.

Please let me know what you'd like me to do.

Blake

**Comment by dpentony** [comment]
@bguerrettaz - thanks for your research on this. It is not that big an issue at this point, so we're going to close it.
