### ISSUE TITLE
Quiz Results - Date & Time Not Shown

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#120]
![image](https://cloud.githubusercontent.com/assets/5790325/5777729/d9860f12-9d5a-11e4-9684-fb41211b7cc7.png)

This student is in WI and his teacher is Marty Speth. Any idea why the date and time this quiz was taken the first five times do not show up? The student claims he took it six times and that he got improved scores until he finally got 19 out of 19. The result of the last time he took it definitely does not show he got 19 correct, nor does it show the date and time he took it the first five times.

**Comment by bguerrettaz** [comment]
As I dig into this issue, I have a couple of questions:

-Can you recreate this issue?
-Has any other teacher reported an issue with this?

I just want to make sure we have some background before I go digging
through this.

Blake

**Comment by dpentony** [comment]
I did not attempt to recreate. Please feel free to try as I'm on the road.

**Comment by mnichols13** [comment]
I cannot see the student name, the quiz or any details.   I cannot see 
the images, which leaves out all the pertinent information for me to try 
and recreate.
*/


      Mindy Nichols
      CAERT, Inc.
      P.O. Box 50
      Danville, IL 61834

/*

**Comment by dpentony** [comment]
I am closing this issue for now. We do not have enough info to pursue its cause.
