### ISSUE TITLE
Delete an old quiz class

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#121]
Can you please delete the old quiz class:  Ag. Science and Technology from the account of Perry Mason in AR.

I have been unsuccessful.  This quiz class has no course outline and is just confusing to have in his Manage Course roster pull down.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
Another teacher  needed old quiz classes deleted:  Mary Barnes IL us: mbarnes pw: recordbook

Ag Mechanics - Welding
Ag Science
Agriculture Mechanics -- Small Engine
Animal Science - Equine Science
BSAA - Animal Science
BSAA --Plant (with dash)
Horticulture - Greenhouse (with the dash)
Introduction to Agriculture A
Introduction to Agriculture B

**Comment by mnichols13** [comment]
Can you get this done this weekend?  thanks!

**Comment by dpentony** [comment]
Please make this the top priority on open issues.

**Comment by bguerrettaz** [comment]
I'm working on these tonight, I'll update when I'm done.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
looks good

**Comment by mnichols13** [comment]
I have another teacher who needs quiz classes deleted, I have done all I can in MYcaert 1.0, so I need your help to delete these old quiz classes for  Eddie Hendrix that are not associated with a current course outline.  Can you do this in the next day or two? 
HORTICULTURE 2
Horticulture 1st semester 2012
Horticulture 3
Survey 3rd 2nd semester
Surver of Ag systems 2012 4th period
Horticulture 1st period
Animal Science 2012
Animal Science 2

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
This request is now complete.

I didn't find the following in the database under this teacher:

Horticulture 3
Survey 3rd 2nd semester
Horticulture 1st period

Let me know if you still see them and I'll take a look again.

Blake

**Comment by mnichols13** [comment]
It looks good except I guess I missed one:  Introduction to Horticulture.  

I thought when we deleted old quiz classes they no longer showed attached to quiz names.  It looks like these quiz class names are still showing under the Edit Quiz screen as being associated with old quizzes that Eddie has created. I was thinking that it changed from the old quiz class to none?  Do you recall?

**Comment by mnichols13** [comment]
![image](https://cloud.githubusercontent.com/assets/5790342/8110706/6c38d4a8-1023-11e5-8023-f5d0cfe967f9.png)

**Comment by bguerrettaz** [comment]
I can't actually remember which way it was.

Do you want me to also delete Introduction to Horticulture?

**Comment by mnichols13** [comment]
Yes, please delete intro to Hort.
More importantly, the quiz classes need to be deleted so that they do not show up in this drop down menu under the Edit quiz parameters page.

**Comment by mnichols13** [comment]
Would it be possible to get this done this morning?

**Comment by bguerrettaz** [comment]
Yes, I will try.

I might not understand though, are you saying I just need to delete that one additional quiz class?

**Comment by mnichols13** [comment]
Two things:
1.  Delete the INTRO TO HORT quiz class.
2.  The quiz classes must be listed in multiple databases.  While they do not show up under the Manage Course Rosters drop down, they do currently still show up under the Edit quiz parameters drop down menu.  see screenshot above

**Comment by mnichols13** [comment]
Just delete the Intro to Hort quiz class.  I thought that there were additional quiz classes showing in the Quiz parameters drop down, but I was wrong.   I guess the teacher will need to do the rest.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
perfect
