### ISSUE TITLE
Montana teacher/ National state issue with exporting course outline

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#122]
Here is the message when I try and export a course outline for Melissa Mack - MT teacher: 
This webpage is not available

Hide details
The webpage at http://www.mycaert.com/Teachers/course-outlines/XX/reports/course-outline.asp?OutlineID=27661&TeacherID=14704&action=word might be temporarily down or it may have moved permanently to a new web address.
Error code: ERR_INVALID_RESPONSE

**Comment by mnichols13** [comment]
Just to clarify, she is able to export some of her course outlines, but not others.   Here are the ones that do not work:
7th Grade AG Ed
7th Grade AG Ed Semester Test
8th Grade Ag Ed

The others seem to work ok.

**Comment by dpentony** [comment]
What's the status on this?

**Comment by bguerrettaz** [comment]
This issue is resolved.

There was an issue with a variable not being set and couldn't be empty.

Hours: 1.5

Blake

**Comment by mnichols13** [comment]
looks good
