### ISSUE TITLE
Add Lesson Number to Search Results in MY Community?

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#123]
Below is a screen shot that shows the results for teachers when they search MY Community. The results do not list the lesson plan the item in the Community is associated with. Is there a way that the search results can also show the lesson plan the item it is associated with? When you do a search on the admin side, it does show the lesson number (see second screen shot).

![image](https://cloud.githubusercontent.com/assets/5790325/5842913/50433be0-a16e-11e4-9641-4ccc697bd79e.png)

![image](https://cloud.githubusercontent.com/assets/5790325/5842984/d02658b0-a16e-11e4-9ea6-b95030ae2b76.png)

**Comment by bguerrettaz** [comment]
Yes, this can be done.  Probably take 4 hours or so to add the column,
resize it all and write the query to retrieve the information from the
database.

Blake

**Comment by dpentony** [comment]
Thanks. I will share this with our customer and get back to you.

**Comment by dpentony** [comment]
Please proceed with this item. It should be second in priority after item 121.

**Comment by bguerrettaz** [comment]
This request is complete.

In my opinion there are some formatting issues with the display of search records.  Some of the text is bunched up against the field beside it and the spacing seems weird.  Let me know if you agree or if you want to leave it for now.

Please test and confirm this issue.

Thanks,
Blake

Hours: 4

**Comment by mnichols13** [comment]
I agree, the lack of spacing makes it hard to read.  I think it would good to tweak that.

**Comment by dpentony** [comment]
Please tweak it.

**Comment by dpentony** [comment]
Has this been tweaked?

**Comment by bguerrettaz** [comment]
I'm in the process of doing that.  I have to calculate what each column
will get (for spacing) and then implement that.  Should be done soon.

Blake

**Comment by bguerrettaz** [comment]
Ok, I have the spacing corrected and marginalized.

The only outstanding issue might be the category/attachements column.  This column isn't separated, it is one column with both headings in it.  To separate them out, it would probably take me 2 hours.

Hours spent on spacing so far: 2.5

Please let me know if you want that column fixed.

**Comment by dpentony** [comment]
I think this  looks good as is. @mnichols13 - I am going to close  this unless you see an issue.
