### ISSUE TITLE
Expand My Community Search Capability

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#124]
Currently when searching My Community, the key word search deals only with the Title of the document that has been uploaded. Could the keyword search be expanded to include the “description” and “saved document title” provided for the document?

**Comment by bguerrettaz** [comment]
Yes, this is possible.  Not sure on an estimate yet.  I'll have to take a
look at the current queries and see how they are pulling data.  I'll want
to make sure the queries performance doesn't take a hit by adding those
additional searches.

Are you thinking you'd want one search box for all, or a search box for
each type of search?  (Possibly a dropdown next to the search field to
indicate what type of search?)

**Comment by dpentony** [comment]
One search box will suffice.

**Comment by bguerrettaz** [comment]
Looking like 5-6 hours to implement the search you reference above and test.

Blake

**Comment by dpentony** [comment]
Thank you. We need to sit on this until we know more from our customer.

**Comment by bguerrettaz** [comment]
Sounds good.

**Comment by dpentony** [comment]
@bguerrettaz - please proceed with this item.

**Comment by bguerrettaz** [comment]
This request is complete.

The search now takes into account title, description and attachment name
(file name)

Thanks,
Blake

Hours: 6

**Comment by dpentony** [comment]
Looks good. Thanks.
