### ISSUE TITLE
WI Standards Missing

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#125]
Login to the Admin

This is showing all the standards
http://www.mycaert.com/admin/Lesson-Library/WI/AssociateAcademicStandard_LandingPage.asp

for some reason this page is not showing all the standards
http://www.mycaert.com/admin/Lesson-Library/WI/Ag/SelectContentArea.asp

**Comment by bguerrettaz** [comment]
Brian - what do you want to do about this issue? We talked the other day.  All states have this problem.

Blake

**Comment by BrianPeterlin** [comment]
For whatever reason, the content areas are on a separate database then the list of libraries/CDs.   If one is missing, it must be added here:

http://www.mycaert.com/admin/Lesson-Library/WI/Ag/AddContentArea.asp

**Comment by bguerrettaz** [comment]
Does this need my attention?

**Comment by dpentony** [comment]
@BrianPeterlin  - What's your opinion. These standards used to be there in v 1.0. It seems they should be there  in 2.0 as well.

**Comment by BrianPeterlin** [comment]
i am surprised that is the case.

i will look in 1.0 and investigate.

 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
they had to be there originally in 1.0 because that is where we originally added them to the database. It was the same for all states so that we could enter the standards in the database.

**Comment by BrianPeterlin** [comment]
@blake, I think this page was re-written going as part of the Admin
performance issues.  Was some logic put in differently?

[image: Inline image 3]

[image: Inline image 4]


On Thu, Feb 5, 2015 at 10:06 AM, dpentony <notifications@github.com> wrote:

> @BrianPeterlin <https://github.com/BrianPeterlin> - What's your opinion.
> These standards used to be there in v 1.0. It seems they should be there in
> 2.0 as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyCaert/Issues-Enhancements/issues/125#issuecomment-73072012>
> .
>



-- 
Brian Peterlin
bpeterlin@cmiti.com
Cell# 309 310 4551

**Comment by bguerrettaz** [comment]
Brian - After we spoke about this, we confirmed that the new page (the landing page) is correct, it has all of the CD's.  The incorrect page is the old page, which only has a subset of them.

Please let me know if you want me to make any changes.

Blake

**Comment by bguerrettaz** [comment]
Am I doing anything with this?

**Comment by BrianPeterlin** [comment]
@dpentony did Darrell write this page? http://www.mycaert.com/admin/Lesson-Library/WI/Ag/SelectContentArea.asp

Blake did not write or update this page.  2.0 and 1.0 are completely different for WI

**Comment by dpentony** [comment]
I assume Darrell wrote it.

**Comment by bguerrettaz** [comment]
Is anything needed with this issue?

**Comment by dpentony** [comment]
I will talk with Brian

**Comment by bguerrettaz** [comment]
Any update on this?

**Comment by dpentony** [comment]
I still need to discuss with Brian.

**Comment by bguerrettaz** [comment]
Is this still an issue?
