### ISSUE TITLE
Error message when assigning E-units - URGENT

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#127]
Doug Falk in IL - gets the following error message on one particular E-unit in one particular course.  He wants to assign the E-unit and make it active so his students can see it.   I get the same thing when I try.  

Advanced Agricultural Livestock  Eunit is 40011
We tried assigning it both through the course roster page and through the MY Students tab.  Neither worked.  

Microsoft OLE DB Provider for SQL Server error '80040e07'

The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.

/Teachers/students/eunit-update.asp, line 181

**Comment by mnichols13** [comment]
This problem occurred under the CHROME browser.  When I signed in under Firefox browser I was able to change the E-unit to Active with no problems.    I think we still need to investigate.

**Comment by bguerrettaz** [comment]
I've made a small change to the format of the date inserted into the
database.

Can you try and recreate?

**Comment by mnichols13** [comment]
I am unable to recreate - tried with several E-units.  Hopefully this fixed it.  Thanks for your quick response.
