### ISSUE TITLE
Password Validation for MyCaert Material - Hide from Google Search

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#130]
Hide Lesson Plans, PPTs, eUnits, Sample Quizzes, etc.

https://www.google.com/#q=mycaert.com+the+dairy+industry

@bguerrettaz need estimate and identify where we have issues

**Comment by dpentony** [comment]
Why is that dairy lesson showing up with a mycaert url? It is not one that we made available as samples.

**Comment by dpentony** [comment]
This is very concerning to our business. If you google the dairy lesson, you will get this link: http://www.mycaert.com/lesson-plans/L040155.pdf. All you have to do is change the number of the pdf and you can access any CAERT lesson plan. How do we stop this?

**Comment by BrianPeterlin** [comment]
we can ask google to not index those pages

i will call u to discuss

 Brian Peterlin
1-309-310-4551

**Comment by bguerrettaz** [comment]
What is the status on this?  Do I need to be looking into this?

**Comment by dpentony** [comment]
Not at this time.
