### ISSUE TITLE
Delete Post link in MY Community does not work

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#131]
See screenshot below. We had a teacher post a file to MY Community and then attempt to delete it. The delete post link does not work. When you click on the link, you get an message in the bottom left corner of the page saying JavaScript:delPost (813).

![image](https://cloud.githubusercontent.com/assets/5790325/6537104/46b51b16-c419-11e4-8fcd-a0149d571ced.png)

**Comment by dpentony** [comment]
The user who discovered the issue is Whitney Mehaffy in IL. She had uploaded an item in the Community for lesson HST:B3-3 and then could not delete it.

**Comment by dpentony** [comment]
What's the status on this?

**Comment by BrianPeterlin** [comment]
@bguerrettaz will review this weekend

**Comment by bguerrettaz** [comment]
Ok, there were actually three issues with this page.

-Incorrect query clause for displaying 'Approved' posts.  Rejected status
was also getting in -- Corrected
-Closing table element tags were missing, this was causing the table to not
be completed for rendering -- Corrected
-Updated JQuery plugins, was using a dated version -- Corrected

Please test and confirm.  I have reset that teachers post to 'Approved' so
you can use her account to test the delete method is working correctly.

Hours 3.5

Thanks,
Blake

**Comment by dpentony** [comment]
The delete post does not work on the admin page. See screenshot below. The only way I could delete it was buying logging in as the user who posted it.

![image](https://cloud.githubusercontent.com/assets/5790325/6733774/33f638c6-ce22-11e4-8b79-0cb0548e123e.png)

**Comment by dpentony** [comment]
Never mind. This now seems to be working on Admin page.
