### ISSUE TITLE
Add "Free 30-Day Trial Button to Homepage?

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#133]
We want to develop an easier way for teachers to request a free 30-day trial. We would like an estimate on adding a "Free 30-day Trial" link to the homepage. It could go to the left of the Submit Order link.

We envision that when a teacher clicks on the link a page would come up that would be somewhat similar to our order form at http://www.mycaert.com/ContentFiles/12102014105650AM.pdf. The form would be filled in online allowing them to enter their name, school, etc. They would also be able to place a check mark next to any library they wanted to preview for 30 days. Once the form is completed, they would submit it online and it would be sent to Dan and Mindy. We'd then have the info needed to set up their trial subscription.

We'd also like to the link to be easily hidden. At some times of the year, we do not want to promote the free trials.

Please provide me with an estimate.

**Comment by bguerrettaz** [comment]
This would take roughly 6-8 hours, including the admin function to hide/show the trial button.

Blake

**Comment by dpentony** [comment]
Please move ahead with this. We'd like it to be operational as soon as possible.

**Comment by bguerrettaz** [comment]
I have the form ready for review.

Please let me know if there is anything missing or text you would like to
add.

Here is the link: http://www.mycaert.com/free-trial-request.asp

Thanks,
Blake

**Comment by mnichols13** [comment]
Dan - do we want state libraries to show, or only the National AG lesson libraries?

**Comment by dpentony** [comment]
There are two issues with this:

1. There are way too many lesson libraries listed. The only ones that should be listed are those found on the order forms at http://www.mycaert.com/ContentFiles/12102014105650AM.pdf and http://www.mycaert.com/ContentFiles/125201480048AM.pdf. The ag titles should be listed first followed by those from the CTE order form.

2. Will they get some sort of message once they hit Submit? I'd like them to see a message saying: "Thank you for your request of a free 30-day trial. You will receive an email messaqe shortly with the logins for your trial."

**Comment by dpentony** [comment]
Can you provide an update on this? This item is our top priority.

**Comment by bguerrettaz** [comment]
I worked on it over the weekend as well.  I'm finalizing the email to you
and Mindy as well as the library selection that they have to choose from.

I should be done in the next day or two.

Blake

**Comment by bguerrettaz** [comment]
I have completed the pages for submitting a free trial request.

When you visit the homepage (not logged in) you'll have the option at the
top for a free 30-day trial request.

Once you click on that, you'll be taken to the new form.  Clicking submit
sends an email to Dan/Mindy.

Please test this and look it all over and let me know what you think.

I still have to make an admin function on the backend to hide/display this,
but at least this gets it up and running for now.

If you see something wrong, I can quickly revert the changes.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Forgot to add my hours so far: 8.5

**Comment by bguerrettaz** [comment]
I have also completed the toggle free-trial button code and new page on the
admin console:

[image: Inline image 1]

Right now it is set to active, meaning it will show on the homepage.  When
you click toggle, it removes it from the home page.

Please give that a try and make sure everything is working as desired.

Additional hours: 1

I went an hour or so over my estimate, but there were multiple pages that
held the top page elements (Teachers Login, Students Login, etc.) that I
had to change to reflect this button.

Thanks,
Blake

**Comment by dpentony** [comment]
This is looking good. There are just a couple of changes as follows:

 I think we should add is a bit of text on the screen that comes up after they click the 30-Day Trial Button. See screenshot below. In the area circled in red, I think we need to put the following text in bold red type: Please complete the fields below and check which libraries (maximum of two) you would like to preview. The login credentials for your trial will be emailed to you.

![image](https://cloud.githubusercontent.com/assets/5790325/6801897/911143f4-d1f9-11e4-8b2a-16234ad2eb06.png)

2. Move Agribusiness Management and Animals, Plant & Soil Science Libraries from towards the bottom of the list and insert them after the Advanced Life Science libraries at the top of the list.

![image](https://cloud.githubusercontent.com/assets/5790325/6802001/a4c54296-d1fa-11e4-956c-4581e9b2f2a8.png)


![image](https://cloud.githubusercontent.com/assets/5790325/6801970/3dcf0f4a-d1fa-11e4-890d-fc322bc52f4d.png)

**Comment by bguerrettaz** [comment]
As for the first one, I added that text. I also removed the message after
successful completion and put that in a popup box once it is successful.
There was too much text at the top once they completed the form and it got
confusing.  Please test it out to see what I mean.

For the second, that will take a little more time.  Those libraries are
pulled from the database.  I can order them (which I am doing now) but
can't pick exactly which ones go where without a more complex query.

I will work on the second request now and let you know when it's complete.

Thanks,
Blake

**Comment by dpentony** [comment]
@bguerrettaz  - see screen shot below. Could you make (maximum of two) more prominent? Maybe you could change it to all caps and highlight it? The Free Trial link is working well, but they are missing the part about a maximum of two.

![image](https://cloud.githubusercontent.com/assets/5790325/6951998/9e115d3c-d884-11e4-9417-a8d9387281ce.png)

**Comment by bguerrettaz** [comment]
Done.  No charge.

**Comment by dpentony** [comment]
Gracias!

**Comment by dpentony** [comment]
Even though we made "Maximum of Two" more prominent, most people continue to request more than two libraries. Could something be done to the list of libraries so that they could only place a check mark next to two of them. For instance, if they placed a check mark against the first two libraries and then tried to check the third library, they would not be allowed to do so until they unchecked one of the first two libraries?

**Comment by dpentony** [comment]
Yes, please proceed.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by dpentony** [comment]
The 30-Day Trial is not working in Internet Explorer. After hitting the Submit link, nothing happens.

**Comment by bguerrettaz** [comment]
Ok, I was able to identify the problem.  Can you please retest and confirm
its working and that you're receiving the request in email?

Blake

**Comment by dpentony** [comment]
Works great. Thanks.

**Comment by dpentony** [comment]
We have two issues with the 30 Day Trial Request as follows:

1. We need to update the list of the ag libraries in the pull down menu. See screenshot below. These should be the first 13 listed in the pull down and all other ag libraries currently listed should be deleted.

![image](https://cloud.githubusercontent.com/assets/5790325/10883231/1dd3e79c-8136-11e5-9d74-4be665886132.png)

2. The submission form allows a teacher to request a maximum of two libraries. However, when only one library is requested and the form is submitted, you get the following error message:

Microsoft VBScript runtime error '800a0009'

Subscript out of range: '[number: 1]'

/DoSendEmailTrial.asp, line 24

**Comment by bguerrettaz** [comment]
To be clear, you want all of the libraries removed from the dropdown that currently exist and replace those with the ones from the above screenshot?

I'll work on the error now, please let me know the answer to the other question and I'll work on that as well.

Blake

**Comment by dpentony** [comment]
I will email a file with how we want the libraries to be listed.

**Comment by bguerrettaz** [comment]
This request is complete.  Both the library addition and the error with 1
selection.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. thanks.
