### ISSUE TITLE
Exporting course outline to Word - cell format is incorrect

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#134]
When I export a course outline to Excel and want to view the grade level for the Common Core standards it should read "11-12"  instead it reads Nov-12.

Can you please fix this?

**Comment by bguerrettaz** [comment]
This is actually due to Excel formatting the column (it thinks its a date,
rather than a number range).

Can you send me an example to look at and then I can give you an estimate
to fix (probably won't take too long, but course outlines are state
specific).

Blake

**Comment by mnichols13** [comment]
Do you want me to email you a copy of an exported outline?

**Comment by bguerrettaz** [comment]
That would be fine, I just need to see what the system is putting in and
how Excel is interpreting it.

Thanks

**Comment by bguerrettaz** [comment]
This is resolved.  I had to find the offending data element.  I added a
blind space to the end so Excel wouldn't think it was a date.

Please test and confirm.

Blake

**Comment by mnichols13** [comment]
looks good

**Comment by mnichols13** [comment]
I'm not sure why this seems to be a problem again.   The original problem here is a problem again 

When I export a course outline to Excel and want to view the grade level for the Common Core standards it should read "11-12" instead it reads Nov-12.  Also grade level 9-10 reads Sept 10
![image](https://user-images.githubusercontent.com/5790342/222237369-4ba35a92-95f2-46a2-bbbf-a010f6a3584a.png)

**Comment by blake** [comment]
@mnichols13 I believe you meant to tag @bguerrettaz. I'm a completely different person. Kindly please stop tagging me on issues in this repo.

**Comment by bguerrettaz** [comment]
Hi - this is actually an Excel formatting issue.  Excel automatically
formats when it detects a pattern or specific pattern.  It's mistaking 9-12
(grades) for Sep-09, for example.

The only way I could get this to fix is to put a period after the grade.  I
needed to break the date auto-formatting and this seems to have done the
trick.

If for some reason this causes an issue, we can look at alternatives but
that will likely include rewriting the Excel/Word export using a
third-party utility we would need to purchase.

Please test and let me know what you think.

Thanks,
Blake
