### ISSUE TITLE
Exporting course outline - other requests

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#135]
Can you give us an estimate on making the following three changes to Exporting a course outline:

Remove the letters "CD: before the lesson library title in the header (row #1)
Lighten the dark grey banner to the lightest grey in row #1
Remove the letters "LC" before the Lesson number and title in column #1

**Comment by bguerrettaz** [comment]
Course outlines are state specific, so the estimate will be broken down for
one state, and then all states.

One state: 1 hour
All states: 18 hours (1 hour x 22 different state specific pages, but will
only charge 18 hours, instead of 22)

Please let me know how to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
@mnichols13 - let's talk about this on Monday. I do not think the changes are worth the expense.

**Comment by dpentony** [comment]
@bguerrettaz  - Please make these changes only for Illinois.

**Comment by bguerrettaz** [comment]
This request is now complete.  Please check it out and confirm everything
looks as desired with the stated changes.

Blake

**Comment by mnichols13** [comment]
looks good !
