### ISSUE TITLE
Saved messages in email console - do not display properly 

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#136]
Below is a copy of an email sent from the console.  It was in my saved email messages and when I sent it this morning, now it is not displaying properly.   I have sent these same messages out twice before with no problem.  Now this month, the formatting is messed up.    When I view MANAGE SAVED MESSAGES they look fine.  

![image](https://cloud.githubusercontent.com/assets/5790342/6785137/e33db7f0-d151-11e4-8e6d-cc69ba77031b.png)

I have nine of these similar messages that I sent out. 

See the text after  What's new for 2015? 

Budget planning time? Be sure and check out MYcaert’s 2015 prices. We’re pleased they are largely the same as last year.

 

Access our 2015 AG order form here:

http://mycaert.com/ContentFiles/12182014125929PM.pdf

 

We’ve got a wealth of materials in other CTE areas. Access our 2015 CTE order form at: http://www.mycaert.com/ContentFiles/125201480048AM.pdf

 

What’s New for 2015?

 

-          Revised AFNR and Ag Power Libraries

-          Easier Student Set-up

-          Improved Calendar Functionality

-          Trial Subscriptions Available

 

Send questions to us at: http://mycaert.com/contact.asp

Or call us at 866-678-2433

**Comment by bguerrettaz** [comment]
Mindy,

I am seeing those comments (- ) in
the database, but those are ignored by the browser and email clients (they
are HTML comments)

I sent the email to myself and it looks good:
[image: Inline image 1]


Where are you seeing those? What email client?

I also don't see those comments in the preview or edit screens for those
email blasts.

**Comment by dpentony** [comment]
I saw them when I received the eblast. I am not sure what you mean by the email client. We are served through go daddy.

**Comment by bguerrettaz** [comment]
I mean where do you receive your emails? Like GMail, Outlook, Yahoo, etc.?

**Comment by dpentony** [comment]
Outlook express. I may be a rarity.

**Comment by dpentony** [comment]
Correction. I use Windows Live Mail.

**Comment by bguerrettaz** [comment]
Is anyone else seeing this issue in any other email client?

I didn't see it in GMail.

**Comment by mnichols13** [comment]
I did not get a copy myself, so I cannot comment.

**Comment by dpentony** [comment]
No one else has reported it. Maybe I am the only one since I use Windows Live. We will close this issue for now until we get other reports.
