### ISSUE TITLE
log of work in Admin

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#137]
Request for estimate of work:
Can you provide some sort of log of entry that would show work done by date for the Admin site?   Example:
Today I aligned common core standards to IL CTE lessons.   One of the alignments I believe was entered incorrectly.  I have no way of finding the incorrect entry.  Any ideas?  

thanks.

**Comment by bguerrettaz** [comment]
The only thing that comes to mind (from a simple solution perspective) is
having a log of all of the 'admin' database transactions that has occurred
and when.

With this there would have to be the following:
- A new table to hold log entries
-An interface on the admin side for you to read/search the log
-And building the back end to log when a transaction hits one of the tables
in the admin console

For something like this, you are probably looking at around 15-20 hours of
work (that's a rough estimate, it could be a bit more depending on the
number of admin tables we identify).

Is this what you were looking for?

There are solutions that would be more detailed and in depth, but that
would require many more hours.

Please let me know how you want to move with this.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Did you want to move forward with this logging?

**Comment by mnichols13** [comment]
That didn't sound very simple ....  probably not

**Comment by bguerrettaz** [comment]
If you wanted it only for one screen, it wouldn't be that bad.

There are two thoughts here, build logging for all admin functions for
tracking and accountability, or just pick the screen you want logged and
build a report off of that.

**Comment by mnichols13** [comment]
ok, Dan and I will talk

**Comment by dpentony** [comment]
How many hours for such a scaled back version?

**Comment by bguerrettaz** [comment]
I could probably do the capture of the data and building a report in 5-6
hours.

**Comment by dpentony** [comment]
@mnichols13  - let's talk about this.
