### ISSUE TITLE
Error message when maintaining E-unit dates IL teacher

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#139]
We get the following error message on Doug Falk's IL AG account 
u: dfalk
p:tori

He cannot change or wipe dates on the course outline named:  Advanced Agricultural Livestock - the following error message comes up:
Microsoft OLE DB Provider for SQL Server error '80040e07'

The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.

/Teachers/students/eunit-update.asp, line 181

**Comment by bguerrettaz** [comment]
This was a weird issue.  Someone had placed multiple comma's (and nothing
else) in the TeacherNotes column.  That's a form of SQL injection, which
means it messes up the queries in a way that pushes columns into different
columns.  Sounds confusing and it kind of is.

I removed the comma's but even before I looked at this issue, it pushed
some updated into other columns, so I had to fix those as well.

Long-story short, I have everything fixed and the profile is loading
correctly now.

Thanks,
Blake

Hours: 3
