### ISSUE TITLE
Help with a course outline - Jarred Bower

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#140]
Teacher: Jarred Bower in Wyoming has a problem course outline AGLeadership
will not export to word or excel
cannot change the order
anytime you click on the outline, the website hangs up

**Comment by bguerrettaz** [comment]
This gets back to the performance issue.  There is a lot going on with
course outlines from the backend.

We put flushing in for IL, but I think we held on the other states.

To fix this, I'd need to put in flushing.  Do you want me to do all the
states or just WY?

**Comment by dpentony** [comment]
What is the estimate for doing just WY?

**Comment by bguerrettaz** [comment]
Around 1-1.5.

Blake

**Comment by dpentony** [comment]
Please proceed on WY only.

**Comment by bguerrettaz** [comment]
Ok, I put flushes into WY code for course outlines.  I also had to add a
custom script timer because of how large this specific course outline was.
I've attached it for reference.

This is complete.

**Comment by mnichols13** [comment]
Something is not right with this.  Jarred's AGleadership outline is only 25 lessons long, why is it repeating everything multiple times?  It did finally download, but took 2 or 3 minutes.

**Comment by mnichols13** [comment]
Something went wrong here - take a look at the outline.  It should only 
have 25 lessons in it.
*/


      Mindy Nichols
      CAERT, Inc.
      P.O. Box 50
      Danville, IL 61834

/*

**Comment by dpentony** [comment]
To clarify, when you look at the course outline before exporting, it only has 25 lessons in it. When you export the outline, the file is huge and runs many pages. In the exported file the 25 lessons are listed multiple times. Why is this happening? It's the Ag Leadership course under Jarred Bower in Wyoming.

**Comment by bguerrettaz** [comment]
Ok, I think I'm at or close to a fix with this.  Can you please look at the
course outline and let me know if it is correct or not?

Blake

**Comment by mnichols13** [comment]
yes this looks right now
