### ISSUE TITLE
Headers not showing when emails get sent through console

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#141]
Typically when i send emails through the Mycaert admin console - a blue header and footer show - for some reason these have disappeared.  Can you look into?

**Comment by bguerrettaz** [comment]
Do you mean in these emails sent from the console?
[image: Inline image 1]

This is what I see.  You're expecting a header/footer?

**Comment by bguerrettaz** [comment]
Is this still an issue?

**Comment by mnichols13** [comment]
yes
*/


      Mindy Nichols
      CAERT, Inc.
      P.O. Box 50
      Danville, IL 61834

/*
