### ISSUE TITLE
Microsoft VBS Runtime Error for MN

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#142]
Each year we administer a Plant Science Test for Minnesota. Login as MN Plant Science TSA Teacher (look under the Ts in Minnesota.). We set up a Dummy Student15 as a student just to make sure all looks OK. The student can see the test fine, but there is a runtime error on the page. Can you get this to go away before they take the test on May 13? See screenshot below:

![image](https://cloud.githubusercontent.com/assets/5790325/7524824/4b7c9caa-f4ca-11e4-95c7-0b7323c2c9df.png)

**Comment by bguerrettaz** [comment]
This issue is now resolved. Please test and confirm.

Hours: 2

**Comment by mnichols13** [comment]
looks good
