### ISSUE TITLE
Student Login Report Not Working - Need this Week

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#143]
I am trying to print a student login report via the global admin. From the global admin, click Login Report under Usage. Choose Student as the report type and SC as the state. The date ranges I need are from 5/6/2015 to 5/7/2015 and 5/10/2015 to 5/11/2015. When I run the report it throws those dates out and gives me a report for the last 30 days. Also, when I clicked on Printer Friendly link I get the error message below. 

Response object error 'ASP 0251 : 80004005'

Response Buffer Limit Exceeded

/admin/LoginReport/PrinterFriendlyReport.asp, line 0

Execution of the ASP page caused the Response Buffer to exceed its configured limit.

**Comment by bguerrettaz** [comment]
I put some flushing in to take care of it, but when I did that, I noticed
that the dates weren't taken into account, therefore it was building the
report agnostic of the date.  This will need to be fixed.

It looks like there are three different pages:

[image: Inline image 1]

I'm guessing they will need to be fixed.  Please let me know how to proceed.

Blake

**Comment by dpentony** [comment]
Please proceed

**Comment by bguerrettaz** [comment]
This is now complete.  The old date picker was throwing many errors.  I put
in a new, more modern and reliable, date picker.

Blake

**Comment by dpentony** [comment]
Thanks
