### ISSUE TITLE
Update MO State MYcaert Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#144]
Missouri has extended their subscription to MYcaert for another year. We need you to make the following changes on a state-wide level prior to July 1:

1. For any teachers with a master de-activate date of 7/1/15, we need you to change it to 7/1/2016.

2. For any teachers who have de-activate dates of 7/1/15 to the six Missouri libraries (Agriscience, Horticulture, Animals, Plants & Soils, Ag Mechanics, Agribusiness, and Environmental Resources) we need you to change them to 7/1/2016. This includes lesson plan, Eunit, and CSAT access for the six libraries.

Please let em know if you have questions.

**Comment by bguerrettaz** [comment]
I will work on this request.

Blake

**Comment by bguerrettaz** [comment]
This request is now complete.  Please spot check to confirm.

Blake

**Comment by mnichols13** [comment]
Blake,
We have about 25 teachers in MO and MN that did not get their master activate date changed.  Here is the report.  I apologize that I didn't run this before we closed the issue.  Can you take a look and see why these teachers did not get included? 

http://www.mycaert.com/admin/Reports/PrintUserAccounts.asp?SortBy=TeacherDeactivateDate&State=%27MN%27,%27MO%27&FromDate=2015-07-01&ToDate=2015-07-01&IncludeExpired=

**Comment by mnichols13** [comment]
http://www.mycaert.com/admin/Reports/PrintUserAccounts.asp?SortBy=TeacherDeactivateDate&State=%27MN%27,%27MO%27&FromDate=2015-07-01&ToDate=2015-07-01&IncludeExpired=

**Comment by mnichols13** [comment]
Blake - looks like everything you did worked the way it was supposed to and the teachers that were inactive should not have been updated.  Thanks !
