### ISSUE TITLE
Kay Poland - activation dates not working properly

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#145]
Kay Poland is a teacher with a National account.  She has a master activation date of 6/15/2015, but I set her individual library activation dates to 7/1/2015 - 7/1/2016.  She previously had an active account whereby she was able to set up course outlines.   Even though she has no active libraries according to her dates, she can still open these course outlines previously created.     

Please take a look and see how we can correct this.

**Comment by bguerrettaz** [comment]
I see the problem.  We take care of access restrictions in most places.
One place I see we aren't is when the user hovers over 'My Courses' and can
see their old saved course outlines, etc.

To fix this, we can try two approaches:

-Check the three activation date tables and assure they don't have any
valid subscriptions.  If they don't, the hover over will be disabled, since
they don't have access to anything under that tab anyway.  This works if
they have no subscriptions

-The second option is if they do have access to any course outline, they
will still be able to get the hover to work, so do we want to get more
granular and check each course outline they click on to see if they have
access and if they do not, give them a message?

The first one would be an all or nothing.  The second option would cover
each course outline and check if they have the required subscription to
view it and everything attached to it.

Thoughts?

**Comment by mnichols13** [comment]
-Check the three activation date tables and assure they don't have any
valid subscriptions. If they don't, the hover over will be disabled, since
they don't have access to anything under that tab anyway. This works if
they have no subscriptions - 

What if they do have some active and some not active?  Then how would this address the course outlines that have inactive subscriptions?

**Comment by bguerrettaz** [comment]
That's where the second option is needed, it covers both scenarios.

The one you referenced in your email is all or nothing, meaning, if they
have some valid and some invalid, they see call.

I think the long-term fix is to check each one, if they have access, it
shows, if they don't, its removed from the list.

**Comment by mnichols13** [comment]
We do not need for you to disable the hover, just do the check for active libraries.  It is fine for them to see their course outline listing and even export the titles.    

What are you referring to as far as removing from the list?

**Comment by bguerrettaz** [comment]
I agree, that approach is faster, but definitely not better.

I just a way to connect the course outline with a lesson plan/eUnit/CSAT so
I can check subscription status.  If they are subscribed to one or more of
those items, then it stays in the list.  If they aren't subscribed to a
lesson plan/eUnit/CSAT connected to the course outline, we remove it from
the list displayed under My Saved Course Outline.

Does that sound right?

**Comment by mnichols13** [comment]
No - it is important that you understand the CSAT subscription is completely separate from the lesson plans and E-units.     When a teacher subscribes to CSAT they get access to every library's questions, but they may only subscribe to one lesson library.  

So it needs to check for lesson plans only -  a teacher cannot subscribe to the E-unit without the lesson plan.  Maybe this makes it simpler?   Can you give us a time estimate on this?

**Comment by bguerrettaz** [comment]
Got it.  So I need to find which lesson plan is attached to the course
outline, if they have access to that, then they can view the course
outline, if not, they can't.

Probably 4-5 hours for this.

**Comment by dpentony** [comment]
4 to 5 hours is OK. Mindy, please confirm that Blake's understanding is correct.

**Comment by mnichols13** [comment]
Blake your understanding is now correct, please proceed.

**Comment by bguerrettaz** [comment]
Ok, this was a little more complicated then originally expected, but I have
a query together and tested now.

From my testing, everything seems to be working as requested, but please
test and confirm.

If there are any issues, I can easily back out the changes.

Please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
When I click on Kay Poland's outlines I can still open them even though her active dates for the libraries aren't until July 1.  I am not seeing the fix?

**Comment by bguerrettaz** [comment]
Good catch, I had to make another change to the query to account for that.

Please test and confirm.

Blake

**Comment by mnichols13** [comment]
The way it has always worked in the past - and how we would like it to continue to work:  

The teacher could see Course Outline titles - then when they try to open the course outline, they get a message that their subscription has expired to these lessons.  

It allowed the teachers to export the course outline without opening lesson plans to see what the lesson titles were in that particular course outline.

**Comment by bguerrettaz** [comment]
This is a change from how I thought we agreed it was supposed to work.
I'll have to revert my changes and then figure out why that isn't working
correctly (since I'm assuming that is how it was always supposed to work?)

**Comment by mnichols13** [comment]
![image](https://cloud.githubusercontent.com/assets/5790342/8435243/dcc210d0-1f15-11e5-9d08-bd380f7f7c61.png)

**Comment by bguerrettaz** [comment]
Yes, when I said hover I meant, if they didn't have access to anything,
when they hover over Courses, it wouldn't show a submenu at all.

I didn't disable the hover and submenu functionality, just the list of
course outlines if they didn't have access to libraries connected to those
course outlines.

I can revert the changes I made if that's not what is wanted.  But they
question still remains, was this ever working as desired?

**Comment by mnichols13** [comment]
Yes it was working as desired, I don't know when it stopped working.

**Comment by bguerrettaz** [comment]
Ok, I think I have this working as desired.  I used Kay Poland as my test:

[image: Inline image 1]

Can you please test a few teachers to make sure this is working correctly?
If not, I can use the teacher that isn't as a test.

Please let me know if I'm missing anything.

Thanks,
Blake

**Comment by mnichols13** [comment]
unfortunately it is not fixed..  I went into the admin site and change her libraries to an activate date of 8/1/2015 and was still able to open the libraries...  I had to change them back so now they are set to 7/1/2015 since that is the date they were supposed to be activated.    If you want to test it, you can do the same, but the dates need to be set at 7/1/2015 when you are done testing.

**Comment by mnichols13** [comment]
I created a dummy teacher that you can play around with:
State:  MT
username: Mindy
password:  Nichols

This account has the same issue - no active libraries, but the outlines can be opened.

**Comment by bguerrettaz** [comment]
Ok, I have rewritten the query used and tested a few accounts.  Please test
some accounts that should and should not have access and let me know.

If there are issues, I can quickly revert back to work on the changes again
and not impact the users.

Please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks correct now - Thanks!
