### ISSUE TITLE
Update Minnesota State MYcaert Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#146]
Minnesota has paid to extend their state subscription by one year. We need you to update the subscriptions based on the following parameters:

1. For any teacher in MN who has a master de-activate date of 7/1/2015, please change this date to 7/1/2016.

2. For any teachers who have expirations dates of 7/1/2015 on the following 5 libraries: Animals, Plants & Soils - Revised, Biological Science in Ag, Environmental Resources, Animals, Plants & Soils, and Minnesota Natural Resources libraries, please change their expiration dates for lesson plans, Eunits, and CSAT for these libraries to 7/1/2016.

We would need this done before July 1.

Thanks. Please let us know if you need additional info.

**Comment by bguerrettaz** [comment]
This is complete, please test and confirm.

Blake

**Comment by dpentony** [comment]
@bguerrettaz  - is there a way you can take a high-level look to determine what percentage of the MN teachers have used the testing component? Perhaps there is some data that shows how many teachers had students take tests during the last school year?

MN is looking at pricing for next year. They currently pay for all teachers to to access the assessment component, but our feel is only a few of them use it.

**Comment by bguerrettaz** [comment]
Dan - I wrote some queries to get these numbers for you, below is the
information with supporting queries.

Let me know if you need anything else.

Thanks,
Blake


--------------------------------------------------------------------------------------------------------------------------------------------
--23 MN teachers created a one or more tests for the 2014-2015 school year

select distinct test.TeacherID from tblTest test
join tblTeacher teacher on test.TeacherID = teacher.TeacherID
join tblSchool school on teacher.SchoolID = school.SchoolID
where school.State = 'MN'
and DateCreated between '07/01/2014' and '07/01/2015'

--378 MN teachers total

select distinct t.TeacherID from tblTeacher t
join tblSchool s on t.SchoolID = s.SchoolID
where s.State = 'MN'
--------------------------------------------------------------------------------------------------------------------------------------------
