### ISSUE TITLE
Exprired Accounts for Some IL CTE Teachers

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#147]
See my email and attachment of this date. We neglected to update a parameter that controls the end dates for when the IL Admin adds new CTE teachers. So, there are about 130 IL CTE teachers who were recently added that have an end date of July 1, 2015. We need the master end date and those for the CTE libraries updated for these teachers to 7/1/2016 instead of 7/1/15.

**Comment by bguerrettaz** [comment]
When were these added?  I'm trying to find something that I can script off
of.  Right now there are 166 CTE, IL teachers with a deactivedate of 7.1.15

Blake

**Comment by dpentony** [comment]
Please use 1/1/2015 as the cutoff date.

**Comment by bguerrettaz** [comment]
Do you mean date entered into the system of 1.1.15?  If so, I've still got
160.

The activate dates are all greater than 1.1.15 as well.

**Comment by dpentony** [comment]
I mean any added between 1.1.15 through today.

**Comment by bguerrettaz** [comment]
Yes, I did that and that number was 160.

**Comment by dpentony** [comment]
Could you please update those 160 so they have an end date of 7/1/16?

**Comment by bguerrettaz** [comment]
Yes, I'll work on that.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
This is now complete.

Blake
