### ISSUE TITLE
Unable to export course outline to Excel/Word

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#148]
Debbie Hopper has an account in IL. She created and saved a course outline called Care and Learning Services Validation. The outline comes up fine, but she is unable to export it to Word or Excel. She gets a white screen and nothing will come up. I was able to replicate the issue.

Please look into this and advise when you can have it corrected.

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
We are traveling this weekend.  I will look at this tonight.

Blake

**Comment by bguerrettaz** [comment]
This again is a performance type issue.  This outline is very large.  I was
able to put some HTML flushes in place to get it from timing out.

Blake

**Comment by dpentony** [comment]
Thanks for fixing this.

@bguerrettaz - what constitutes a large outline? This one only has 50 lesson plans in it. Traditionally, an outline of 100 lessons would be considered large. I'm now wondering why one with only 50 is giving us a problem.

**Comment by bguerrettaz** [comment]
I'm not sure what the number is that triggers this timeout.  It's a
combination of lessons, units, problem areas and then the supplemental data
that goes around it to build this print out.

**Comment by dpentony** [comment]
@BrianPeterlin - what are your thoughts? An outline consisting of 50 lessons was never a problem in version 1.0. What changed so that now such a small outline is problematic when exporting it to Word/Excel?

**Comment by dpentony** [comment]
@BrianPeterlin - you never responded to this. What are your thoughts? There seems to be an issue with being able to export to Word/Excel when not that many lessons are included in a course outline. Under v1.0, we always told teachers not to create an outline greater than 75 lessons. This threshold seems to have been reduced in 2.0. Why?
