### ISSUE TITLE
Missouri Teacher homescreen (reopened on 5-17-23)

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#150]
When the MO teachers sign into MYcaert their homescreen does not show the lesson libraries like all other users.   What would it take to make this change so that they see the same thing as all other teachers rather than the MO courses?  Please give estimate
![image](https://cloud.githubusercontent.com/assets/5790342/8933530/f3fafaba-3508-11e5-9bd8-ead922419529.png)

**Comment by bguerrettaz** [comment]
I wanted to look over this to see what I think will go into it.  Barring no
surprises, it looks like roughly 4-8 hours of work.  Some things have to be
rewritten in order for this to work.  Plus I'll want to test several
different teachers accounts.

Oklahoma is in the same boat as MO, going to a different screen on login.
I'm not sure the reasoning.

Please let me know if you want to pursue.

Thanks,
Blake

**Comment by dpentony** [comment]
Please proceed with Missouri.

**Comment by bguerrettaz** [comment]
Ok, I have made the normal home screen available to MO users.  The only
caveat is that when they have no active subscriptions to lessons, they
won't see a list of lessons to build a course outline by lesson plan
library on the home screen.  Not sure how many users that actually is, but
I found one in testing.

Please test some MO users and confirm that everything is working
correctly.  Please also test a few non-MO accounts to assure that all users
are unchanged.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Mindy, I think you meant to post the errors you found this morning to this
issue and not the one about MyCommunity.

I've fixed those issues you found.  Please let me know if you encounter
anymore.

Thanks,
Blake

**Comment by mnichols13** [comment]
for some reason the old screen is showing up again for our Missouri teachers. see screenshot at the beginning of this post.

**Comment by mnichols13** [comment]
Blake, have you had a chance to take a look at this yet?

**Comment by bguerrettaz** [comment]
Yes, I had to hunt for another state reference to MO teachers that would be
pointing to the old page.  I found the code that wasn't caught and updated
it with the new code.

I tested and confirmed it is corrected, please test and confirm.

Blake

**Comment by mnichols13** [comment]
looks good!  thanks Blake

**Comment by mnichols13** [comment]
Blake - can you give an estimate on what it would take to go back to the old screen?  basically reverse this ? 
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/3595ecdb-d2f2-431a-986a-ce9a85bce025)

**Comment by mnichols13** [comment]
Please have this done by July 1, 2023 @bguerrettaz @jquesse

**Comment by LKocher** [comment]
@bguerrettaz, @BrianPeterlin, @jquesse  - Please provide an update on this request

**Comment by BrianPeterlin** [comment]
@bguerrettaz, can this be completed asap.  They have a demo tomorrow so maybe do not touch it tonight.

They have a workshop at the end of the month.

**Comment by bguerrettaz** [comment]
I won't make any live adjustments tonight.  This looks to be 2-3 hours.

**Comment by bguerrettaz** [comment]
Hi - I was able to complete this work as well.

Please confirm it looks as requested.

Thanks,
Blake
