### ISSUE TITLE
Upload students to MYcaert for Edwardsville HS.

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#151]
See Dan's email and attached Excel file sent to you on July 27.

**Comment by bguerrettaz** [comment]
This request is complete.  I have attached the Excel spreadsheet with all
of my formatting for inserting into the database.

I will save the query I wrote in case of any issues.  I have also backed up
the student table as a precaution.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. I will have the teacher take a look at the students before closing this issue.
