### ISSUE TITLE
MYcaert 1.0 site unavailable -error message

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#152]
Microsoft OLE DB Provider for SQL Server error '80040e14'

The transaction log for database 'csat2' is full. To find out why space in the log cannot be reused, see the log_reuse_wait_desc column in sys.databases

/login.asp, line 526

**Comment by mnichols13** [comment]
can you delete these course for the following teacher in IL: 

Todd Ehlers
U: TEhlers
P: ehle7341
Ag 1, Ag 2, Ag 3& 4

They show up three places:
Manage course rosters
Choosing a course to assign a quiz
Maintaining E/units and ppts

**Comment by bguerrettaz** [comment]
Both of these are for MyCaert 1.0?

**Comment by mnichols13** [comment]
I tried to login to 1.0 in order to try and delete these old quiz classes.  So I guess this is two issues - 
1 - cannot login to 1.0
2 - quiz classes need deleted

**Comment by bguerrettaz** [comment]
This request is complete and mycaertold is back online.

Blake

**Comment by mnichols13** [comment]
My caert old is back online, but I am not able to delete these old quiz classes, can you please do this?
Teacher: Todd Ehlers
State:  IL
U: TEhlers
P: ehle7341
Ag 1, Ag 2, Ag 3& 4

They show up three places:
Manage course rosters
Choosing a course to assign a quiz
Maintaining E/units and ppts

**Comment by bguerrettaz** [comment]
If we are still talking about mycaertold, I did this yesterday and just
confirmed that is the case.

If you want this done on the current system, I'll have to do that today.

**Comment by mnichols13** [comment]
The whole point of this thread was to take care of the teacher request.  Yes, this still needs to be done.  Please do it ASAP.

**Comment by bguerrettaz** [comment]
Sorry, I was just going off of the title, which is for mycaertold.

**Comment by bguerrettaz** [comment]
This is complete.
