### ISSUE TITLE
Submit Order Link not working

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#154]
Could you please test the submit order link? I've had a couple of customers tell me it did not work. I tested it and after submitting the order I just get a white screen for the page http://mycaert.com/Submit_Order.asp. There is no acknowledgement that the order was submitted and I do not receive the order via email.

**Comment by dpentony** [comment]
@bguerrettaz - not sure if you are in the midst of testing on this. I got a test message on the Free 30-day Trial Request. Just want to make sure you understand that this issue relates to the Submit Order link.

**Comment by bguerrettaz** [comment]
Yep, I just wanted to make sure that the SMTP server that we use for both
isn't down.  I'm still testing, sorry for the random emails.

Blake

**Comment by bguerrettaz** [comment]
It seems like the SMTP connection has slowed down with GoDaddy for whatever
reason.  I'm not sure if we've seen this before or not.

I did restart the email service and that got one through.  Can you try
another one to see if you get one through as well?

Thanks,
Blake

**Comment by dpentony** [comment]
Still not working. I could not get a test to go through.

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
I'm currently still looking into this.  I've had mixed results, sometimes
it goes through, other times it doesn't.

I'll update soon.

**Comment by dpentony** [comment]
What's going on with this?

**Comment by bguerrettaz** [comment]
I've worked on it tonight as well.  I can't pinpoint why this page is any
different than the free trial.  It uses the same email client to send
emails.

I rebooted the server an hour or so ago to see if it was something with
that.

When did you start to notice this?

@Brian - anything changed with the GoDaddy SMTP account?

**Comment by bguerrettaz** [comment]
Brian - I've spend over 4 hours looking into this issue.  I've tried many
different things, still nothing.

It is an automatic 500 after exactly 20 seconds after the Mail.Send
command.  Thought it was due to the GoDaddy SMTP, but other pages with the
same code work correctly.

Ever seen anything like this before?

**Comment by dpentony** [comment]
I first noticed it on the day it was posted to github. A customer called and said they had tried  to submit an order online. I then tried submitting a test order several times and was able to duplicate the  problem.

**Comment by dpentony** [comment]
I've tried the link a few times today. I get a notice that the order was successfully sent, but I never received it via email. This concerns as it gives the appearance to our customers that the order was successfully sent. Perhaps we need to hide the Submit Order link until this is rectified.

**Comment by bguerrettaz** [comment]
I've already hidden the Submit button temporarily (around 1pm) to make sure
users weren't getting these false positives.

@brian - is this something that we need to open up with GoDaddy?

**Comment by BrianPeterlin** [comment]
try now

http://www.mycaert.com/submit_order.asp

if you agree it is working, we will make it live again

**Comment by dpentony** [comment]
I did a test and it worked

**Comment by BrianPeterlin** [comment]
@blake can you make it live

On Wed, Aug 19, 2015 at 7:56 PM, dpentony <notifications@github.com> wrote:

> I did a test and it worked
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyCaert/Issues-Enhancements/issues/154#issuecomment-132840145>
> .
>



-- 
Brian Peterlin
bpeterlin@cmiti.com
Cell# 309 310 4551

**Comment by BrianPeterlin** [comment]
I am not sure why we could not send out GoDaddy's smtp servers, so I tried
using the local machine.  I found that Godaddy was blacklisting the IP
address, so I routed the mail to another one of our servers to send out
messages and it worked.  I will still investigate why GoDaddy is
blacklisting.

On Wed, Aug 19, 2015 at 7:57 PM, Brian Peterlin <bpeterlin@cmiti.com> wrote:

> @blake can you make it live
>
> On Wed, Aug 19, 2015 at 7:56 PM, dpentony <notifications@github.com>
> wrote:
>
>> I did a test and it worked
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MyCaert/Issues-Enhancements/issues/154#issuecomment-132840145>
>> .
>>
>
>
>
> --
> Brian Peterlin
> bpeterlin@cmiti.com
> Cell# 309 310 4551
>



-- 
Brian Peterlin
bpeterlin@cmiti.com
Cell# 309 310 4551

**Comment by bguerrettaz** [comment]
Done.

**Comment by dpentony** [comment]
I am not sure if the submit order link is working. I had a teacher tell me he had submitted an order online but we never got it. I then submitted an order. It's been two hours and it has not been received.

**Comment by dpentony** [comment]
This is definitely not working. I never did receive the order I submitted yesterday.

**Comment by dpentony** [comment]
@BrianPeterlin - what's the plan?

**Comment by dpentony** [comment]
@BrianPeterlin - WHAT IS THE PLAN FOR THIS?

**Comment by BrianPeterlin** [comment]
i will find a different smtp server

 Brian Peterlin
1-309-310-4551

**Comment by BrianPeterlin** [comment]
I think i figured it out.

give it a try.

The sender address was admin@caert.com.  i changed it to noreply@caert.net,
which is the account sending the email.  GoDaddy changed their rules, which
caused this to start happening.



On Mon, Oct 5, 2015 at 1:18 PM, Brian Peterlin <peterlin3@gmail.com> wrote:

> i will find a different smtp server
>
>  Brian Peterlin
> 1-309-310-4551
> Sent from my iPhone
>
>
> On Oct 5, 2015, at 10:19 AM, dpentony <notifications@github.com> wrote:
>
> @BrianPeterlin <https://github.com/BrianPeterlin> - WHAT IS THE PLAN FOR
> THIS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MyCaert/Issues-Enhancements/issues/154#issuecomment-145567115>
> .
>
>


-- 
Brian Peterlin
bpeterlin@cmiti.com
Cell# 309 310 4551

**Comment by dpentony** [comment]
This is not working again. We had a customer who submitted an order 24 hours before and we never received it. I did a test and we never received it.

**Comment by dpentony** [comment]
@BrianPeterlin  - what's the status on this?

**Comment by BrianPeterlin** [comment]
This should be closed
