### ISSUE TITLE
Aligning WI AG standards - issue

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#155]
When I am aligning WI AG standards, there are seven performance indicators under the AG standard: PSTS 1e, they are: 
1e
2m
3m
4m
5h
6h
7h

I should be able to choose all of these performance indicators and align them to one lesson in one entry.  However for some reason, they show up under 1e in 5 different places, which means I have to make five entries, rather than one.   This is not the only one like this, it is also the case for 1f

I have a screen shot so you can see how it shows up multiple times rather than once the way it should 
![image](https://cloud.githubusercontent.com/assets/5790342/9340605/5b9bc84e-45b6-11e5-91a4-ed879c2fd7dd.png)

**Comment by bguerrettaz** [comment]
This has been resolved.  Please test and confirm.  The issue had to do with
the sort order entered for each of those repeating entities.  I've updated
those and tested.

Blake

**Comment by mnichols13** [comment]
this is fixed, thanks.
