### ISSUE TITLE
Export to Excel/Word links are not working correctly

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#156]
Kevin Rice is a teacher in Colorado. He created a course outline called Ag Mechanics. When he attempts to export the outline to Excel/Word using the links at the top of the outline (see highlights in screenshot 1 below), He gets an exported report with a lot of junk in it and it does not include all of the lessons in his outline. The outline is made up of both Ag Mechanics (AMT) and Horticulture (HC) lessons, but the exported report does not show the Horticulture lessons.

If however, you click on the Print Course Outline at the top of his course outline (see red arrow below) a new page comes up. From that new page, you can click on the Export to Word/Excel links (see screenshot #2) and the exported reports are fine - no junk and the Hort lessons are included.

Shouldn't the export links on the two pages act in the same way? If we cannot get the Export links in the first screenshot to work correctly (this has been a problem), perhaps we should change the links so that they take the user to the same page as the Export links in the second screenshot.

![image](https://cloud.githubusercontent.com/assets/5790325/9365752/e99e9924-4678-11e5-862f-9d51e27dbe2b.png)

![image](https://cloud.githubusercontent.com/assets/5790325/9365822/4ff31506-4679-11e5-86b4-ef40abd49b01.png)

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
More to come, I've been looking into this.

**Comment by bguerrettaz** [comment]
I've taken the junk text out of the course outline, but do see that the
Hort lessons are missing.

The two different methods to export an outline were developed that way.
When you use one of the two links from the course outline view, its
displayed one way, when you go through the print first, then export to
excel, its displayed another way.

I can make them all the same with some work, but its state specific or I
can invest some time in seeing why the Hort lessons are missing and leave
these two views the way they are today.

Which way do you prefer?

**Comment by dpentony** [comment]
Couldn't the the links at the two different locations just be pointed to the same spot? For instance, when you click the Export link at the top of the course outline, could that not take the user to the same page as when you click Export after you click the print link?

**Comment by bguerrettaz** [comment]
Yes, they could.  So you want all three buttons to go to the same page as the Print Course Outline button does today or do you want a button to replace all three that says 'Print/Export Course Outline'.

Doing this means they are all going to be printed/exported via the layout that is displayed here:

![image](https://cloud.githubusercontent.com/assets/5695475/9471593/c2caa9bc-4b16-11e5-997f-dd47085a744b.png)

Instead of this layout:

![image](https://cloud.githubusercontent.com/assets/5695475/9471719/4a055120-4b17-11e5-85ac-60f9f5e7adc8.png)

Is that ok?

**Comment by dpentony** [comment]
I was thinking that the same page would come up whether they clicked on Export to Excel on the first page or if they did so after hitting print course outline. That page exported to Excel looks like the screen shot below. Is that possible? It would be the same if they clicked on Export to Word. Either way, the actual exported report would come up and not the print course outline page.

![image](https://cloud.githubusercontent.com/assets/5790325/9472301/17d91a30-4b1a-11e5-98da-d83169d14131.png)

**Comment by bguerrettaz** [comment]
Yes, if the report you want exported (via Word or Excel) is in the last
screenshot you sent me, I should be able to make that happen.

I just wanted to let you know that the other format (it looks like my
second screenshot) won't be the 'look' of the export anymore if we make
these changes.

Blake

**Comment by dpentony** [comment]
I realize that it will not look like the format in second screenshot. I just wanted to be sure you could in fact do it. Please give a some time to think this through.

**Comment by bguerrettaz** [comment]
Sounds good.

**Comment by dpentony** [comment]
@bguerrettaz - I am still trying to think this one through. You previously said:

"I can make them all the same with some work, but its state specific or I
can invest some time in seeing why the Hort lessons are missing and leave
these two views the way they are today".

Can you invest some time to see why the hort lessons are not showing up when you export from the course outline page? I'd like to get that format working as it is the one the teachers are used to.

**Comment by bguerrettaz** [comment]
Yes, I'm currently working on this.

**Comment by bguerrettaz** [comment]
Ok, I finally found the issue.  The sort order in the database is messing up this entire course outline.

I'm not exactly sure how the sort order got so out of whack, but it definitely is, see here:

![image](https://cloud.githubusercontent.com/assets/5695475/9604954/39d44c02-5080-11e5-9b8c-382a0aea6842.png)


Those numbers in the SortOrder column are supposed to be completely sequential, instead there are random gaps in between each number.  I will have to change every row to get them sequential.

I'll update when I'm finished.

Blake

**Comment by bguerrettaz** [comment]
Ok, I have updated those records in the database.  Kevin's course outline is now fixed.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks
