### ISSUE TITLE
Import Quizzes Not Working

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#157]
Via the admin page, we have the ability to import course outlines and quizzes from one teacher's profile to another's. I am trying to import quizzes from Joe Steffen's  (Newark, IL) ag account to Trent Taber's account at Cambridge, IL. To do so, we go to edit Trent's profile and then click on the Import Outlines/Quizzes link at top of the page. See highlight in screenshot below.

![image](https://cloud.githubusercontent.com/assets/5790325/9392224/0f7641d8-4741-11e5-8c34-bac84409df67.png)

This brings up a page where you can select Joe Steffen as the teacher you want to import from. You can then select the quizzes to import. I tried to import the Parli Pro 2014 Test. 

After selecting the test and then clicking the Import Quizzes link at the bottom, I get kicked out of the page and am brought back to the Admin login page. No quizzes are being imported.

**Comment by dpentony** [comment]
What's the status on this?

**Comment by bguerrettaz** [comment]
This is now fixed and working correctly.  The issue was the submit button
for quizzes was pointed to the wrong redirect page and the page that
inserts into the database didn't have the list of quizzes from the previous
page.

I have fixed all the issues and tested.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
My initial testing looks good. I will do further testng in the morning to make sure before closing out this issue.

**Comment by dpentony** [comment]
This does not appear to be working this morning. I tried to import several quizzes at once from Joe Steffen's IL account to Trent Taber's. I had a list of about 30 quizzes to import. I did them in groups of 10. Although the page said I was successful in importing the quizzes, they do not show up under Trent Taber's account. I then tried to import a single quiz and that was unsuccessful. I was able to import one quiz last night.

Here is a list of a few of Steffen's quizzes you might try to import to Taber's account:

2015 Animal Products and Classification
2015 Ag Law and Contracts Quiz
2015 Introduction t Animal Science Test
Ag Business 2015
Intro to Ag Horse Test 2015

**Comment by bguerrettaz** [comment]
Ok, after I saw the code last night, it seemed incomplete.  Have you used
this before?  Did it work correctly?  I can't imagine it did because it
wasn't even calling the data elements correctly.

I'll have to keep looking into this one.

Blake

**Comment by dpentony** [comment]
I used it extensively almost one year ago to the day. At that time, I was able to import quizzes in batches of about 10 from one IL teacher to another.

**Comment by bguerrettaz** [comment]
Ok, that complicates things, since I'm not sure why it would all of a
sudden stop working.  I'll get to the bottom of it.

**Comment by dpentony** [comment]
I am not sure why I was able to import one quiz last night but was unsuccessful doing so this morning - whether it was a batch of 10 or just a single quiz.

**Comment by bguerrettaz** [comment]
But neither the single quiz or the groups of 10 worked this morning,
correct?  Yeah, I can't explain that either.

**Comment by dpentony** [comment]
Correct

**Comment by bguerrettaz** [comment]
Ok, give this another shot.  Looks like I've got everything set correctly
now.

Blake

**Comment by dpentony** [comment]
I want to hold off on testing it. Something is not right. I went Joe Steffen's account to import quizzes from his account into Trent Taber's. As I reviewed Joe's list of quizzes, it appears that those I previously tried to import have been duplicated in Joe's account. So, instead of importing them into Trent's account, they are duplicating them in Joe's account. 

Look at the tests listed below. These are just some of those I tried importing earlier today. They are now showing up twice under Joe's account and they have not been imported to Trent's.

2015 Animal Products and Classification
2015 Ag Law and Contracts Quiz
2015 Introduction t Animal Science Test
Ag Business 2015
Intro to Ag Horse Test 2015

**Comment by bguerrettaz** [comment]
Yes, the teacherID that was used in the code was the wrong one, it was the
ID of the teacher being imported, instead of the teacher that needed the
quiz.  I fixed that, and tested between your account and Mindy's.

I also had to switch it for the related test questions.

So we should be covered.  The reason Trent didn't have multiples is because
the looping wasn't working correctly either (for more than one quiz).

If you test with you and/or Mindy's account, you should be able to verify
this is working now.

**Comment by dpentony** [comment]
It is now working, but it does not show who the imported quiz came from. Usually it will show the name of the quiz and the person if was imported from. For instance under my account it would say Basic Ag 2013 - Mindy Nichols. This would show that it was imported into my account from Mindy's. All it is showing now is the name of a quiz followed by a hyphen. It does not show who it came from.

The importing is working. It just does not show who it came from.

**Comment by bguerrettaz** [comment]
Ok, I should be able to fix that easily, I'll get back to you when that is
fixed.

**Comment by bguerrettaz** [comment]
Ok, give it a shot now, name should properly display as desired.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
