### ISSUE TITLE
Current School Year Test Scores - Detailed Reports not Coming up

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#158]
Curt Robbins is a teacher in IL. Last week he gave a quiz in his Basic Ag Mechanics course. The quiz is called Electricity & Safety Quiz. When you pull up the results for that quiz, the page loads very slowly, but eventually all of the student results show up. In the upper left corner of the page is a link to see View Details. The teacher wants to see the Details. When he clicks on the link, this url comes up, but the page never displays: http://mycaert.com/Teachers/csat/QuizReportDetailsAll.asp?StateOverride=&TeacherID=294&SchoolID=95&TestID=50219.

Please look into this. We're not sure why this particular quiz is giving us trouble. It may have to do with how slowly the basic test results page loads.

**Comment by dpentony** [comment]
Any updates on this issue?

**Comment by bguerrettaz** [comment]
Ok, this has two parts to it.  The query that feeds the data on the page
take a long time to execute and return the results.  For each student, that
query has to be executed and data displayed.

I put in flushing and a loading image while the page is being loaded, but
that is just a band-aid.  The page still take a long time to load, but does
load without timing out.

If you'd like me to dig into the queries and a possible rewrite of the
queries, please let me know.

Blake

**Comment by dpentony** [comment]
Thanks. Please do a little digging to determine if a rewrite is needed and its estimated cost.

**Comment by bguerrettaz** [comment]
Ok, I did some more research on this issue.

There are 6 queries that are executed per student.  Each 'set' of queries
takes 4-7 seconds per student, depending on the number of submissions they
have.  This all adds up to the total time to load a page (number of
students, number of submissions).

There's no clear cut way to improve these with the current output and
without a rewrite of the process.  If you'd like me to estimate a rewrite
of the current process, please let me know and I'd be happy to do so.

Thanks,
Blake

**Comment by dpentony** [comment]
Before you put the flushing and loading image in, we could never get the page to come up. I waited a good 15 minutes and never did get it to load. Now that the flushing has been put in, at least the page loads. So, I think that is improvement. I think we'll just have to deal with these sorts of items on a case-by-case basis.
