### ISSUE TITLE
URGENT - WI MYcaert Pages Not Displaying Correctly

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#159]
Jeff Griffey from WI contacted us. The pages when he opens his saved course outlines are not displaying correctly. See screenshot below. The highlighted parts shows a link for an HIV site instead of showing the NEW WI Ag Standard. Also the parts of the page in red circles are not displaying correct.

 
![image](https://cloud.githubusercontent.com/assets/5790325/9852955/a865e8ec-5ac6-11e5-9751-73492e6c7670.png)

This appears to affect all WI users. The weird link is showing up both when they simply search for lessons and in their saved course outlines. It is showing for lessons from multiple libraries.

Mindy looked at the associations on the admin site. That junk that shows up for the user is also showing up on the admin site. However she did not put it there. She deleted the junk from the admin site for one standard and it no longer shows for the user. However, we do not know how many standards are affected and cannot possibly check them all. 

The standards were entered and the associations were made over a year ago and we've never seen this before today.

Urgent - Please advise!

**Comment by bguerrettaz** [comment]
Ok, I found the issue.  It looks like this was some sort of SQL injection.
I'm not sure where it was injected or by whom, but here is the injection:

<div style="display:none">symptoms of hiv in men <a href="
http://thegeorgiaclubforum.com/page/aids-tests">thegeorgiaclubforum.com</a>
cause of hiv</div>

I'll have to go through all of the Wisconsin  learning priorities and
cleanup all of the bad records.  It might be a stolen/obtained Wisconsin
admin username/password?  I would suggest changing the Wisconsin state
admin password.

I'll work on cleaning up the records and report back.

Blake

**Comment by bguerrettaz** [comment]
Just found another table, tblWisconsin_GradeBand.  I'll have to clean that
up as well.

**Comment by dpentony** [comment]
Can you tell me what the existing logins are for the WI admin site? I don't recall ever setting them up with logins.

**Comment by bguerrettaz** [comment]
These are the WI admin accounts:

cmiti.com (our account)
joewebel
daniel
stateadmin
WIAGED

**Comment by bguerrettaz** [comment]
Looks like all WI tables have that data.  This will take some time to clean
up.

**Comment by dpentony** [comment]
What's the user name and password for the WI admin site? I tried stateadmin and WIAGED and they did not work. I also tried joewebel and daniel with the same result.

**Comment by bguerrettaz** [comment]
Username Password
joewebel webel22075
daniel cathy
stateadmin wisconsin
WIAGED badgers

**Comment by bguerrettaz** [comment]
Ok, I think I have all of the data finally cleaned up.

Brian and I think the problem comes from the actual admin login page.
There isn't any SQL injection safe guarding in place on that login page.

I suggest that we put that in place and test some scenarios.  Probably 3-4
hours worth of work/testing.

Please let me know your thoughts.

Blake

**Comment by dpentony** [comment]
I am not opposed to doing this, but can you explain what you mean by "There isn't any SQL injection safe guarding in place on that login page"? I want to fully understand how this happened and whatSQL injection safeguarding is and how it will help.

**Comment by bguerrettaz** [comment]
Sure, no problem.

On the main login page there is code in place to detect SQL injection
attacks.  That code looks for certain traits or attributes with the
incoming form data and catches it before its posted to the database.

I'm purposing we add that same kind of safeguarding to the admin login to
avoid this type of issue in the future.

Please let me know if you have further questions.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. Based on your estimate of 3 - 4 hours, please proceed.

**Comment by bguerrettaz** [comment]
Ok, I have finished and tested the SQL injection prevention code.  I used
parameterized queries for username, password and state for this login.

I changed this code in two places and tested both places.

Please test both with a state admin and a non-state admin.  For this login,
you are now protected from SQL injection attacks.

Thanks,
Blake

**Comment by mnichols13** [comment]
We have the same situation in the PSAA library

![image](https://cloud.githubusercontent.com/assets/5790342/9934186/55a1bb8a-5d15-11e5-8102-d74f6e24b8de.png)

**Comment by mnichols13** [comment]
Same problem exists in WI  _ PSAA library please help ASAP

![image](https://cloud.githubusercontent.com/assets/5790342/9934220/8e4ab18a-5d15-11e5-842d-ca0adb9453d1.png)

**Comment by mnichols13** [comment]
Blake,
This only affects unit C of PSAA - about 22 lessons.

**Comment by mnichols13** [comment]
Also affected:  BSAA library unit C

**Comment by bguerrettaz** [comment]
Ok, looks like more cleanup is necessary.  I'll get it cleaned up ASAP.

**Comment by bguerrettaz** [comment]
I'm also working on the cleanup, will update once complete.  Should be
today or tomorrow morning at latest.

**Comment by dpentony** [comment]
This is priority #1

**Comment by bguerrettaz** [comment]
Ok, in doing the cleanup, I've found that the tables that I've cleaned up
before, are now corrupted again with those entries.

So I suggest changing all WI admin passwords (since that is the only state
we've seen this).

It's going to take me a little bit cleaning it all up since I have to do it
again.

Brian - any thoughts on where this could be coming from?

**Comment by bguerrettaz** [comment]
I've changed all of the WI passwords to the following:

AdminID Username Password State
30 cmiti.com  itimc WI
31 joewebel          jw!2115! WI
32 daniel dc!2115! WI
33 stateadmin sa!2115! WI
39 WIAGED wi!2115! WI

**Comment by bguerrettaz** [comment]
I'm also going to snapshot those tables so if this happens again, we can
easily revert to the backed up tables.

**Comment by dpentony** [comment]
Could you send the new user names and passwords via a different format? The formatting in github makes it hard to understand what they are.

**Comment by bguerrettaz** [comment]
Ok, the tables are now cleaned up again and backed up incase it reoccurs.  Brian has turned on advanced web security to prevent SQL injection attacks as well as other common attacks.  We hope this solves the issue we are seeing.

Blake

**Comment by dpentony** [comment]
Thank you. We'll close this for now until we hear of any other reports.

**Comment by dpentony** [comment]
It is happening again. In this case it is with lessons in the Agriscience Revised library:

![image](https://cloud.githubusercontent.com/assets/5790325/10045205/7169dc34-61c6-11e5-8496-ed15f6062450.png)

**Comment by dpentony** [comment]
This is also affecting other libraries. I noticed it in the Hort Library lessons.

**Comment by bguerrettaz** [comment]
I've restored the bad tables with the good ones I took the other day.
Brian and I will talk this morning about additional steps to take.

Blake

**Comment by dpentony** [comment]
Thanks. I just texted Brian asking him to call me later. I just want to better understand this issue and how we can prevent it once and for all.

**Comment by dpentony** [comment]
Are you sure it is fixed? I'm still seeing the issue:

![image](https://cloud.githubusercontent.com/assets/5790325/10047024/a2067914-61d1-11e5-90a1-405d6fa66773.png)

**Comment by bguerrettaz** [comment]
It actually looks like the tables I created are also corrupted, which means
both the restore and the actual tables are corrupted.

I'll need to talk to Brian about next steps here.

I can cleanup again manually, but I didn't want to do so again without you
giving the go ahead.  It looks like after the cleanup, its corrupted again
a day later.

Blake

**Comment by dpentony** [comment]
Please do so manually.

Brian, I will look forward to talking to you today to learn more about next steps to prevent this.

**Comment by bguerrettaz** [comment]
Ok, this cleanup is completed again.

@Brian - what are our next steps here?

**Comment by dpentony** [comment]
Thanks. We'll continue to keep an eye on this.

**Comment by mnichols13** [comment]
Getting reports from Wisconsin teachers of same problem.  In Natural Resources library and Animal Plant and Soil Science... There may be others

**Comment by dpentony** [comment]
I thought the tables were going to be changed to Read Only. Did that occur? if so, how can they keep doing this?

**Comment by bguerrettaz** [comment]
I have cleaned up the data again.

We can't change the tables to read only because of the type of
user/security that is in place.

@Brian - any other options to help prevent this attack?

Blake

**Comment by dpentony** [comment]
This is the third time we've had to fix it in 2 weeks. We need a proactive solution to preventing a reoccurrence.

**Comment by bguerrettaz** [comment]
Brian and I spoke, I am going to put a last updated column on one of the
tables being attacked.  Then we will have a timestamp to use to look at
logs to see how this occuring.

@Brian - anymore to consider or preventative measures we can take?

**Comment by dpentony** [comment]
Some of the lessons from the Hort library still seem to be affected. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/10309562/dc6b7ce0-6c02-11e5-9e94-ccbbcdbf5113.png)

**Comment by bguerrettaz** [comment]
There was a straggler.  Cleaned up now.

Also, I have created a LastUpdated column on one of the troubled tables and
a trigger to update that field on update.  If the tables are hacked again,
we will know the exact time.

Blake
