### ISSUE TITLE
Removing the ability to post MY COMMUNITY to Ag Mechanics library

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#160]
Since we are nearly done with the new library: Ag Power Structure and Technical Systems - we will begin to phase out the Ag Mechanics library.  Would it be possible to remove the ability for teachers to post new items to the AG Mech library?   

Please advise a time estimate to do this.

**Comment by dpentony** [comment]
@bguerrettaz  - The pull down would need to hide the Ag Mechanics & Technology library when adding item through the MY Community tab. Also, we'd need to figure out a way to disable the Contribute link when any Ag Mechanics lessons are being pulled up by the user or if they are in existing course outlines.

**Comment by bguerrettaz** [comment]
This has a few parts to it, as Dan indicated above.  I think to add a
disable function, I'd have to add a column to the database (MyCommDisable)
or something along those lines, then put code in place on all the affected
pages.

I'd also have to build an admin interface so you/Mindy could disable
libraries at will.

Probably looking at a total of 7-9 hours IF there aren't any state specific
code pages.  I haven't gotten all the way through the analysis to know if
that's true or not, but if I find any, I will update this issue.

Please let me know if you want me to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
@mnichols13  - let's talk about this tomorrow. I am not sure if it justifies the time Blake would spend.

**Comment by bguerrettaz** [comment]
I'm almost done with it.  Shouldn't be more than 2-3 hours total.

**Comment by bguerrettaz** [comment]
Please disregard last email, I thought we were talking about another issue.
