### ISSUE TITLE
Add Ability to Make Multiple Quizzes Inactive at Once?

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#163]
If a teacher wants to make more than one quiz inactive, they have to open each quiz (Under Edit Quiz) and deactivate each one. Would there be a way to create a form where they could deactivate multiple quizzes without opening each one? I would see this similar to the Edit Students screen under MY Students where a teacher can make multiple students inactivate at once.

**Comment by bguerrettaz** [comment]
If you look under the 'My Quizzes' dropdown, there is an Edit Quiz and a
Web Enable/Disable Quiz selection.  They actually both go to the same page.

We could repurpose the Web Enable/Disable Quiz selection to go to a form,
similar to edit students, to allow the teachers to mass update the status
of their own quizzes.  Does that sound like what you are wanting?

Probably 6-7 hours for that.

Thanks,
Blake

**Comment by dpentony** [comment]
This might be doable. I think we'd need to rename the Web Enable/Disable Quiz link so that it provides a better description. Any ideas as to what we could call it?

**Comment by bguerrettaz** [comment]
We could name it:

- Activate/Deactivate Quizzes
- Bulk Activate/Deactivate Quizzes

something like that?

**Comment by dpentony** [comment]
I like Bulk Activate/Deactivate Quizzes. Please proceed when you have time.

**Comment by dpentony** [comment]
Do you have an estimate when you might be able to work on this?

**Comment by bguerrettaz** [comment]
I'm actually almost complete with this work, should be mid-week or so.

Blake

**Comment by bguerrettaz** [comment]
This is complete.  The new page is under My Quizzes --> Activate/Deactivate
Quizzes

Please review and test and confirm design/functionality.

Thanks,
Blake

**Comment by dpentony** [comment]
Something you did has prevented any teacher from making edits to a quiz. If you click on edit quiz and select a quiz, nothing happens. This is affecting all teachers!!!

**Comment by dpentony** [comment]
Before the change, when you clicked on edit quiz, it brought up a list of quizzes. I believe you could either view or edit the quiz.Those links are now gone and when you click on a quiz nothing happens.

**Comment by bguerrettaz** [comment]
This is fixed.  The new page I created had a clashing name with the actual
edit quiz page, which caused this (it was just overlapping each other).

Both the Edit Quiz and Activate/Deactivate Quizzes links are now correct.

**Comment by dpentony** [comment]
Thanks for your quick work. All looks good.
