### ISSUE TITLE
Missouri teacher has Microsoft 2013 and cannot open any powerpoints

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#164]
Do you have any suggestions for a teacher who has Microsoft 2013 - she cannot open our ppts or download and view any either.  We need a workaround for her and any other future calls that we get on this.  
![image](https://cloud.githubusercontent.com/assets/5790342/9997151/42b9f1de-6050-11e5-9f84-f6fd6a91cf36.png)

**Comment by mnichols13** [comment]
here is another error message she gets

![image](https://cloud.githubusercontent.com/assets/5790342/9997172/58949f9a-6050-11e5-8bf2-f8b54b18dfc2.png)

**Comment by bguerrettaz** [comment]
Here is a workaround for this, this is something we can't control:

To resolve the issue of opening an individual file, please follow these steps:

1)     Locate the file on your computer

2)     Right click the file and see the dropdown box which appears

3)     Look to the bottom of the dropdown box and select “Properties”

4)     In the “Properties” Window, you will see several tabs, the first of which should be “General”.  Select this tab if it is not already selected.

5)    At the bottom of this window you will see “Attributes” and “Security”.  Next to the word “Security” is a description stating “This file came from another computer and might be blocked to help protect this computer.”  and a box labeled “Unblock”.



6)     Click “Unblock” , then OK.

7)     Re-open the file by double clicking it, or opening it from PowerPoint’s “File” menu.

Note:  Once you’ve Unblocked a file, the “Security” label under the General tab will disappear.  This is normal and to be expected.

- See more at: http://www.presentermedia.com/blog/tag/powerpoint-found-a-problem-with-content/#sthash.lVzrnaX2.dpuf
