### ISSUE TITLE
IL teacher has a course not appearing in Manage course rosters

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#165]
Amanda Goin is an IL teacher at Griggsville-Perry HS.  She has created three course outlines.  When she tried to add students to one of them: AG INTRO, it simply does not show up in the Manage course roster drop down menu.   

It does show up in the Assign ppts/e-units drop down, but she cannot put students into the course to see the materials.  

Please help.

**Comment by dpentony** [comment]
Note: I made of copy of the Ag Intro Course and now it is visible under the Manage Course Roster pull down. However, the original version of that course still does not show up.

**Comment by bguerrettaz** [comment]
I manually inserted this record for this teacher.  After doing some
research, I'm not sure how this didn't get inserted correctly.  How was
this course outline created?  Was it different from the way everyone else
is doing it?  Have you seen this happen with anyone else?

Thanks,
Blake

**Comment by dpentony** [comment]
Since the teacher cannot tell us exactly how she created the outline and because we've not seen this with other users, I am going to close this issue for now.
