### ISSUE TITLE
Scoring Misc Questions NOT WORKING properly

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#166]
When a teacher writes their own quiz question with an open ended question there is an issue with grading.    This happens in the EDIT STUDENT ANSWERS on quiz link.  

Here is what happened:  Jay Williams scored a student with a 10 out of 20 and changed the drop down box to yes.  He hit save at the bottom of the screen.  He left the screen to input grades into the gradebook, when he returned to that screen, all of the scores were set at 20 and Yes has been checked.

I also created a quiz on my account with two essay questions worth 20 points.  I signed in as three students and took the quiz.  The exact thing happened as he describes it.  I graded the first question with the following points: 
student #1 : 20
student #2: 15
student #3: 10

I went to question two and assigned the same number of points.  When I jumped back to review the grades for question #1 it had assigned 20 points for all three students. 

![image](https://cloud.githubusercontent.com/assets/5790342/10079993/c290a178-62b2-11e5-80ec-b53c5851c8a3.png)

**Comment by bguerrettaz** [comment]
I've looked into this some and it looks like the scoring is correct (if you
look to the right of the box with 20 in it, it says 'Current 15/20 pt(s)'
and etc.)

From the looks of it, the allocated points box selected the 'MAX' of the
points available.  Would you like that changed to reflect the actual
current points?  I get why you would want it that way and why its confusing.

Let me know and I can work on this.

Thanks,
Blake

**Comment by mnichols13** [comment]
Yes it should actually reflect current points not max points.

**Comment by bguerrettaz** [comment]
This is now fixed.  Please test and confirm.

**Comment by mnichols13** [comment]
looks good - I will double check with the teacher and confirm he agrees.

**Comment by mnichols13** [comment]
Blake,
I believe when this change was made to fix the points when a teacher was grading, you unintentionally took out the autofill portion.  It should autofill, but it should also allow the teacher to overide that score.  I believe that it was working correctly at one time or we would not have teachers contacting us.  The problem previously was that they would change the score, but it would not save.  See below where the box is blank.  It should have the points possible pop up, but if a teacher needs to change it, then they would go in and make the change. 

![image](https://cloud.githubusercontent.com/assets/5790342/10580740/8dac0e20-7644-11e5-8290-661bd083fb93.png)

**Comment by bguerrettaz** [comment]
I have fixed this issue.  Please test and confirm.

Blake
