### ISSUE TITLE
Can't Upload New CTE Order Form

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#168]
I am attempting to upload a new CTE order form so that it appears under the Pricing tab on the home page. Under Admin, I go to Edit Content Under the Manage Content Banner. I then select Pricing and click edit. At the top of the page, I choose #3 Downloads. I then choose the file I want to upload, open it, add in a title and then click the Add File link. This is the error message I get:

Microsoft OLE DB Provider for SQL Server error '80004005'

Invalid connection string attribute

/admin/includes/FileUploaderClass.asp, line 91

I was successful in deleting the old order form, but need to get the new one added since there is no longer one showing for CTE.

**Comment by bguerrettaz** [comment]
This is fixed.  It was an IIS property that stated a maximum upload size
limit.  This one was just barely over the limit.  I made the limit more
reasonable for 2015 standards and went ahead and uploaded the document for
you.

You should be good to go.

Blake

**Comment by dpentony** [comment]
Thanks
