### ISSUE TITLE
Odd Student Test Results

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#169]
Jeff Sherer is an ag teacher in MO. He has a series of safety tests that he allows his students to take an unlimited number of times. They have to keep taking the tests until they get 100% on them. 

On several of the tests when he looks at individual students results under the current school year report, it often shows that the first time the student took the test they got 0/1, even though the test has 30 questions. This seems to happen quite often and he is sure the students did not answer just one question and submit the quiz. What could be causing this?

Also, please see text circled in red at the top of the student test report page. That shows up for every student. We need to get rid of it.

![image](https://cloud.githubusercontent.com/assets/5790325/10281600/3f72e58a-6b3b-11e5-99fb-4921df3a49f8.png)

**Comment by bguerrettaz** [comment]
Ok, I've removed what is circled in red and have done some analysis into
the issue with the first submission.

There is an issue I see in the database, but I'm curious if it is just with
this test and/or teacher or a problem in general.

Can you please test this scenario with a different teacher and test and let
me know?

Thanks,
Blake

**Comment by dpentony** [comment]
We'll do some further testing, but I do know that this issue was present in more than one of this teacher's safety tests.

**Comment by dpentony** [comment]
I did some further testing. The stuff circled in red no longer appears, but I still see the 0/1 test results on several tests. Check out any safety test for student Eric Steinhoff. He got 0/1 results on several instances of the same tests and on various tests. I can't believe he only submitted one right answer several times.

**Comment by dpentony** [comment]
Anything further on this?
