### ISSUE TITLE
CSAT test reports

### ISSUE THREAD

**Issue by bguerrettaz** [MyCaert/Issues-Enhancements#170]
Is there a way to find out how many of the IL CTE teachers have:
 
1. Created a test using CSAT in the last year?
 
2. Administered a test using CSAT in the last year?

**Comment by bguerrettaz** [comment]
A little clarification needed here:

- This is for IL teachers, with a focus of CTE?
- I'm going to use dates 10/1/14 to 10/1/15, is that ok?

Created =  the teacher created test
Administered = at least one student took a created test

Blake

**Comment by dpentony** [comment]
1. Yes, it is for IL teachers with a CTE focus.
2. Could you use the dates 7/1/14 to 6/30/15? That would encompass last fiscal year.
3. Created = a teacher created and saved a test during that period.
4. Administered = at least one student took the test.

We're wanting to see how many of the CTE teachers in IL are using CSAT. So, in addition to the above info, we'll also need to know how many total IL CTE teachers there are.

**Comment by bguerrettaz** [comment]
Got it, thank you.

Do you have any past years numbers, just so I have for reference?

**Comment by dpentony** [comment]
No numbers from pas years. Remember, at this point, we're just asking for an estimate of the time it would take to gather this info.

**Comment by bguerrettaz** [comment]
Ok, probably 2-3 hours.

**Comment by dpentony** [comment]
Please proceed.

Also, you might check with Darrell on this. He has developed similar info the past several years on the IL ag teachers at the request of ISBE. We were not involved, but I know he gathers similar info for ag.

**Comment by dpentony** [comment]
Where are you on this?

**Comment by bguerrettaz** [comment]
I have some numbers from a report I wrote, but I wanted to double check
with Darrell as to if I have the correct numbers related to previous
reports he has ran.  I've sent him a follow up  email.

**Comment by bguerrettaz** [comment]
I confirmed with Darrell that my queries and reports are correct.  I will
put them together for your view and send out tonight or tomorrow.

Blake

**Comment by bguerrettaz** [comment]
Attached at the reports (I sent them to your actual email because you can't
open them in GitHub.  I have titled them correctly, 'created' and
'administered'.

Looks like 67 IL, CTE teachers created a test in the dates specified.

Only 14 of those teachers actually administered a test.

Please let me know if you have any questions.

Thanks,
Blake
