### ISSUE TITLE
Delete Bio II course name choices when Assigning Students to a course

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#175]
Blaine Hartwick is an ag teacher in IL. He does not have a course outline called BIO II. However, when he goes to assign students to a course, that BIO II course shows up in the pulldown list of courses. See below. We need you to delete the BIO II course from the pull down list when he goes to assign students to courses.

![image](https://cloud.githubusercontent.com/assets/5790325/10884772/7c468448-813f-11e5-9c88-5141a47a20d1.png)

**Comment by bguerrettaz** [comment]
This is complete.
