### ISSUE TITLE
Eunits in Course Ouline not Displayed in same order  as those under Maintain Eunits

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#176]
Carter Turner is a teacher in WI. He has a course outline called Ag Surveying. When you look at the course outline, the first Eunit listed is 100001. However when you go to manage assigned Eunits and pull up that course, that same Eunit is listed way towards the bottom of the list. Why are the Eunits not listed in the same order in both locations?

**Comment by bguerrettaz** [comment]
I did some analysis into this issue, here is the answer to your question:

-The course outline is driven by a database table called tblCourseOutlineLessons, that's how the order of the course outline view is derived.
-The student maintain e-Units page is driven by a different table, tblAssignedEUnitsQuizClass.  The reason for this is the context in which the user is in.  In the first point, you are in the context of the course outline, in this point, you are in the context of the student.

I can work on getting them to match, but can't completely guarantee they will be identical.  One way to possibly sort them is by e-Units.

Let me know what you think.

**Comment by dpentony** [comment]
Please let me know how many hours might be involved. The order of the Eunits in the course outline should match those of the Eunits assigned to students.
