### ISSUE TITLE
Quote - Title Word Search Box for Editing Quizzes?

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#177]
What would it take to add a Title Word Search box when viewing the Edit or Activate/Deactivate Quizzes  pages? Long term teachers now have hundreds of quizzes under their profiles. Could a title word search box be added that would help them locate quizzes based on the titles of a quiz? What would it cost?

**Comment by bguerrettaz** [comment]
Yes, it would take 3-4 hours per page (Edit and Activate/Deactivate
Quizzes).

Another thing is to possibly consider an archive function for Quizzes so
teachers can archive older quizzes but yet retain them for their records or
to use later.

Thanks and let me know how to proceed.

Blake

**Comment by dpentony** [comment]
@mnichols13 - do you think we could get away with just having a search box on the Edit Quiz page and not including it on the Activate/Deactivate Quizzes page?

**Comment by mnichols13** [comment]
I'm not sure, what was the original intent?  The teacher can't remember the quiz name or what?

**Comment by dpentony** [comment]
Here is what the teacher said:

"Is there a way that we can "search" through quizzes based on title/topic? I know that I have 300+ and they are all different in terms of how they are titled and it takes so long to sort through them to even see if I have an existing quiz on a topic...all to find out that I do not. That time searching could have been better used creating a new quiz instead of looking through quizzes. Often times, my course names that I teach/offer change from year to year, so the categorizing be course doesn't always work."

As we worked with teachers at FFA, it hit me they have lots of tests. I am wondering if adding a search box would make it easier for them to find a test. I know when a teacher has a problem, it takes a while to find the test they are talking about.

**Comment by mnichols13** [comment]
Yes I think putting it on the Edit quiz page works fine.

**Comment by dpentony** [comment]
@bguerrettaz  - we want to do this, but only on the Edit Quiz page. I will review the list of outstanding issues this weekend and assign this item a priority.

**Comment by bguerrettaz** [comment]
I have completed this item today.  Please take a look at the Edit Quiz page and confirm the functionality.

If you'd like it somewhere else on the page, worded differently, etc., please let me know.

I did check and some of the work I did on this page could be reused for the Activate/Deactivate Quiz page if you're interested in me doing that as well.  I could probably get it done in 2 hours since I got this page done already.

Please let me know.

**Comment by dpentony** [comment]
It seems to work real well. Mindy and I will talk about wording on the location on the page. We may want to slightly re-word or re-position it. Thanks.
