### ISSUE TITLE
High Priority - Students Can Access Eunits that Teacher No Longer has Access to

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#178]
Michelle Howe is a teacher in WI. At one time, she had access to the Hort library. At that time she developed a Landscaping course outline. If you look at that course outline, there are no lessons listed since she no longer has access to the Hort Library. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/5790325/10952486/9f1aacae-8308-11e5-9764-6bcde3e5d341.png)

However, if you login as one of her students  (Jordan Shea) in the Landscaping course, they can still see the Eunits associated with that course. In the case of the Landscaping course, the students can see 64 Eunits which the teacher no longer has access to. 

![image](https://cloud.githubusercontent.com/assets/5790325/10952572/15ec8014-8309-11e5-8ec6-fcf55db6a613.png)

Because the teacher no longer has access to that library, the students should not be able to see the Eunits either. Please let us know how this can be fixed.

**Comment by bguerrettaz** [comment]
I'm currently looking into this.  Seems like a semi-complicated issue, I'll update soon.

**Comment by dpentony** [comment]
Please let us know when you find out what it would take to fix. From a common sense standpoint, the Eunits the students see should be in the same order as they are in the teacher's course outline.

**Comment by dpentony** [comment]
Disregard the latter part of my previous comment....I was thinking of another issue. Please let us know what this will take to fix. Students definitely should not have access to Eunits that the teacher no longer pays for.

**Comment by bguerrettaz** [comment]
Ok, I've spent some time on this issue this afternoon and its much more complicated than I initially thought.  There is currently no connection between the view for the e-units that the student sees and the subscription status of their teacher.

Information I do have is name of the actual course (Quiz Class), teacherID, studentID, and other information about the student.

I've been trying to connect all of the necessary dots for a while and haven't been able to find a connection.

@BrianPeterlin - any thoughts or connections I might be missing?  Maybe something Darrell can provide some insight into?

**Comment by BrianPeterlin** [comment]
so, the only way the student would have access to the eunit is if the teacher at one time had access and got it assigned during that time period

is this a big concern?

it is possible for us to validate access on each eunit before it is displayed to students but it might be some performance overhead


 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
Yes it is a concern. If the teacher no longer pays for access to the eunits, the students should no longer have access to them either. This was always the case in v1.0.

What is "performance overhead"?

**Comment by bguerrettaz** [comment]
I think this is related to the overall authentication things we need to work through.

As part of that, we'll have to create a teacher authentication page and a student one.

Please let me know if you decide to pursue this and I can put a proposal together.

Thanks,
Blake
