### ISSUE TITLE
Question about Sorting of tests on Edit Quiz Page

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#180]
How are the quizzes sorted when you first click on the Edit Quiz page? The box says they are by Quiz Name, but it does not appear the quizzes are listed in alphabetical order. The first two quizzes listed under my IL Ag profile show copies of the my IL Hort test. If you go farther down the page, you will see three other instances of this test. Why aren't they all listed together?

Also, if you go down the page, you will see several instances of the ABC quiz. That quiz should be listed before the IL Hort test.

We need to figure out how they are sorted when you first click the Edit Quizzes page and then have it default to sort by quiz name since that is what appears in the pull down box.

**Comment by bguerrettaz** [comment]
I have fixed this.  It was defaulted to Quiz Name, but was sorting a different way.

I've left it sorting by Quiz Name and corrected the sorting on page load.

Please test and confirm.
