### ISSUE TITLE
State Admins Having Trouble Adding New Teachers

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#181]
Recently, state admins have reported a problem when adding new teachers. They get the following error message:

ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/StateAdmins/Teacher/AppendTeacher.asp, line 72

I was able to replicate it once. It did not happen when I used the universal logins (daniel/cathy) on the admin site when I chose Delaware from the pull down, but I did get it when I used the Delaware logins (stateadmin/delaware). New Jersey also reported this problem recently.

We're wondering if it might be a server issue? Mindy could not replicate it, but I could.

**Comment by bguerrettaz** [comment]
Hmm, I just tried to recreate it with all admin accounts for DE and didn't get it.

I also looked at the code behind it and nothing seemed incorrect.

This is something we'll want to monitor and try to keep recreating as I wasn't able to yet.

Blake

**Comment by dpentony** [comment]
What does the error message indicate?

**Comment by bguerrettaz** [comment]
It means that it was looking for a record to push to the web page, but it
was missing/deleted or in most cases, never there.

Usually very easy to recreate, really weird that its sporadic.
