### ISSUE TITLE
Logins not Being Saved

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#182]
We've received a couple of reports where subscribers are checking the box to save their logins, but when they log out and then login, the logins are not saved. They get the message below. This is happening with both Chrome and Firefox. Any ideas?

![image](https://cloud.githubusercontent.com/assets/5790325/11481810/18f7e74c-9765-11e5-99d5-0776ef132f3b.png)

**Comment by bguerrettaz** [comment]
Have you been able to recreate this?  I tried with Chrome and it worked for me.

**Comment by dpentony** [comment]
Both people who reported it are no longer having issues, so I'm closing this.
