### ISSUE TITLE
URGENT - Changing # of Submission Creates New Instance of Test

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#184]
Eddie Hendrix teaches in Arkansas. He determined that when he changes the number of submissions on the quiz parameters page, it is creating a whole new instance of the test. This should not be the case. A new instance of the quiz should only be created when you assign the quiz to an additional course. When the # of submissions is changed, it is treating the test like it was assigned to an additional course.

I recreated the issue under his account by creating a test called CAERT Test 12.15.15. I created the original version at set the Submission parameter to 1. I then edited the quiz and changed the parameter to 5. Once I did that, it created a second instance of the test. See below. A second instance should not have been created since the course the test was assigned to did not change.

![image](https://cloud.githubusercontent.com/assets/5790325/11824873/b567fe4a-a341-11e5-80d1-a3a4abbab7ef.png)

When you change the submissions and go to save it, you get the pop-up that the course has been changed when it has not. You also end up with a second instance of the quiz.

The teacher ended up with multiple instances of a quiz. When he deleted an instance, he deleted the wrong one and lost his test results.

Note: This is something specific to Arkansas. I could not replicate it under my IL account, but I could when I logged in as him and created the dummy test called CAERT Test 12.15.15. Please edit the submissions on this test under his account to replicate issue.

**Comment by dpentony** [comment]
Also, can you restore the exam he inadvertently deleted? It is called PS unit 3 exam.

**Comment by bguerrettaz** [comment]
I found the issue and have corrected the issue, please test and confirm.

Blake

**Comment by bguerrettaz** [comment]
![image](https://cloud.githubusercontent.com/assets/5695475/11830412/723a1756-a36a-11e5-98cf-3448fd149a19.png)

There are actually a few tests already there in the database, so I'm not sure if this is still an issue or not.

**Comment by dpentony** [comment]
This is only partially corrected. 

1. When you go to change the submissions, another instance of the test is not corrected and that is as it should be. However, the course it has been assigned to defaults to None. I originally had assigned the quiz to the Survey of Ag Course. When I changed the submissions parameter, it changed the course to None even though all we did is change the submissions.

2. I also cannot delete the multiple instances of the test I created today called CAERT Test 12.16.15. When I go to delete quiz and click on those quiz instances nothing happens.

**Comment by dpentony** [comment]
The teacher believes he deleted another instance of the PS unit 3 exam that has test results on it. Can you locate and retrieve other instances of the exam that have been deleted?

**Comment by dpentony** [comment]
Earlier I said: "When you go to change the submissions, another instance of the test is not created and that is as it should be. However, the course it has been assigned to defaults to None. I originally had assigned the quiz to the Survey of Ag Course. When I changed the submissions parameter, it changed the course to None even though all we did is change the submissions".

This happens only the second time you change the submissions parameter. If you created a test and assign it to a course then edit the number of submissions, the course it is assigned to sticks. However, if you then go in a second time and edit the submissions a second time, it is then that the course it is assigned to does not stick. If you don't notice this at the time, a second instance of the test is created.

**Comment by bguerrettaz** [comment]
I'm not getting the same issue:

I created the following quiz: BGTest_12.17.15
I then changed the number of submissions --> course stayed the same
I then changed the number of submissions again --> course stayed the same

Can you retest?  If you get the same issue, can you walk me through the
exact steps?

Thanks,
Blake

**Comment by dpentony** [comment]
I still get the same issue. See screenshot below. When you change the submissions parameter, the course it was originally assingned to (Survey of Ag Systems) changes and you end up with two instances of the quiz. The main problem is that when you change the submissions parameter, the course it is assigned to does not stick.

Here is what I did:

1. Created a test called CAERT 12.17.15 – It was assigned ot the Survey of Ag Systems course and submissions was set at 1.
2. I then edited the quiz by changing submissions to 5.
3. I ended up with two instances of the test: A)the first had submissions set at 1 and it was assigned to the Survey of Ag course. B) the second had submission set at 5 and it was assigned None even though I did not change the course it was assigned to. The course it was originally assigned to (Survey of Ag) should not have changed when all I edited was the submissions. Again, the course is not sticking when you change the # of submissions.

![image](https://cloud.githubusercontent.com/assets/5790325/11889754/4562479a-a512-11e5-92d8-444cd144fc0f.png)

**Comment by dpentony** [comment]
@bguerrettaz - I want to make a clarification. A second instance of the test is NOT being created when you change the submissions parameter. The only real issue is that the course the test is assigned does not stick when you change the number of submissions. This happens in both Firefox and Chrome. The course may stick the first time you change the submission parameter, but if you change it more than once, the course the test is assigned to becomes None even though you did not change the course parameter.

I created a test called CAERT DP 12.18.15. Submissions are set to 1 and it is assigned to the Survey of Ag Systems:

![image](https://cloud.githubusercontent.com/assets/5790325/11898614/a5911366-a55e-11e5-8ee9-b19e4e484152.png)


I then went in and changed only the submissions parameter to 5. See screenshot below. The Survey of Ag course is no longer highlighted in the list of courses.

![image](https://cloud.githubusercontent.com/assets/5790325/11898666/2b2909f2-a55f-11e5-93ee-06a66e3546da.png)

But, if you go under Edit Quizzes, it still shows that it is assigned to the Survey of Ag course:

![image](https://cloud.githubusercontent.com/assets/5790325/11898681/5e647162-a55f-11e5-9db0-a72176033a62.png)

Now, if you go and change the submissions parameter to 10, the course selected defaults to None even though the only parameter that changed was the submissions:

![image](https://cloud.githubusercontent.com/assets/5790325/11898722/b77901dc-a55f-11e5-8b97-7aff839f896c.png)

And if you go back to the Edit Quiz screen, you will see that the test is assigned to None even though the only parameter that was changed was the number of submissions:

![image](https://cloud.githubusercontent.com/assets/5790325/11898771/f58fd004-a55f-11e5-90c3-3aac282bce27.png)

So, that is what I mean when I say the course is not sticking when the only thing you change is the number of submissions.

**Comment by bguerrettaz** [comment]
Got it, that helps a lot.  Thanks

I'll work on this issue today.

Blake

**Comment by bguerrettaz** [comment]
I've been testing and messing with this issue for a while and can't get it to act the way you've described, please see the below referenced screenshots:

Created quiz, submission at 25:
![image](https://cloud.githubusercontent.com/assets/5695475/11920532/2355896e-a738-11e5-9071-0722b23e0a2f.png)

Changed submissions only to 50:
![image](https://cloud.githubusercontent.com/assets/5695475/11920537/440f086a-a738-11e5-8ac2-7c9024b80093.png)

Changed submissions to 1:
![image](https://cloud.githubusercontent.com/assets/5695475/11920539/5e150980-a738-11e5-8138-bcf8b1026241.png)

As you can see in each screenshot, the selected course is Ag Mechanics throughout the entire change of submission count process.  I couldn't get the course to become 'unstuck' like described.

Were you clicking anywhere around the course or something like that?  I'm just not sure how you were able to get that to occur.  I confirmed in Firefox and Chrome as well.

Please let me know your thoughts or additional things to try.

Blake

**Comment by dpentony** [comment]
You're not logging into Eddie Hendrix's account in Arkansas, are you? The list of courses in your screenshots appear to be from my IL account. My original post said this was something specific to his AR. I said then I could not replicate it in my IL account.

Please log into Eddie's AR account. He has given us permission to create tests under his account to get the problem identified. He's now done for the semester.

You should be able to replicate the issue if you login as Eddie.

**Comment by bguerrettaz** [comment]
Yes, I was in your account.  That's weird because this code isn't state
specific, but if I can recreate in his account, that's a start.

I'll try it again with his account.  Thanks.

**Comment by dpentony** [comment]
Where are you on this?

**Comment by bguerrettaz** [comment]
It took a lot of digging to get to the root of this issue, but I finally found it.  There were spaces attached to the end of the courses when entered originally.  There was code in place already that wasn't accounting for those spaces (trimmed).

I have made the appropriate changes and retested, I (think) I've got it.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. thanks for all of your work on this item.

**Comment by bguerrettaz** [comment]
No problem, glad it's resolved!
