### ISSUE TITLE
Error Message when adding test questions from State Admin

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#185]
The IL Mycaert admin is trying to create a test via the state admin page. When he enters a question (either from a PDF file or by keying it in), he gets the following error message:

Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/admin/csat/IL/StateConnection.asp, line 9

Even though the error message appears, the question is being added to the quiz.

I was able to replicate the issue. I logged in to the IL admin page by choosing IL from the state pull down. UN = daniel and PW = cathy. Then go to Edit quiz. Sort the quizzes by activation date and go to the very list quiz - Food Science & Technology CDE Exam 2011. When you type in your own test question or paste it in from a PDF, you get the error message. But, if you go back to edit the quiz, you will see that the question was added even though you got an error message.

Further, if you try to delete any of the questions in the quiz, you get the error message. Lastly, if you try to edit any of the questions, nothing is on the page that comes up after clicking the green edit link.

**Comment by bguerrettaz** [comment]
This has been fixed.  Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. thanks.

I am going to leave it open until the customer confirms all looks good.
