### ISSUE TITLE
Can't Open PPTs from MYcaert

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#186]
Over the past couple of weeks, we've received reports from about 10 teachers that they cannot open the PPTs on MYcaert. When they click the file, they get the "spinning wheel of death" and nothing ever happens.

We believe that this issue has to do with filters on the school networks. We are unable to replicate the issue. Also, when teachers have tried opening the PPTs from a computer not on the school network, they have been successful.

Any ideas on how we can help them? Some teachers have talked to their school IT staffs and they said it was our problem. I do not agree. I am wondering if you have any ideas on directions we can give them to get around this problem.

**Comment by dpentony** [comment]
Here is the type of info we are receiving from teachers. This one just came in this morning:

As of Tuesday, 1/12, I have been unable to download powerpoint's from the MyCAERT website. I have been able to successfully download PPT's since August, 2015. Is there a problem with the website? I wanted to check before I begin exploring the possibility of something being wrong with our equipment. Thanks! Whitney Phillips

**Comment by bguerrettaz** [comment]
I researched this some this morning and wasn't able to find anything on
it.  I've also tried to recreate in a few different environments/browsers
with no luck.

Brian and I will talk over some ideas and we'll get back to you.

Thanks,
Blake

**Comment by BrianPeterlin** [comment]
There is a difference in the way powerpoints and pdfs are accessed

http://www.mycaert.com/file-manager/download-powerpoint.asp?PPTFilename=P060002.ppt
http://www.mycaert.com/eUnits/060001.pdf

The PowerPoint method is the preferred mechanism because it checks authentication before it delivers  the PowerPoint to the end user.  This could be the source of the problem download-powerpoint.asp has code in it that renders the file a different way.  Eunits are directly accessed.  Is there a different way we can write download-powerpoint.asp or re-write it in ASP.net?

**Comment by bguerrettaz** [comment]
Yes, most likely.  I'll take a look at that tonight.

One thing to note, I have not logged in to MyCaert on this computer yet
today, and I was able to click the .ppt link and download without
authenticating, so I'm not sure its actually checking the session state or
whether a user is logged in or not.

If we do end up rewriting that code, it would be a good idea to process all
downloaded medium the same way (through authentication checking) which
would alleviate someone finding PPT's and eUnits though Google.  Just my
two cents on that.

Thanks,
Blake

**Comment by dpentony** [comment]
I completely agree with Blake in that the PPTs should not be accessed without authentication. We want to be sure with any changes that the PPT files that are assigned to students are not adversely affected. Some teachers do not assign the PPTs (they just show them in class), while others do assign them to students. We need to make sure any changes take both these methods into account.

**Comment by bguerrettaz** [comment]
I'll put some suggestions together after looking over the code, both of
those will add their own level of complexities.

I'll get back soon.

Blake

**Comment by BrianPeterlin** [comment]
Yes, there should be authentication built into it

**Comment by BrianPeterlin** [comment]
or needs to be going forward

**Comment by dpentony** [comment]
Why wasn't it built into it from the start of Mycaert 2.0? Wasn't it built into 1.0?

**Comment by dpentony** [comment]
Just to be clear, Here is what we know about the issue:

1. It just started occurring a couple of weeks ago
2. It does not affect all teachers
3. It does not seem to be browser related
4. We are unable to replicate it
5. If teachers try to open PPTs from outside of school, they are most times successful - indicating it has something to do with the school's network.

**Comment by BrianPeterlin** [comment]
it never was in there

 Brian Peterlin
1-309-310-4551

**Comment by BrianPeterlin** [comment]
blake

rewrite the ppt delivery page in asp.net.  let see if that clears things up

we can add authentication thereafter

 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
Are you sure this rewrite is needed? It is only affecting some customers. I just want to be sure what you propose is necessary to fix the problem based on what we know.

**Comment by dpentony** [comment]
We had a teacher who could not access the PPTs since January 10. After verifying that she could access them from a computer outside of school, she referred the issue to the tech guy at her school. This is what he did to correct the issue: "the .ppt files were getting caught up in an error state in the virus scanner on our firewall. I have whitelisted the site so this wont happen anymore".

I know nothing of virus scanners. Could something have recently been done to scanners schools use that all of a sudden prevent the opening of PPTs?

**Comment by BrianPeterlin** [comment]
I made a change to cloud flare maybe that will help

 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
OK as long as you feel it won't worsen the situation. I am guessing only about 10% of teachers seem to be affected, with most in IL and some in MO and MN.

**Comment by bguerrettaz** [comment]
Should we still talk about writing an authentication process for PPTs and eUnits?

**Comment by BrianPeterlin** [comment]
remember when you were having the problem uploading videos?

thats when i made the change, i have now reverted it in Cloudflare

i don think the timing was a coincidence, but maybe it was


 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
OK. Please let me know when this is done. We'll then monitor to see if things have improved.

**Comment by dpentony** [comment]
We can talk about the authentication, but first I want to see the impact of the change that Brian makes to Cloudfare.

**Comment by BrianPeterlin** [comment]
the change was made to Cloudflare
Friday

 Brian Peterlin
1-309-310-4551

**Comment by dpentony** [comment]
We'll monitor and let you know.

**Comment by dpentony** [comment]
@BrianPeterlin  - I'd like to talk to you about this "whole authentication thing". Could we set up a time to talk on Monday?

**Comment by BrianPeterlin** [comment]
@bguerrettaz dan would like an estimate to implement this for eUnits and PowerPoints

**Comment by dpentony** [comment]
Authentication of Eunits, PPTs, and lesson plans need to be addressed.

**Comment by bguerrettaz** [comment]
No problem, I will work on an estimate.

Here is a breakdown of what that will look like:

- Build authentication page (only need one for Eunits, PPT's and lesson
plans)
- The other part of the estimate is the 'calling entities'.  Each place
there is a link for any of the three, we'll have to change the link to call
the new page.  This includes state specific pages.
- Locking down directories so they aren't accessible from search engines
(Google, Yahoo,etc.)

Brian - if I'm missing anything, let me know.

I'll get numbers soon.

Blake

**Comment by bguerrettaz** [comment]
Here's what it's looking like:

- Build authentication page (only need one for Eunits, PPT's and lesson
plans)
4-6 hours
- The other part of the estimate is the 'calling entities'.  Each place
there is a link for any of the three, we'll have to change the link to call
the new page.  This includes state specific pages.
15-20 hours, depending on how long it takes to change and test each calling
entity
- Locking down directories so they aren't accessible from search engines
(Google, Yahoo,etc.)
3-4 hours

Please let me know how you'd like to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
Can you work on this slowly over the next 4 to 5 months so that the changes do not go into effect until July 1? This is a big change and we want to give people plenty of notice that it will be happening.

Also, could a pop-up be developed when they go to login that would announce this impending change? We would want that pop-up to become visible around April 1.

**Comment by bguerrettaz** [comment]
Yes I can do that and yep, I can develop a popup that goes in April 1st and
goes away at a certain time.

**Comment by dpentony** [comment]
Please SLOWLY proceed.

**Comment by bguerrettaz** [comment]
Will do.

**Comment by dpentony** [comment]
@bguerrettaz  - any progress on the pop-up around April 1? See comments above.

**Comment by bguerrettaz** [comment]
Yes, I have the popup ready to go, what verbiage would you like?

Something like:

Starting July 1st, 2016 we will be changing the authentication process for
eUnits and PPT's.  This change will be seamless to you, but we wanted to
share this information with you.

Just let me know what you'd like it to say.

Thanks,
Blake

**Comment by dpentony** [comment]
@bguerrettaz  - I understand what you mean by the change being "seamless", but is it really? Am I correct in that the authentication change will require students to log into their MYcaert account before they can see an Eunit that there teacher may have posted to their school web site?

Mindy and I will put our heads together. I'd like to come up with wording that gives them a bit more info about what the change means to them, but at the same time does not open a huge can of worms for us.

**Comment by bguerrettaz** [comment]
No you're right, if the students aren't logged in, it will require them to log in.  

Thanks,
Blake

**Comment by dpentony** [comment]
Mindy and I will talk in the morning and come up with some wording for the pop-up.

**Comment by bguerrettaz** [comment]
Sounds good.

**Comment by dpentony** [comment]
Here is the wording we'd like to use. Let me know if you think any changes need to be made:

Effective July 1, we’ll be upgrading our authentication process for Eunits and Powerpoints. This will require your students to first log into MYaert before accessing our materials, whether on our site or a
secured school site.

**Comment by bguerrettaz** [comment]
The popup is now in place.  Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
