### ISSUE TITLE
Update IL State CTE Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#187]
We need to make two changes as follows to all IL CTE subscriptions:

1. We need to give all IL CTE teachers access to the Agricultural Mechanics & Technology library lessons, Eunits & CSAT until 7/1/2017. See screenshot below. If possible, we'd like this change made before Friday (2/5).

2. We need to add one year to the expiration dates on all of the other libraries these teachers currently have access to. Their expiration dates should be changed to 7/1/2017. See screenshot below.

![image](https://cloud.githubusercontent.com/assets/5790325/12719343/150f01ac-c8ba-11e5-9f53-8bad7118fdcc.png)

**Comment by bguerrettaz** [comment]
Just as an FYI, I've started working on the first request.

**Comment by dpentony** [comment]
Where are you on this?

We need to give all IL CTE teachers access to the Agricultural Mechanics & Technology library lessons, Eunits & CSAT until 7/1/2017. See screenshot below. If possible, we'd like this change made before Friday (2/5).

**Comment by bguerrettaz** [comment]
This will be completed in the early afternoon.  These are the types of
changes that take some time, because of all of the underlying issues
between the tables (issues we've had in the past with these changes).  I
have most of the queries written and will conduct table level backups soon.

I will wrap it up as quickly as possible.

**Comment by bguerrettaz** [comment]
This is complete.

As with others in the past, this is a pretty manual process, so please let
me know if you see anything that doesn't look correct.

Blake

**Comment by dpentony** [comment]
Thank you. We'll monitor to insure that all teachers have access to the library.

Please let me know when you have item #2 finished. That is: We need to add one year to the expiration dates on all of the other libraries these teachers currently have access to. Their expiration dates should be changed to 7/1/2017. (See screenshot above from my original post on this topic).

**Comment by bguerrettaz** [comment]
Will do, I'll finish the rest up.

**Comment by bguerrettaz** [comment]
Number 2 is complete.  One thing to note, all libraries those teachers had
access to have deactivate dates of 7/1/2017, but the teacher accounts
themselves have different dates, most are 7/1/2016.

Please let me know if there are any issues.

Thanks,
Blake

**Comment by dpentony** [comment]
That is an issue. We need the master teacher account de-activate date to also be changed from 7/1/2016 to 7/1/2017.  See below:

![image](https://cloud.githubusercontent.com/assets/5790325/12887161/1c70e356-ce38-11e5-8e1e-25c84f5f2357.png)

**Comment by bguerrettaz** [comment]
Ok, no problem.  I'll change those as well.

Blake

**Comment by bguerrettaz** [comment]
This is now complete.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
