### ISSUE TITLE
Create an alert for E-units with expired dates

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#188]
It is becoming more and more of an issue for teachers to have E-units not showing up for their students.   We have nothing set up to alert teachers that an E-unit has a due date that has been assigned and has now expired.  The only way for them to discover that an E-unit has previously been assigned with expired/past due dates is to go into the Maintain assigned E-units tab.  They do not know to do this, **so we need to create an alert.**   

On a weekly basis we have teachers contacting us asking why their students cannot see the E-units.  Every single time it is due to the fact that they have previously assigned it, but never cleared out the expired dates.  

What would be the easiest, fewest number of hours for you to create an alert when an E-unit is being assigned that is already active, but has expired dates?  

Blake - can you login to my teacher account:  
u: MindyAG p; Love2work

I want my students to read three E-units in Hort 101.   When I login as a student, for ex Bob Caert.  I see 2 of the 3 E-units that I want to assign.  So I know I need to give access to the 3rd E-unit. 

So I go to "My Courses"
click "Horticulture 101"
click "Assign e-units"
change e-unit status to "Make E-units Active"
click the little box by "030003"
click "Click to assign selected e-units below to students"
I received thank you note - this gives me the impression, that I was successful - however this is not the case....

I then login as student, Bob Caert, but he still cannot see it. .... This E-unit was previously assigned in January and I never changed the dates.   But no error message or screen pops up showing that this is E-unit is active but has expired dates.

**Comment by bguerrettaz** [comment]
Where and when would you want the alerts to be shown?  When maintaining
eUnits, assigning?

Any alerts for the students or an alert for the teacher upon login?  Just
trying to get an idea of the scope of what we're looking at.

Blake

**Comment by mnichols13** [comment]
I guess in my mind, the alert that the E-unit has expired dates should replace the thank you note.   The students do not need the alert, only the teacher.

**Comment by bguerrettaz** [comment]
Ok, probably just 3 hours or so to build and test.

Blake

**Comment by mnichols13** [comment]
Sounds good Blake, please proceed.  We would like to get this done.

**Comment by mnichols13** [comment]
Blake are you working on this now?  We are unable to change the status of an e-unit.. .getting error messages..

INSERT INTO tblCalendar ( [AssignDate], [DueDate], [AssignmentType], [Filename], [Notes], [QuizClassID], [TeacherID], [AssignBy], [LessonCode], [LessonTitle], [LinkID] )VALUES ('1900-01-01','1900-01-01','eUnit','/eUnits/030024.pdf','',27822,3364,'QuizClass','030024','Understanding Soil Color',169053); INSERT INTO tblCalendar ( [AssignDate], [DueDate], [AssignmentType], [Filename], [Notes], [QuizClassID], [TeacherID], [AssignBy], [LessonCode], [LessonTitle], [LinkID] )VALUES (', 2/7/2014',', 2/10/2014','eUnit','/eUnits/040068.pdf',', ',27822,3364,'QuizClass','040068','The Nature of Soil',169052); 
Microsoft OLE DB Provider for SQL Server error '80040e07' 

The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value. 

/Teachers/students/eunit-update.asp, line 181

**Comment by bguerrettaz** [comment]
I've started this work, but in a copied page (to not affect the site).  I'm
not sure what would've caused this, I'll look into it.

Blake

**Comment by bguerrettaz** [comment]
I have finished putting the logic in place to catch past due date Eunits.
The warning now shows on the same page as the Thank you page, if applicable.

I did put a note in that it could either be past the due date OR a
duplicate, because there was already code in place catching duplicates, and
if we don't warn them, it could be confusing.

Can you please test this and confirm the functionality?  If you'd like the
message to change, that's no problem, just let me know what you'd like it
to read.

I'll continue trying to recreate the error message from the above email.

Thanks,
Blake

**Comment by mnichols13** [comment]
Please go into Rex Hamner's account and try to change the status of any of his E-units.... I tried clearing out the past due dates, here is the latest error msg:

INSERT INTO tblCalendar ( [AssignDate], [DueDate], [AssignmentType], [Filename], [Notes], [QuizClassID], [TeacherID], [AssignBy], [LessonCode], [LessonTitle], [LinkID] )VALUES (', ',', ','eUnit','/eUnits/020103.pdf',', ',26589,11728,'QuizClass','020103','Sharpening Hand Tools',193113);
Microsoft OLE DB Provider for SQL Server error '80040e07'

The conversion of a varchar data type to a smalldatetime data type resulted in an out-of-range value.

/Teachers/students/eunit-update.asp, line 181

**Comment by bguerrettaz** [comment]
I was able to recreate with his account.  I 'think' his is related to
having duplicates (which is a problem in of itself).  For example, Eunit
020022.  That's not correct, is it?

I think those duplicates are corrupting the row id, which is causing that
error.

Blake

**Comment by mnichols13** [comment]
That is very interesting that we have never seen this before... but when I cleared out all the duplicates it now seems to work.

**Comment by bguerrettaz** [comment]
Good deal, I'm not sure why the duplicates were there either, but you're
not able to recreate once they're gone?

**Comment by mnichols13** [comment]
The problem seems to specific to Rex Hamner's account.  It is allowing him to assign a duplicate E-unit. 

I tested the new pop up on my account and it worked great. 
When we test it on Rex's account, the pop up does not appear and it allows the duplicate.   

Question:  Is this only Rex Hamner?  is it the entire state?

**Comment by bguerrettaz** [comment]
I have been trying to recreate Rex assigning a duplicate and haven't been
able to, are you still able to do it?  If so, can you send me the steps
you're taking?

Thanks,
Blake

**Comment by mnichols13** [comment]
I can't either now.  I was able to on Thursday of last week.  I would say don't spend anymore time on it.
