### ISSUE TITLE
MN Strand Issues

### ISSUE THREAD

**Issue by bguerrettaz** [MyCaert/Issues-Enhancements#189]
I've been working on this, this week, and wanted to make sure I opened an issue for tracking and to post the resolution, once I have it.

**Comment by bguerrettaz** [comment]
I think I have found the issue, it had to do with overlapping functions, so I had to rewrite one.

Please test and confirm the fix.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
