### ISSUE TITLE
New Logins on MACs???

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#191]
John Neyhart teaches in NJ. He regularly changes his password under Edit Profile. He does it on an PC. He has noticed when he then goes to login on a MAC, the changed password already appears on the MAC and he does not have to enter it in to login. That should not be the case, should it? If he changes it on the PC, the first time he logs in on a MAC, he should have to enter in the new password to login. It should not be already saved where he logs in.

**Comment by bguerrettaz** [comment]
The browser is actually saving this password.  For example, I use Chrome,
once I save my password on any of my computers that password is saved for
any computer that I use Chrome on.  This is normal and something that sites
can't generally control because that's being put in place by the browser.

Blake

**Comment by dpentony** [comment]
But he said he was using Chrome on the PC and Safari on the MAC.

**Comment by bguerrettaz** [comment]
It might have been saved from another instance.  Safari and Chrome don't
utilize the same password saving methods, so that's not possible.  If the
username/password is being entered automatically, its coming from the
browser, not anything we're controlling on our end.

**Comment by dpentony** [comment]
Clarification: He is using Firefox on the Mac. Does that make a difference?

**Comment by bguerrettaz** [comment]
No, all major browsers do similar things.  Saving username/password and
even credit card information is becoming more and more common with all of
the browsers as it speeds user interaction.  That's really the only
possibility for what this teacher has experienced, there's nothing on our
end that we could be doing or can do about the browser doing this.

Thanks,
Blake
