### ISSUE TITLE
New Accounting Library for CTE

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#192]
We have added a new Accounting Careers (AC) library to those we offer in CTE. We need the following:

1. Give all IL CTE users access to the new library, Eunits, and CSAT until 7/1/2017.

2. I manually gave Mary Waters access to the new library. When you login as her, it appears under the libraries for Technology Education. We need this new library to be listed under those for Business, Marketing, and Computer Education which are at the top of the page.

I believe you control the sub-categories under which the CTE libraries appear. I cannot see the functionality on the admin site for us to control the them when we add a new CTE library.

**Comment by bguerrettaz** [comment]
Wanted to let you know I'm working on this.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
I have completed both 1 and 2.

Please test and confirm.

Thanks,
Blake
