### ISSUE TITLE
Student Can't See All Quizzes Assigned to Course

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#193]
Marty Speth (WI) has a number of quizzes assigned to his PEAS III course. There is one student who can only see one of the quizzes when he logs in while all other students in the course can see multiple quizzes. 

This is what Ryan Severson sees when he goes to his assigned quizzes:

![image](https://cloud.githubusercontent.com/assets/5790325/14983796/f9710d3a-1104-11e6-9c05-ce9662c4c342.png)

Note that there is only one quiz that shows up. Also note the error message that has been highlighted.

When any other student that is assigned to the PEAS course logs in and accesses their assigned quizzes, they see this:

![image](https://cloud.githubusercontent.com/assets/5790325/14983878/681f17ea-1105-11e6-95dd-557ca4d333f7.png)

Why does Ryan only see the one test as being available in the PEAS III course?

**Comment by bguerrettaz** [comment]
I'll take a look and get back to you.

Blake

**Comment by dpentony** [comment]
The student (Ryan Severson) needs to take the Managing Plant Diseases CSAT Quiz but it is not available to him.

**Comment by bguerrettaz** [comment]
I found the issue in the code, fixed and tested the fix.  Please test and
confirm.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by mnichols13** [comment]
We have this same issue with a Missouri student now

**Comment by mnichols13** [comment]
Dean Lackey's account
Colton Bryeans 
![image](https://user-images.githubusercontent.com/5790342/49296990-44608400-f47f-11e8-9749-1ec148519ae9.png)

**Comment by dpentony** [comment]
Any progress with this? We're hoping to provide the teacher with an update on Monday morning.

**Comment by bguerrettaz** [comment]
This issue is resolved.

Please test to confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
Looks good, Thank you!
