### ISSUE TITLE
Update NJ State Ag Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#194]
NJ has extended their ag subscription for anther three years. Could you please update all active NJ teacher accounts for ag so that:

1. Their account de-activate date is changed from 7/1/2016 to 7/1/2019.

2. The de-activate dates for the lessons, Eunits, & CSAT they currently have access to are changed from 7/1/2016 to 7/1/2019.

**Comment by bguerrettaz** [comment]
This is complete, please test and confirm.

Blake

**Comment by dpentony** [comment]
Thanks
