### ISSUE TITLE
Update MO State Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#195]
Missouri has extended their subscription to MYcaert for another year. We need you to make the following changes on a state-wide level prior to July 1:

For any teachers with a master de-activate date of 7/1/165, we need you to change it to 7/1/201676.

For any teachers who have de-activate dates of 7/1/16 to the six Missouri libraries (Agriscience, Horticulture, Animals, Plants & Soils, Ag Mechanics, Agribusiness, and Environmental Resources) we need you to change them to 7/1/20176. This includes lesson plan, Eunit, and CSAT access for the six libraries.

Please let em know if you have questions.

NOTE: You did the same thing last year. See issue #144 in closed issues.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
