### ISSUE TITLE
Update DE State Ag Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#196]
Delaware has extended their subscription for AG teachers for another three years. Please update the DE Ag teacher accounts as follows:

1. Change account de-activate date to 7/1/2019.

2. Change the deactivate dates on all libraries, Eunits, and CSAT that they currently have access to from 7/1/2016 to 7/1/2019.

**Comment by bguerrettaz** [comment]
This is complete.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
@mnichols13  - could you spot check this to make sure all is well. If so, please close the issue. Thanks.
