### ISSUE TITLE
unable to open ppts from ADMIN page - missing file report

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#197]
I am unable to get any ppts to open when in the MISSING FILE report on the Admin page.  I use this quite a bit, today I began getting the following error:

![image](https://cloud.githubusercontent.com/assets/5790342/15899001/f6abdbd0-2d5f-11e6-8494-91504fadfebb.png)

**Comment by BrianPeterlin** [comment]
blake

thoughts?

 Brian Peterlin
1-309-310-4551

**Comment by bguerrettaz** [comment]
This is fixed, while developing the authentication solution, I left the XML
in place hat shouldn't have stayed.  I have corrected this.  Sorry about
that.

Blake

**Comment by mnichols13** [comment]
thanks, looks good
