### ISSUE TITLE
old link to be removed

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#201]
I found this live link today, can you remove?
http://www.mycaert.com/ppt_presentation.asp

**Comment by dpentony** [comment]
This could be from MYcaert v.1.0.

**Comment by bguerrettaz** [comment]
I have created a hidden segment in IIS to have a location for old, or
unneeded files.

The hidden segment (or folder that is blocked from outside access) is
Archive under the MyCaert root.

Any files that are no longer needed can be placed in the Archive folder and
won't be accessible by anyone.

Please test and confirm.

Removed file:  http://www.mycaert.com/ppt_presentation.asp
Archived file: http://www.mycaert.com/Archive/ppt_presentation.asp

**Comment by mnichols13** [comment]
what about this link?  why am I able to pull up

**Comment by mnichols13** [comment]
when i put this into google:  Mycaert e-units, I get the following return on my search:  
![image](https://cloud.githubusercontent.com/assets/5790342/16927332/62ff9cca-4cf2-11e6-821e-f6b2762ebd18.png)

**Comment by mnichols13** [comment]
If I follow this link I am logged into Diane Mahinda's account.   I cannot figure out why this works?  If I cut and paste the link it does not work.   Please take a look when you have a minute and see if you can also make this link work.    I have tried it multiple times and I am able to access her account without logging in.

**Comment by bguerrettaz** [comment]
Hmm, that is weird, I get the same thing.  Can you please change or have
the teacher change their password on that account?

I've searched for other users with Mycaert in Google and can't find any
other occurrence of this issue.  I'm very curious as to why this one is
showing up.

**Comment by mnichols13** [comment]
I changed her username and password but that did nothing, so I made her account inactive.  She is retired anyway.
