### ISSUE TITLE
SC Admin - Error Message When Adding Teachers

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#202]
The SC admins are getting the following error message when they try to add a new teacher via the state admin site:

Microsoft VBScript runtime error '800a005e' 

Invalid use of Null: 'replace' 

/admin/StateAdmins/Teacher/AppendTeacher.asp, line 226

Even though they get the message, the teacher is successfully added. However, the fact the error message is displayed would lead some to believe they were not successful in adding the new teacher.

**Comment by bguerrettaz** [comment]
This has been resolved.  Please test and confirm.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
