### ISSUE TITLE
Duplicates on MYcaert Support Questions

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#203]
Ever since you set Kathy Novotney up to receive the MYcaert Support queries we are all getting duplicates of each message. Can you look into why we are all getting duplicates?

**Comment by dpentony** [comment]
We're still getting duplicates on all messages sent when a user clicks on the Questions tab on the MYcaert home page.

**Comment by bguerrettaz** [comment]
It's probably because its going to individual email addresses as well as
the support mailbox, and everyone is on that as well.

Can I just send it to support, and that way everyone will receive it?

**Comment by dpentony** [comment]
That is fine as longs as we insure knovontey@caert.net, dpentony@caert.net and mnichols@caert.net all receive the support messages.

**Comment by dpentony** [comment]
@bguerrettaz - Kathy Novotney is not receiveing the Free 30-day Trial requests. She is receiving the support messages.

**Comment by bguerrettaz** [comment]
I have fixed the duplicate email issue and Kathy should now be receiving
30-day trial requests.

Thanks,
Blake
