### ISSUE TITLE
Changes to support podcasts and other media

### ISSUE THREAD

**Issue by bguerrettaz** [MyCaert/Issues-Enhancements#204]
Opening this issue to track this request, if you decide to move forward.  I've attached the estimate that we talked through.

[MyCaert_HighLevelEst_PodcastsOther_Comments_051116.docx](https://github.com/MyCaert/Issues-Enhancements/files/400300/MyCaert_HighLevelEst_PodcastsOther_Comments_051116.docx)

**Comment by bguerrettaz** [comment]
Just wanted to see if you had any updates on this potential enhancement?

**Comment by dpentony** [comment]
It is looking doubtful at this time due to budget constraints. I am going to close this issue for now.
