### ISSUE TITLE
Wiping Out Eunits Assigned to Individual Students

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#205]
Micah Bristow is a teacher in Missouri. He has LOTS of Eunits assigned to individual students. Go to Maintain Assigned Eunits and then click on Eunits. Then click on the tab for Eunits Assigned to Individual Students. Using the pull down menu, choose All Students. When you do so you get this error message:

Response object error 'ASP 0251 : 80004005'

Response Buffer Limit Exceeded

/Teachers/students/select-all.asp, line 0

Execution of the ASP page caused the Response Buffer to exceed its configured limit.

The teacher wants to wipe out the all Eunits assigned to all individual students. I assumed choosing All Students would allow us to do that. Can you take a look? I am guessing the problem has to do with him having assigned so many eunits to so many individual students.

**Comment by dpentony** [comment]
Have you had a chance to look into this? The teacher just contacted me asking for an update.

**Comment by bguerrettaz** [comment]
Yes, I was holding off on putting in the fix until I tested it some more.

This teacher does have a very, very large number of eUnits, so I wanted to
make sure that the fix I put in place would support that number.

I have made the fix, please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
I just tried to delete all of the Eunits assigned to individual students under Micah Bristow's account. I selected all students under the Eunits Assigned to Select Students and then selected all Eunits to be deleted. When I hit submit, nothing seems to happen.

**Comment by bguerrettaz** [comment]
Because of the very large number of eUnits, it will take a long time to
delete that (if at all).

I see two options:

- I can look at why its hanging
- Or since most seem to not have this many, I can manually delete from the
database

Let me know how you'd like me to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
Please manually delete them.

**Comment by bguerrettaz** [comment]
In investigating this more I ran some queries before I deleted all of his
eUnits assigned to students.

There are two tables that will need the deletes:

- One is the table that has the eUnit assignment
- One is the calendar table for assigning

For the assignment table, there are 41,652 that are under that teacher,
assigned to students
For the calendar table, there are 31,415 that are/were assigned under that
teacher, to students

Before I run the delete queries, I just wanted to confirm with you these
deletions.

I will back up both tables before I issues the deletes, so we have a point
in time to go back to, if needed.

Thanks and please confirm the request.

Blake

**Comment by dpentony** [comment]
I've contacted the teacher to tell him what we plan to do.. If we do not hear from him, we'll move forward.

I'll be in touch later today.

**Comment by dpentony** [comment]
The teacher just told me he did it himself in several batches. Go figure.
