### ISSUE TITLE
Bulk Add New Students for McKown at Edwardsville, IL

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#206]
In the past, you have bulk uploaded students for Edwardsville HS in IL. Attached are two files - one for 7th grade and one for 8th. Could you upload these students under Mark Mckown's profile at Edwardsville? 

[Class List - Lincoln Grade 7.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/418478/Class.List.-.Lincoln.Grade.7.xlsx)
[Class List - Lincoln Grade 8.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/418479/Class.List.-.Lincoln.Grade.8.xlsx)

**Comment by knovotney** [comment]
Blake- I just wanted to see what the status of this issue is?

**Comment by bguerrettaz** [comment]
I'll complete this request tonight.  These requests take some time to get
into the right format to insert into the system.

Blake

**Comment by bguerrettaz** [comment]
Both 206 and 207 are now complete.

The usernames are first name + last name + teachers initials (MM, JO)

Their passwords are their student IDs.

Thanks,
Blake

**Comment by knovotney** [comment]
Thanks, Blake! Looks great.

**Comment by knovotney** [comment]
We again need to bulk add students for Mark McKown. Please see the attached document.
[AG Class List Lincoln.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/1163469/AG.Class.List.Lincoln.xlsx)

**Comment by bguerrettaz** [comment]
Just FYI, I'm working on the bulk upload.

Blake

**Comment by knovotney** [comment]
Thank you. I look forward to the final update. 


-------- Original Message --------
Subject: Re: [MyCaert/Issues-Enhancements] Bulk Add New Students for
McKown at Edwardsville, IL (#206)

**Comment by bguerrettaz** [comment]
This is completed.  Please spot check to confirm.

I will begin working on the other bulk add request.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Any issues with this or can we close?

**Comment by knovotney** [comment]
Thanks for your work on both issues.
