### ISSUE TITLE
Bulk add students for Jeni O'connor at Edwardsville, IL

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#207]
Can you bulk add the students  on the attached for Jeni O'Connor at Edwardsville, IL?

[Class List - Liberty Grade 7and8.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/418486/Class.List.-.Liberty.Grade.7and8.xlsx)

**Comment by knovotney** [comment]
Thanks, Blake.

**Comment by knovotney** [comment]
We again need to add the students in the attached document to Jeni O'Connor at Edwardsville. 

[Copy of AG Class List Liberty 2017-2018.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/1163473/Copy.of.AG.Class.List.Liberty.2017-2018.xlsx)

**Comment by bguerrettaz** [comment]
This is complete, please spot check to confirm.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Any issues with this or can we close?

**Comment by knovotney** [comment]
I was helping teacher to clean up duplicate students. It is fine to close now.

**Comment by bguerrettaz** [comment]
No problem just cleaning up some items!

**Comment by dpentony** [comment]
@bguerrettaz - we've been asked to do the bulk upload of students again this year. Just giving you a heads up. I will email the file to you.

**Comment by dpentony** [comment]
You should now have two files - one for Liberty and one for Lincoln Middle Schools.

**Comment by bguerrettaz** [comment]
All of these requests are now completed.

Please have all three teachers confirm they see their students.  I did not
do a mass delete as there were no issues with bulk uploading her students.

Thanks,
Blake

**Comment by dpentony** [comment]
Thank you. I will let them know.

**Comment by mnichols13** [comment]
Blake,
Again this year, Edwardsville IL teachers are requesting a bulk upload of students.  I will attach the files.  Are you able to finish this by  Monday? 
[2019AG Class List Alpha Lincoln.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/3478995/2019AG.Class.List.Alpha.Lincoln.xlsx)
[2019AG Class List Alpha Liberty.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/3478996/2019AG.Class.List.Alpha.Liberty.xlsx)

**Comment by mnichols13** [comment]
The teachers at Liberty Middle School are Keith Morgan and Jeni O'Connor
The teacher at Lincoln Middle School is Elizabeth Fanning

Let me know if you have questions

**Comment by mnichols13** [comment]
Blake, I just wanted to make sure you saw this, are you able to work on over the weekend?

**Comment by bguerrettaz** [comment]
Hi - yes I should be able to work on this over the weekend.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Hi - this is complete.
