### ISSUE TITLE
Update Current School Year Report for Tests

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#208]
Micah Bristow in MO called with another issue. When he clicks on Current School Year Reports, he gets a long list of quizzes from previous years. See below. The page is showing lots of quizzes - many of them with no results. Shouldn't this page show the results only for the quizzes given this school year (7.1.16 to 6.30.17)?

![image](https://cloud.githubusercontent.com/assets/5790325/17706745/d525e98c-63a2-11e6-955e-5c8be9841825.png)

**Comment by bguerrettaz** [comment]
I agree it probably should only load those quizzes from the current school
year since that's the title of the link, but at this time, its loading all
of the quizzes for that teacher.

If the teacher clicks on 'Click to Show Quizzes from current year', then it
is only those in the current year.

This is a state specific page, is this issue with all states as well?

Please let me know how you'd like me to proceed.

Thanks,
Blake

**Comment by dpentony** [comment]
We'll hold off on doing anything for now unless we begin to get other reports.

**Comment by dpentony** [comment]
If you click on the "Click to Show Quizzes from current year" link, it does reduce the number of tests that are displayed, but it is showing results based on the calendar year. It should be showing quizzes as of 7/1/2016 which is the new school year.

**Comment by mnichols13** [comment]
This issue has come again with Jay Williams, an AG teacher in IL at Stillman Valley.   He was looking for quiz results from his quiz:  Sustainable Agriculture_3B in course:  BSAA_Plant_16/17_3B.   The other two quizzes from this course show, but this one does not.  
Please advise on when you can work on this issue, it has been outstanding for quite some time.

**Comment by bguerrettaz** [comment]
I'm looking into this again.  I have found one issue, the dates were
01/01/year rather than the actual school year.  That has been fixed.  I'm
trying to track down why that quiz for Jay Williams doesn't show.  More to
come.

Blake

**Comment by bguerrettaz** [comment]
Just an FYI, I looked into this again, I can't trace why that one quiz
isn't showing for Jay Williams.  Are there any other cases like that one?

**Comment by dpentony** [comment]
@knovotney - didn't Jay have a second occurrence of this? If so, please let Blake know the name of that second quiz.

**Comment by knovotney** [comment]
Yes. The quiz name is Sustainable Agriculture_2016_1A.

**Comment by bguerrettaz** [comment]
I think I have finally found the issue as to why some quizzes are dropping
off.  In the code, there are certain date formats that were coming through
incorrectly, and they weren't passing the 'current school year' date test.

I have reconfigured the date formats and the quizzes are now showing
correctly.

Please test and confirm.

Thanks,
Blake

**Comment by knovotney** [comment]
@bguerrettaz I went into Jay's account and was able to locate this year's quizzes he mentioned, using the "Current School Year Report". Thank you for your prompt work.

Kathy
