### ISSUE TITLE
Teachers Getting Kicked Out

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#209]
We're seeing an issue where teachers are getting kicked out and having to login over and over. Here is an example. Login to my IL Ag account. Under the MY Students tab, click on Login as a student. Choose any student. You should be able to login fine. Close that student's page and then try to login as another student. It will kick you back to the home page where the teacher has to login again.

It seems to have to do with when the teacher goes from the teacher page to the student page.

Could this be related to the authentication changes?

**Comment by bguerrettaz** [comment]
This is now resolved.  The new authentication changes clashed with the
student login functionality because the same session variable are used for
teachers as students (that shouldn't be the case).  So I created two new
session variables and that resolved the issue.  I tested out the scenarios
again.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by mnichols13** [comment]
Blake, reverting the changes now allows students to login, so we need to fix the original issue, therefor I have reopened.

**Comment by bguerrettaz** [comment]
Thanks.  I'll research why that login method caused the issue and get back
to you.

Blake

**Comment by bguerrettaz** [comment]
Ok, I think I found the issue.  I've tested the scenario's we saw today
once again and retested the auth changes for students.

The issue stems from there being two login code bases (one for teacher and
one for student) and all changes have to be placed in both pages.

Please test and confirm.  If you run into another issue, let me know and
I'll revert.  I 'think' I've tested each scenario.

Blake

**Comment by dpentony** [comment]
Looks good. Thanks, Blake.

@knovotney - please let Jeni O'Connor know that we've resolved the issue of her getting kicked out
