### ISSUE TITLE
Students unable to submit quiz - Rodney Main

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#211]
Rodney Main, teacher in IL assigned a quiz to his students today and none of them were able to submit it.   We checked all three servers and they were all up and running.  The quiz is 8.24 Shop Safety 1.  Could you look tonight and see if you see any data that would indicate that students took this quiz?  He sent me this screen shot. 

![rodney_main](https://cloud.githubusercontent.com/assets/5790342/17947936/65252a4e-6a14-11e6-8f05-845374796530.JPG)

**Comment by bguerrettaz** [comment]
I was able to view the quiz through the teacher and the student view.

@bpeterlin - Could this possibly be something on the school's end?  Another
test would be for the teacher to try to see it from home rather than at
school, to narrow it down further.

Blake

**Comment by bguerrettaz** [comment]
Brian - have you had a chance to look at this?

**Comment by bguerrettaz** [comment]
Did it work from home?

**Comment by BrianPeterlin** [comment]
Disk space on the db was low, i wonder if certain transaction on the db were failing because of it

The space is freed up now

**Comment by mnichols13** [comment]
I will touch base with the teacher and let him know we believe it was an isolated incident and to let us know if it happens again.  Sounds like not an easy one to diagnose after the fact.

**Comment by mnichols13** [comment]
Closed for now until we hear that the teacher has another issue.  Nothing was really resolved on this for sure.
