### ISSUE TITLE
Teacher cannot open lesson plan

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#212]
We seem to have an isolated issue that we cannot replicate, but we need some help identifying the issue.  She cannot open a lesson plan.   Dan and I can both open them and we are not hearing from other teachers.  Seems to be specific to her computer - happens at school and home...  Can you help?

You have revieved a new Contact Request.
Name: Amy Gibbs
Email: agibbs@bentonhighschool.org
State: IL
School: Benton High School
Profile: CTE
Question:
When I click on a lesson title I am receiving an error message: SessTeacherLogin = SessState = IL SessProfile = Teacher SessStudentID = SessTeacherID = 8895 SessSchoolID = 2513 SessUsername = agibbs SessPassword = agibbs SessFocus = CTE StudentQuizClassArray = SessLessonPlanArray = 4, 26, 27, 28, 29, 30, 31, 34, 35, 37, 41, 51, 54, 56, 57, 58, 68, 69, 81, 82, 83, 88 SessEUnitArray = 4, 26, 27, 28, 29, 30, 31, 34, 35, 37, 41, 51, 54, 56, 57, 58, 68, 69, 81, 82, 83, 88 SessMessageArray = 0, 34, 21, 15, 2 SessCSATArray = 4, 26, 27, 28, 29, 30, 31, 34, 35, 37, 41, 51, 54, 56, 57, 58, 68, 69, 81, 82, 83, 88 SessLoginState = LoggedIn SessLessonPlanAccess = Yes SesseUnitAccess = Yes SessCSATAccess = Yes NewQuizTeacherID = 8895 Microsoft VBScript runtime error '800a000d' Type mismatch /authenticationCheck.asp, line 9

**Comment by bguerrettaz** [comment]
She should clear is cache to see if that helps, here is an article that
covers the major browsers:

http://www.techradar.com/us/how-to/computing/how-to-clear-cache-1298796

My guess is she has something from history that she can't shed.  She could
also try a different browser to test too.

Thanks,
Blake

**Comment by mnichols13** [comment]
We discovered the issue is when a teacher searches by vocab term.  Once the search is complete and you try and open the lesson plan from this particular page  this error message appears.   I was able to replicate the problem.

**Comment by mnichols13** [comment]
Blake,
can you look at this over the weekend?

**Comment by bguerrettaz** [comment]
Yes

**Comment by bguerrettaz** [comment]
I was able to replicate the issue and find the problem.  I've put in a fix
and tested this scenario.

Please test and confirm.

Blake

**Comment by mnichols13** [comment]
looks good - Thanks Blake!
