### ISSUE TITLE
Mycaert/Admin MyCommunity -search by date function

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#213]
We have discovered that the searching by date function for My Community posts does not seem to work.   We would like to be able to look at how many new posts for a given month, but cannot get it to work.

Could you give us an estimate on fixing this?

**Comment by bguerrettaz** [comment]
Is this on the admin side only?  I don't see a date search function on the
user side.

Blake

**Comment by mnichols13** [comment]
yes - admin only

**Comment by bguerrettaz** [comment]
I'll get it done in 2-3 hours, let me know if you'd like to proceed.

Blake

**Comment by dpentony** [comment]
Please proceed.

**Comment by bguerrettaz** [comment]
The date function in the MyCommunity search is now fixed.

Please test and confirm.  I enhanced the two date fields with a dropdown
calendar, so all you have to do is click the field and a calendar appears.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good, thanks!
