### ISSUE TITLE
Teacher cannot use her Course Outlines after moved from another account - CROOK

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#214]
Glenda Crook in WI moved schools.  She asked us to move her course outlines and so I did this through the admin page.   They were moved from Lodi HS to Columbus HS.  The course outlines now appear under the blue MY COURSES tab, however she cannot assign students to the courses.  They do not show up under Manage Course rosters so they are useless to her. 

Please fix ASAP.

**Comment by mnichols13** [comment]
The courses she cannot use are: Horticulture I, Horticulture II, Wisconsin Forestry and Wildlife, Wisconsin Fish and Aquaculture, Agribusiness Management, Ag Processing, Ag Careers and Leadership, Biotechnology, Landscaping, Small Animal Science, Large Animal Science and Veterinary Studies.

**Comment by bguerrettaz** [comment]
When you say cannot use, what do you mean exactly?  What are the issues or
things in the way of these being used?

**Comment by mnichols13** [comment]
She cannot assign any students to the course, therefore cannot assign E-units or PPts

**Comment by bguerrettaz** [comment]
I have manually inserted those records into the correct database table,
therefore fixing this issue.  Please test and confirm it's fixed from her
perspective.

Also - can you please try to do exactly what you did to cause this issue in
a test account (yours or Dan's)?  I want to see what root issue is and make
sure I get it fixed so this doesn't happen again.

Thanks,
Blake

**Comment by mnichols13** [comment]
Glenda's account looks good.  I replicated the issue by importing four course outlines from Dan's account to my MindyCTE account:
Computer concepts and computer applications
Culinary Arts
drafting
Green Construction

Again, none of these show in my Manage course rosters drop down menu.

**Comment by bguerrettaz** [comment]
I have found the issue.  The code was missing some code to insert into both
tables that needed to be adjusted.

I have written the code, and tested the scenarios.

Please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
I transferred two course outlines this morning into my account from Ron Biondo.  One shows a date and time stamp, the other does not.   I believe in the past it always did show the date and time stamp.  Why would one show it, but not the other?

**Comment by bguerrettaz** [comment]
I imagine if there is another named the same, it appends the timestamp, if
not, if doesn't.  Does the case match that profile?

**Comment by mnichols13** [comment]
no.. I didn't have a course that matched either one.

**Comment by bguerrettaz** [comment]
This issue is now resolved, when copying a course outline, it will always
have a date and time stamp.

Please test and confirm.

Blake

**Comment by mnichols13** [comment]
looks good
