### ISSUE TITLE
MN State Admin Unable to Create State Course Outline

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#218]
We are trying to create some state course outlines via the MN state admin page. After selecting the libraries and lessons we want in the outline, we get the following error message. Please advise.

![image](https://cloud.githubusercontent.com/assets/5790325/19274604/3a6ab376-8f96-11e6-9143-3a3ae82c7c20.png)

**Comment by bguerrettaz** [comment]
This issue is occurring because this page doesn't exist for MN.  It does for other states, but not for this one.

I'll need to take an existing page and redo it for MN.  I've looked back in history and haven't been able to ever see a page for MN in this location.

Please advise how you'd like to proceed.

Blake

**Comment by dpentony** [comment]
I was afraid of that. What is your estimate to add the functionality to the MN admin page? I'm not sure why it was never there.

**Comment by bguerrettaz** [comment]
I looked over a page that is there and all of the queries are state specific, so I'd need to rewrite those as well as test to make sure they work.

Probably around 4-5 hours of work/testing.

Blake

**Comment by dpentony** [comment]
Please proceed.

**Comment by bguerrettaz** [comment]
Ok, I have written a new page for MN.  There was a lot of changes that had
to take place from the page I used to create this page.

Please test this out and let me know any issues you encounter, I expect you
may find something, just because there is a lot going on in these pages.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks, Blake.

@knovotney - could you try to create a state course outline when you have a chance?

**Comment by knovotney** [comment]
@bguerrettaz @dpentony 
I was able to create the Animal Science course outline with no problems. I will explore creating the others this afternoon.  Thanks for your work, Blake.

**Comment by bguerrettaz** [comment]
Sounds good, thanks
