### ISSUE TITLE
Students getting an error message - cannot submit quiz

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#220]
Teacher Marty Speth in WI has a few students unable to submit a quiz:

Course:  Peas III
Quiz name:   Moisture Holding Capacity CSAT

Student #1: Hector Zamora - quiz won't move past page 8
Student # 2:  Valentino Villarreal - quiz won't move past page 1

I logged in as Marty Speth (the student) and had no issue taking the quiz, but when i logged in as these two students it gets stuck..  Getting an error message:  Invalid answer string.  It will not allow me to move past the question or submit the quiz. 

Also it shows a different number of pages, such as when logged in as Marty it showed a total of 15 pages, one question per page, the other students it showed 20 pages... of course I couldn't get to all of them.
Here is the error message:

![image](https://cloud.githubusercontent.com/assets/5790342/19489059/2bc5c5b0-952f-11e6-9a6b-e6e437d11d4d.png)

**Comment by dpentony** [comment]
Any progress? We are at national FFA Convention and will be seeing the teacher.

**Comment by bguerrettaz** [comment]
I'm traveling this week, but can look at it tonight.

Blake

**Comment by bguerrettaz** [comment]
I have tried both students and was able to get all the way through the
quiz.  For each student, I selected any answer, and clicked next page and
save quiz.  I didn't submit.

Can you please walk me through exactly how you get this to occur?

I'm also looking into the code to see how this error message is built.

Blake

**Comment by mnichols13** [comment]
Blake,
We talked to Marty at FFA Convention.  He was trying to delete duplicate questions while the students were taking the quiz.   We concluded that this must have been the problem.   We will close this for now and if it happens to come up again, we'll re-open it.
