### ISSUE TITLE
Delete Notice Regarding July 1 Security Upgrade

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#222]
@bguerrettaz - I think it is time that we eliminate the notice regarding the July 1 Security Upgrade. Please make it disappear so that users no longer see it.

![image](https://cloud.githubusercontent.com/assets/5790325/19698013/432d3d26-9ab3-11e6-8341-c56ed7123734.png)

**Comment by bguerrettaz** [comment]
This is complete.

Blake

**Comment by dpentony** [comment]
Thanks.
