### ISSUE TITLE
Expand the window for choosing a list to email

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#223]
Can you make this window larger on this screen so that I can see the entire data set?  This is on the ADMIN page - Email console- Create email

![image](https://cloud.githubusercontent.com/assets/5790342/20313841/c7b3d3a0-ab1d-11e6-9ab2-e9bde41159ca.png)

**Comment by bguerrettaz** [comment]
This is complete.

Blake

**Comment by mnichols13** [comment]
looks great, thanks.
