### ISSUE TITLE
Not All Questions Displaying on a Test

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#225]
Matt Lee is a teacher in WI. He has a test called Genetics and Reproduction Quiz. The quiz has 41 questions. All of his students but one can see the 41 questions. One student (Dalten Arthur) can only see four questions when he opens the quiz. Please look into this and advixe.

**Comment by bguerrettaz** [comment]
I logged in as Dalten Arthur and was able to see all of the questions to
this quiz.  Were you able to recreate this?

Did something change after you submitted this ticket?

**Comment by dpentony** [comment]
Yes, I was able to replicate it. Yesterday, only four questions were showing. Today, all of them are there. Thanks for looking into it. I will close it for now.
