### ISSUE TITLE
Print function on course outline reorder custom lessons

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#226]
How much work would it be to add a print button to the page "Reorder lessons in custom outline page"  This is the most concise listing of a course outline - lesson titles only.  It would be really nice to be able to print this, or at least have the ability to copy it over to Excel to print.

**Comment by bguerrettaz** [comment]
It would roughly be 4-6 hours. I would build the ability to print or export
to Excel.

Please let me know if you'd like to proceed.

Blake

**Comment by dpentony** [comment]
@bguerrettaz  - can you modify the print course outline to remove everything but the lesson plan titles?

**Comment by bguerrettaz** [comment]
Yes, this can be done.  Do you want me to go ahead and make those changes?

**Comment by dpentony** [comment]
What is your time estimate?

**Comment by bguerrettaz** [comment]
An hour or two.

**Comment by dpentony** [comment]
Please proceed. Remember, we want the print capability on the re-order lessons page. There should be no change on the exported course outlines to Word or Excel.

**Comment by bguerrettaz** [comment]
Sorry, might have misunderstood.  I thought you just wanted all information
removed, ecept for the lesson titles from the 'Print Course Outline'
button.  Do you also want the print capability on the 'Reorder Lessons in
Course Outline' button?

Those are two different code files.

Just want to clarify.

Blake

**Comment by mnichols13** [comment]
![image](https://cloud.githubusercontent.com/assets/5790342/21320524/fba56d1c-c5d6-11e6-9caa-e3950619808d.png)

**Comment by bguerrettaz** [comment]
Yes, I have that, but what was confusing was Dan's comment above:  Remember,
we want the print capability on the re-order lessons page.

**Comment by mnichols13** [comment]
so the change would not in any way affect the export course outline to word or excel.    The change should only affect the way this page prints.
![image](https://cloud.githubusercontent.com/assets/5790342/21320608/4da8d00e-c5d7-11e6-9e00-7f697e8f3202.png)

**Comment by mnichols13** [comment]
I am happy to talk through this if you would prefer to call x 133

**Comment by bguerrettaz** [comment]
Got it, thanks.  I will only be making the change to this screen:

[image: Inline image 1]

1-2 hours.

I will not be changing the reorder page.

Blake

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Blake

**Comment by mnichols13** [comment]
thanks.
