### ISSUE TITLE
Web & App Development LIbrary

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#227]
We have a new library we need to make available to all IL CTE users. It is called Web & App Development. Please make the lessons, Eunits and CSAT Questions available to all IL CTE Subscribers from today through 7/1/2017.

**Comment by dpentony** [comment]
Also, we need this library to be listed under the Business, Marketing and Computer Education area on the teacher homepage . It is currently listed under the Technology and Engineering Education area on the teacher homepage.

**Comment by bguerrettaz** [comment]
I have moved this library under: Business, Marketing and Computer Education.

Please confirm it looks correct.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
I will continue to work on the rest of this request.

**Comment by dpentony** [comment]
Moving the library under Business looks good. Please proceed with the rest of the task.

**Comment by bguerrettaz** [comment]
I have completed the addition of this library to all IL CTE teachers.

Please test a few teacher accounts and let me know of any issues.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
