### ISSUE TITLE
Adding Blog to MYcaert site

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#228]
Please move ahead on this item per Brian's Google doc: dd tab on MYcaert.com Homepage- "Blog"- 
- Move the blog to the main website (instead of host it on Weebly) as a separate tab so that MyCaert can get credit for the unique, fresh content
- Once the blog is moved over "tell" Google to crawl that section
- This is a great place to show Google that you are updating your website and that you care about showing your users new, useful and fresh content (which Google loves!)
-Blog is found at: www.mycaert.weebly.com 

Embed existing weebly blog in MyCaert (if possible, haven’t researched) – 4-5 hours

**Comment by bguerrettaz** [comment]
Just emailed about this one to you and Brian.  I will continue work on this.

Blake

**Comment by bguerrettaz** [comment]
Since you're not getting the emails from GitHub, I'll email this update
here and post to GitHub.

I have a working demo up for the blog:

http://mycaert.com/weebly.asp

Please take a look and let me know your thoughts and anything you see that
you would like changed.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Any work remaining here?

**Comment by bguerrettaz** [comment]
Is this ready to be closed?
