### ISSUE TITLE
Changes to 30-Day Trial Request Form

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#229]
Please move ahead on this item per Brian's Google doc:

30-Day Trial Request Form:
-make last line a required field; make separate fields for first and last name and make them required
-add required field for phone number.
- add a check box for: "Yes, I would like to schedule a person tutorial".

**Comment by knovotney** [comment]
@knovotney test

**Comment by bguerrettaz** [comment]
This is complete.

Please test and confirm.  When the user selects they would like an in
person tutorial, I highlighed the text in yellow so you would easily see it
in the email you receive for the free trial requests.

Thanks,
Blake

**Comment by dpentony** [comment]
There is a typo next to the check box. It should say: Yes, I would like to schedule a personal (not person) tutorial.

**Comment by bguerrettaz** [comment]
This is fixed.

Blake

**Comment by dpentony** [comment]
One more small change please. It now says: "Yes, I would like to schedule a personal tutorial". Please add a period at the end of the sentence and follow that sentence with" Please indicate in the comments box the best time to contact you".

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by bguerrettaz** [comment]
Can this be closed?

**Comment by mnichols13** [comment]
looks good, thanks.

**Comment by mnichols13** [comment]
Please give us a quote for adding the following to the FREE Trial form:

How did you hear about MYcaert?

    referral from another teacher
    Google/web search
    received one of your emails
    saw a Facebook ad
    other: add field for them to fill in

**Comment by bguerrettaz** [comment]
Roughly an hour to hour and a half.

Blake

**Comment by mnichols13** [comment]
Please proceed, we would like these changes implemented.

**Comment by bguerrettaz** [comment]
This is now complete.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good - thanks!
