### ISSUE TITLE
knovotney not getting notifications

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#230]
@knovotney test

**Comment by knovotney** [comment]
I did receive the email. Is this fixed? Kathy NovotneyMarketing Directorwww.mycaert.comLike us on Facebook! Follow our Blog!CAERT, Inc.PO Box 50Danville, IL 61834Phone: 217-446-0500 ext. 134  


-------- Original Message --------
Subject: Re: [MyCaert/Issues-Enhancements] knovotney not getting
notifications (#230)

**Comment by bguerrettaz** [comment]
That's a good sign!  I don't want to jinx it yet, let's see if you continue
to get them.

Blake

**Comment by knovotney** [comment]
Sounds like a plan!

**Comment by BrianPeterlin** [comment]
Yes!

**Comment by knovotney** [comment]
I got that one, as well-looking like it is fixed.

**Comment by bguerrettaz** [comment]
Is this still an issue?
