### ISSUE TITLE
Quizzes Not Showing Under Edit Quizzes

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#231]
Tom Willingham, is in SC. When he goes to his Edit Quiz page, no quizzes show up. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/21852698/bb55d0e8-d7d9-11e6-9122-bcf86f40203a.png)

However, when he goes to his Delete Quiz page, the quizzes are all listed:

![image](https://cloud.githubusercontent.com/assets/5790325/21852755/f3b78f3a-d7d9-11e6-873e-89f073cbe9d4.png)

This seems to be an issue only with his account. We've spot checked other and did not see it.. Please advise.

**Comment by mnichols13** [comment]
another teacher has called with this issue:  Felix Landry in the National state.  This needs fixed ASAP.  Status please?

**Comment by mnichols13** [comment]
we now have a third teacher, this time in IL who cannot see their quizzes
Jay Solomonson

**Comment by dpentony** [comment]
Also, no quizzes show up under the Activate/Deactivate Quiizes link:

![image](https://cloud.githubusercontent.com/assets/5790325/21899479/f18ba426-d8b5-11e6-8a4a-195799af5091.png)

**Comment by bguerrettaz** [comment]
This issue is resolved on both pages (Edit and Activate/Deactivate).

The issue was a function called (CINT) which converts to integer, which was
out of bounds.  I checked the data and found that we should be using a
different function, (CLNG).

It took a bit to track down as there were no visible errors, so I have to
dissect the HTML.

Please let me know if you see any issues.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks for fixing this.

So, why were we using (CINT) in the first place?

**Comment by bguerrettaz** [comment]
Generally the scope of this conversion method is enough, for different
reasons, as it counts records, the number grew about the scope of that
method (not necessarily how many of something the teacher has, but more the
inner workings of the code and how many times it is looping through
something to do 'checks').

Converting to CLNG will safeguard us from that going forward.

Blake
