### ISSUE TITLE
Hide Disable Printing Link

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#232]
Can you provide an estimate of how long it would take to hide the "Disable Printing" link from the Quiz Parameters?  Students are often able to print the quiz, even when it is disabled (using CTRL+P, or CTRL+PrtScr).
![image](https://cloud.githubusercontent.com/assets/21039374/22156880/35be5564-df03-11e6-852e-50dcd614c2a4.png)

**Comment by bguerrettaz** [comment]
Just to hide it?  An hour will be it

**Comment by knovotney** [comment]
Blake, please proceed with doing so. Thank you.

**Comment by bguerrettaz** [comment]
This is complete.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,

I am still seeing it:
![image](https://cloud.githubusercontent.com/assets/21039374/22207959/2d84eefa-e14f-11e6-8d28-f214f351ce58.png)

**Comment by bguerrettaz** [comment]
Ok, I changed it on the EditQuizParameters page.  I'll have to also change
it on the AddQuiz page.

Blake

**Comment by bguerrettaz** [comment]
The add quiz page is complete as well.

Blake

**Comment by mnichols13** [comment]
When the students open a quiz, the icon to print the quiz still shows.   What would it take to get rid of this? 

![image](https://user-images.githubusercontent.com/5790342/31675917-9eaf04b8-b32b-11e7-971e-23ee2a0f03dc.png)

**Comment by dpentony** [comment]
@bguerrettaz - have you looked into this?

**Comment by bguerrettaz** [comment]
Hi,

I can remove that link as well.  Should just be a half hour.

Blake

**Comment by dpentony** [comment]
Can you hide it instead of eliminating it?

**Comment by bguerrettaz** [comment]
Yes, I can do that.

**Comment by bguerrettaz** [comment]
This is complete.

Thanks,
Blake
