### ISSUE TITLE
Gretchen Schleper -Landscaping Course not showing in Manage Course Rosters

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#233]
Gretchen Schleper in Upsala MNis not able to input students into the course she has created called Landscaping.

![image](https://cloud.githubusercontent.com/assets/21039374/22699923/d92f1cc0-ed26-11e6-8449-a892a6b16a6d.png)

![image](https://cloud.githubusercontent.com/assets/21039374/22700005/232314b2-ed27-11e6-8c92-f4b4106d963b.png)

**Comment by knovotney** [comment]
We're closing this issue. We made a copy of the course outline and it worked.

**Comment by dpentony** [comment]
This is just a record to indicate that we had this problem once before in regards to Github 165. No action is needed at this time.
