### ISSUE TITLE
Microsoft VBScript runtime error '800a000d' on Teacher account Katie Arms - SC

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#234]
Please look at Katie Arms account in South Carolina.    She cannot login and I cannot make any changes.  I tried edit/delete school and edit/delete teacher.

I did notice that the Focus is "0" rather than AG.  I don't see any other issues.. please help ASAP.
![image](https://cloud.githubusercontent.com/assets/5790342/22830843/a02ac6b0-ef6d-11e6-9b1c-ee015aff0379.png)

**Comment by bguerrettaz** [comment]
For whatever reason, her account was messed up in several different areas.
I've cleaned up the bad data and now you'll be able to edit her account.

Blake

**Comment by mnichols13** [comment]
thanks. looks good
