### ISSUE TITLE
E-units won't load on Leyna Millers account

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#235]
From the MY Students tab -
Nothing will load on the Assign E-units or Ppts to students

The page is blank
![image](https://cloud.githubusercontent.com/assets/5790342/22984587/7839e792-f36b-11e6-9597-289a244a073d.png)

**Comment by bguerrettaz** [comment]
This is fixed.

We were getting overflow errors when using a method called CINT, which is a
conversion (we've seen this before).  It has to do with how many items are
in a list and how many times they are calculated or looped.

I have converted this method to CLNG, which can handle much, much more.

Thanks,
Blake

**Comment by mnichols13** [comment]
The page still does not load.   Did you test this?

**Comment by bguerrettaz** [comment]
Yes, I tested it.  The courses I checked worked, but I just found 2 courses
that gave the same issue.  There was a CINT instance that I missed on the
initial fix.  All courses I test now seem to be working correctly.

Blake

**Comment by mnichols13** [comment]
looks good now...this teacher has 18 old course outline titles that show up in her menus.  I want to double check with her, but may ask you to clean these up for her.  If so I will reopen and list the titles here.
