### ISSUE TITLE
Error Message in Quiz Reports

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#237]
Doug Falk IL Ag teacher is getting an error report when he tries to bring up a quiz report for his ag students. I was able to replicate it. Click on Current School Year Report under the MY Quizzes tab. Scroll to the bottom of the page. Under the the section on State Standards Report (Individual Students), choose a student from the pulldown then click on Quiz Report By Student (New). You will get the following error:

![image](https://cloud.githubusercontent.com/assets/5790325/24074319/4603abd8-0bd4-11e7-9744-76f3e2b68e42.png)

Please advise as to what is causing this. I believe we added this report in the last couple of years.

**Comment by bguerrettaz** [comment]
This is resolved.  It seems that the assembly files needed updated.  Once I
found the issue and updated the assembly files then recompiled, it tested
out correct.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks!
