### ISSUE TITLE
Navigating Sample Course Outlines

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#238]
For teachers in the National State, we've created several "sample state course outlines". For example, login as Kari Dillinger from OK. If you hover over the MY Courses tab, a pop-up screen appears with MY State Courses listed on the right hand side of the pop-up. It is very difficult to navigate to those sample course outlines. You have to move your mouse just right or the pop-up disappears. Further if you try to get to the"slide" on the right side  that allows you to go further down in the list of state courses, the pop-up disappears. This is all just too touchy. Is there anything that can be done to make the pop-up screen not so sensitive to how you move your mouse?

**Comment by bguerrettaz** [comment]
I see what you mean.  I'll take a look through the JavaScript/Ajax and see
if I can make some tweaks.  These are hard to pinpoint, because they are
dynamic in the screen.

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
Yes, after a few hours of frustration and playing with .CSS settings, I
finally found an article regarding a known bug with a recent Chrome version
that causes the hover menu to disappear.  It has to do with when a scroll
bar is within the hover object and when you hover over that scroll bar.

A recent update to Google Chrome fixes this issue.  I have tested and
confirmed that.  I also tested all other major browsers and confirm that it
was just that version of Chrome.

Here is how to update chrome:

https://support.google.com/chrome/answer/95414?source=gsearch&hl=en

**Comment by dpentony** [comment]
@mnichols13 - let me know if you are able to update Chrome on your computer. According to the instructions Blake provided, I am running the most recent version, but I still am seeing the issue.

**Comment by bguerrettaz** [comment]
Dan - what version number are you on?

**Comment by dpentony** [comment]
Blake - Version 56.0.2924.87 (64-bit)

**Comment by bguerrettaz** [comment]
Hmm, that is the version with the issue.  It should say something like,
'you are nearly up to date' relaunch now, or something.  This is the latest
version, and fixes the issue:

Version 57.0.2987.133

Thanks,
Blake

**Comment by mnichols13** [comment]
I updated CHROME and it took care of the issue for me.

**Comment by dpentony** [comment]
I had to re-start my computer and now all is well.
