### ISSUE TITLE
Error Message: Add Image to Quiz

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#241]
Howard Heavner at Southern Illinois University was trying to add an image to a quiz question, and received this error message. He had already uploaded several other images to questions without issue.
Quiz Name: Surveying Test 1 Introduction to Surveying and Legal Land Descriptions.

![pastedimage](https://cloud.githubusercontent.com/assets/21039374/25014062/2cddf9cc-2044-11e7-9eba-d107bbd2cbb9.png)

This is the image he was trying to add
![25](https://cloud.githubusercontent.com/assets/21039374/25014125/72729fc4-2044-11e7-8211-25412585c79b.jpg)

**Comment by knovotney** [comment]
Any further work on this?

**Comment by bguerrettaz** [comment]
Yes, I have been looking into this issue.  That image shouldn't be an
issue, but for whatever reason, it is.  I'm going to try to convert it to
different types and see if that helps.

Blake

**Comment by bguerrettaz** [comment]
Hi Kathy,

I was testing this and couldn't get it to be recreated.  I added the image
to question 33 in that quiz.  Can you ask the teacher to try it again and
walk me through the exact steps if it happens again?

That error message is pretty vague and makes me feel like it was more of a
one-time occurrence, but I'd like to be sure.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,

We will keep this issue open, only to see if it occurs again in the near future. Thank you for checking in to it.

**Comment by bguerrettaz** [comment]
No problem, please let me know if you encounter again.

Blake

**Comment by knovotney** [comment]
I am going to close this issue for now. If it happens again, we can reference this situation. Thanks. 
-Kathy
