### ISSUE TITLE
Leverage the Google courses.courseWork API on MyCaert Saved Course Outline Screen

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#242]
Blake, we need an estimate for this, Kathy would like to consider this as a future Google Classroom integration feature

Setup MyCaert teachers with Google Single Sign On

Provide the ability for teachers to assign Google Classroom Coursework from the MyCaert Saved Course Outline Screen.  It appears we can leverage the Google courses.courseWork API.

https://developers.google.com/classroom/reference/rest/v1/courses.courseWork

![screenshot](https://cloud.githubusercontent.com/assets/5776485/26695883/1f8443da-46d2-11e7-8766-d8b24ec2b963.png)

**Comment by bguerrettaz** [comment]
After some high-level digging into this, I would estimate 20-40 hours,
since this is a new space, there is a large range because I don't want to
underestimate the work.

That only includes placing the 'Google Assign' button on the saved course
outline screen.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. We'll give this some thought about possibly doing it in the future.

**Comment by knovotney** [comment]
Blake, 
Is everything else complete, minus the 'Google Assign'  button?

**Comment by bguerrettaz** [comment]
Everything is completed and so far, tested.

**Comment by knovotney** [comment]
Thank you!
