### ISSUE TITLE
Graphical Reports & Printer Friendly, Columnar Report Errors

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#243]
Error Messages Attached

![image](https://cloud.githubusercontent.com/assets/21039374/26835215/c9346d16-4aa5-11e7-82b2-507b69a9dbbd.png)

![image](https://cloud.githubusercontent.com/assets/21039374/26835249/e09cae1e-4aa5-11e7-837e-7dcbdd38e320.png)

**Comment by knovotney** [comment]
Hi All,
I get those error messages whenever I click on either options on the MyQuizzes "Reports" Page under "Cumulative Quiz Reports".

**Comment by bguerrettaz** [comment]
Brian - are you familiar with ChartDirector.API?  It might not be installed
on the machine from the migration?

**Comment by bguerrettaz** [comment]
I will look

**Comment by knovotney** [comment]
Any further updates on this issue?

**Comment by BrianPeterlin** [comment]
I found the installer, i will get it out there today

**Comment by BrianPeterlin** [comment]
Give it a try now

**Comment by knovotney** [comment]
Graphic Reports actually produced something, but it still isn't show the "graph".
![image](https://user-images.githubusercontent.com/21039374/27135743-5adfd218-50e7-11e7-8039-8bfb07358f04.png)



However this error is still displayed on the "Printer Friendly, Columnar Report".
![image](https://user-images.githubusercontent.com/21039374/27135842-a30cd126-50e7-11e7-893f-d64bce914f07.png)

**Comment by knovotney** [comment]
Just wanted to check on this to see if any progress has been made.

**Comment by bguerrettaz** [comment]
I'm seeing the graphs come up correctly and the printer function working.

Can you please retest and confirm that it is working?  If it isn't, please walk me the steps to recreate the issue.

**Comment by BrianPeterlin** [comment]
we are not getting the same error

what user ID are you using?  which quiz?  can you provide the exact steps so we can recreate

**Comment by knovotney** [comment]
COLUMNAR REPORT. 
![image](https://user-images.githubusercontent.com/21039374/27437822-6f86d57c-5731-11e7-8f36-fb8025aaf0c8.png)

GRAPHICAL REPORT. I clicked one of the many pages he had and this is what appeared. 
![image](https://user-images.githubusercontent.com/21039374/27437881-a13222b6-5731-11e7-84d1-8b8c0332acf2.png)

Same issue for Kevin Garling
Login : KGarling 
Password: rutkowske
State: IN

If you would like to schedule a WebEx meeting where you can see my screen as I try to use the account, I am able to do that as well. It DID work in my own account, but I have two students with any quiz data currently, so mine was fine. Kevin has been using this for close to 10 years, if not more.

**Comment by BrianPeterlin** [comment]
Ok, it is timing out from cloud flare

Let me discuss options with blake

**Comment by dpentony** [comment]
Have any options been discussed?

**Comment by BrianPeterlin** [comment]
Yes

This article provides an option.  Blake, can you provide an estimate?

https://stackoverflow.com/questions/38536167/is-it-possible-to-increase-cloudflare-time-out

**Comment by bguerrettaz** [comment]
I'll research and provide an estimate.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
This is a tough one, I'm not sure what's causing the slowness, if its query
or what.

The article that had suggestions included one of two things:
- Queuing, using RabbitMQ or alike
- AJAX calls

Neither of which have been implemented on these pages, so this would have
to be written.

I'll have to research more to fully understand what needs to be queued, etc.

Since there is a lot that goes into this, I would say it could be anywhere
from 5-12 hours, I just don't want to under estimate with so many unknowns.

Please let me know how you'd like me to proceed.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,

At this point, for this teacher, an extraordinary amount of data exists for quizzes, courses, and students. Would it make a difference, for these reports, if the data is decreased (ie- deleting of courses, quizzes and students)?

If so, I will communicate a with the teacher to delete those items.

**Comment by BrianPeterlin** [comment]
Yes, it would reduce the load time and we may no longer hit the timeout from cloudflare

**Comment by bguerrettaz** [comment]
Exactly, it might be helpful to look at purge or archive schedules for some
of these tables.  Some are very large, which means performance can take a
hit.

Blake

**Comment by BrianPeterlin** [comment]
did the purge help?  Do we still need to do something?

**Comment by knovotney** [comment]
Still waiting to hear from the teacher. I will keep this open for a bit longer until I know more of what may need to be done. Thanks.

**Comment by knovotney** [comment]
We are currently working (both the teacher and I) to delete some of this data. Just now, after we've deleted about 30 quizzes, I got this error message twice.
![image](https://user-images.githubusercontent.com/21039374/28337889-0d6e6608-6bd5-11e7-9fd8-4c45b443d92e.png)



As did the teacher

**Comment by dpentony** [comment]
We now get the same error message even when trying to log into an account. It is happening on multiple accounts.

Microsoft OLE DB Provider for SQL Server error '80040e14'

The transaction log for database 'csat2' is full. To find out why space in the log cannot be reused, see the log_reuse_wait_desc column in sys.databases

/Newlogin.asp, line 601

**Comment by knovotney** [comment]
This issue is resolved.
