### ISSUE TITLE
Update MN state Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#244]
Minnesota has paid to extend their state subscription by one year. We need you to update the subscriptions based on the following parameters:

For any teacher in MN who has a master de-activate date of 7/1/2017, please change this date to 7/1/2018.
For any teachers who have expirations dates of 7/1/2017 on the following 5 libraries: Animals, Plants & Soils - Revised, Biological Science in Ag, Environmental Resources, Animals, Plants & Soils, and Minnesota Natural Resources libraries, please change their expiration dates for lesson plans, Eunits, and CSAT for these libraries to 7/1/2018.
We would need this done before July 1.

Thanks. Please let us know if you need additional info.

**Comment by bguerrettaz** [comment]
This update is complete.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.
