### ISSUE TITLE
Update Missouri MYcaert Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#245]
Missouri has extended their subscription to MYcaert for another year. We need you to make the following changes on a state-wide level prior to July 1:

For any teachers with a master de-activate date of 7/1/17, we need you to change it to 7/1/18.

For any teachers who have de-activate dates of 7/1/17 to the six Missouri libraries (Agriscience, Horticulture, Animals, Plants & Soils, Ag Mechanics, Agribusiness, and Environmental Resources) we need you to change them to 7/1/2018. This includes lesson plan, Eunit, and CSAT access for the six libraries.

Please let em know if you have questions.

NOTE: You did the same thing last year. See issue #195 in closed issues.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by dpentony** [comment]
Its that time of year when we need to update the Missouri state subscription. Missouri has extended their subscription to MYcaert for another year. We need you to make the following changes on a state-wide level prior to July 1:

For any teachers with a master de-activate date of 7/1/18, we need you to change it to 7/1/19.

For any teachers who have de-activate dates of 7/1/18 to the six Missouri libraries (Agriscience, Horticulture, Animals, Plants & Soils, Ag Mechanics, Agribusiness, and Environmental Resources) we need you to change them to 7/1/2019. This includes lesson plan, Eunit, and CSAT access for the six libraries.

Please let em know if you have questions.

NOTE: You did the same thing last year. See issue #195 in closed issues.

**Comment by bguerrettaz** [comment]
This is complete.

Thanks,
Blake

**Comment by dpentony** [comment]
Missouri has extended their subscription for another year. Please make the following changes for all Missouri ag teachers by July 1:

For any teachers with a master de-activate date of 7/1/19, we need you to change it to 7/1/20.

For any teachers who have de-activate dates of 7/1/19 to the six Missouri libraries (Agriscience, Horticulture, Animals, Plants & Soils, Ag Mechanics, Agribusiness, and Environmental Resources) we need you to change them to 7/1/2020. This includes lesson plan, Eunit, and CSAT access for the six libraries.

Please let em know if you have questions.

**Comment by mnichols13** [comment]
Blake,
We have teachers contacting us because they cannot login.  When will this be complete?

**Comment by bguerrettaz** [comment]
Hi, this is complete.  Please test and confirm.

**Comment by mnichols13** [comment]
I believe it all of Missouri looks good.  thanks.
