### ISSUE TITLE
Global Update for IL CTE Users

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#246]
We need to extend the IL CTE state subscription to 1.1.2018. The master deactivate date on all IL CTE user accounts need to be changed to 1.1.2018. Also, the deactivate dates for the lessons, Eunits, and CSAT on the libraries they current have access to also need to be changed to 1.1.2018.

NOTE: We generally update the subscription for one year at a time. However, since we reside in a state that does not pay its bills, we only want to update it for the six month period.

This needs to be done by 7.1.2017. If you need to see an example of how to update an account, please look at my IL CTE account. I have updated it accordingly.

**Comment by bguerrettaz** [comment]
Just as an FYI, I worked on all of the date changes this weekend.  I plan
on doing both states and the IL CTE changes all at once to reduce the
database backups (they take up a lot of space).

Just wanted you to know I have already started all of the work.

Blake

**Comment by bguerrettaz** [comment]
These changes are complete.  IL CTE global updates are larger in scale and should be spot checked throughly. 

Please test and confirm.

**Comment by dpentony** [comment]
See original post on this topic. The state has finally paid some of its bills. We need to update all IL CTE subscriptions from 1.1.2018 to 7.1.2018.

**Comment by dpentony** [comment]
@bguerrettaz - what's the status on this?

**Comment by bguerrettaz** [comment]
This is complete.  Please spot check a few to confirm correct.

Thanks,
Blake

**Comment by dpentony** [comment]
Not all of the IL CTE subscriptions were updated correctly. We are running into an issue where some teachers have an expiration date of 1/1/2018 for three libraries. These three libraries are: Ag Mechanics and Technology, Accounting, and Web & App Development. The correct expiration for these three libraries should be 7/1/2018 so that they match those of all other libraries.

**Comment by bguerrettaz** [comment]
I will update all IL CTE teachers that are active, with these libraries
from 1/1/2018 to 7/1 2018, is that correct?

**Comment by dpentony** [comment]
Yes

**Comment by bguerrettaz** [comment]
This is complete.
