### ISSUE TITLE
Quote on Uploading Word.doc Quizzes

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#247]
We have received a great deal of teachers asking to upload quizzes from Word.docs. How long would it take to develop this capability?

**Comment by dpentony** [comment]
Currently, teachers only have the ability to copy each individual question from a Word doc and paste it in question-by-question to a MYcaert quiz. Is there a way where a teacher can upload an entire test from a Word doc into a MYcaert quiz? If so, what is your estimate on hours?

**Comment by bguerrettaz** [comment]
The only way that we could dynamically bring in questions and answers into
MyCaert and the database, is to possibly have them put the questions in
Excel in two columns (we would need to build a template file for them and
they would have to put the questions/answers in that).  Word documents are
more unstructured and would be very hard to automatically import from that
into the current quiz infrastructure.

Another option would be just to upload the word doc, but then it would go
outside of the normal quiz workflow that is in place today for reporting,
grading, etc.

Let me know if either are viable options.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,

Thanks for this information. I understand and would like to know more about the timeline of developing the capability for using the Excel Document. Would the two columns be "Question", "Answer"?

**Comment by bguerrettaz** [comment]
Yes, just thinking high-level, there would be two columns, question and
answer.  The answer column would mimic how answers are selected today in
the quiz build.

There could be an additional column or two needed once I get into the
details.

I would have to build an import interface in the quiz area of the website.
Once imported they could change anything like they currently do today.

Blake

**Comment by knovotney** [comment]
Okay. When you are able, please provide an estimate of hours. Thank you.

**Comment by knovotney** [comment]
Blake,

We wanted to clarify one point. You said: "Another option would be just to upload the word doc, but then it would go outside of the normal quiz workflow that is in place today for reporting, grading, etc" 

Do you mean that the document would be able to be printed by a teacher, or assigned to students through My Files (similar to a document uploaded into MyFiles or MyCommunity)?

**Comment by bguerrettaz** [comment]
Yes, they could upload the word document, and the students could take it in
paper form, but MyCaert might not have record of the quiz or history, etc.
like it does today.  We could always create an interface for the teacher to
enter the results, but that wouldn't guarantee they always would.

**Comment by knovotney** [comment]
Thanks, Blake. Let's investigate the excel version first.

**Comment by knovotney** [comment]
@bguerrettaz ,

Sorry I meant to ask you about this on the phone. Have you had a chance to investigate the logic for the excel version?

**Comment by bguerrettaz** [comment]
If it was pulling questions, answers and other pertinent fields straight from an Excel as an upload into the database I would estimate the following:

- Create Excel template for teachers to populate and place on the website (3-4 hours)
- Create upload function for the teachers to upload the template (1-2 hours)
- Code page to take uploaded file, run checks to make sure its all in template format, and mass upload questions into the database and create a quiz (8-10 hours)
- Testing and issue resolution (3-5 hours)

I think I would have them create a quiz themselves, that way the course, etc. information is already there, and then give them an option to either build the test questions normally within the web page or they can upload (bulk) the questions from an Excel template.  Does that make sense?

**Comment by dpentony** [comment]
@knovotney  - let's discuss this when we are together tomorrow.

**Comment by knovotney** [comment]
Blake:

Based on your response, would it be possible to create a quiz from both the bulk upload template, and the CAERT Question bank? Essentially, I would add my own questions via the template, and then add additional questions via the CAERT QB.

**Comment by bguerrettaz** [comment]
Yes, we could just give them the option to do a bulk upload from a
template, and they could always add more questions from the question bank.
That's how I had envisioned the design for this.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,
I appreciate your comments. We will hold of for now, and let you know if we pursue this option in the future. Thanks.
