### ISSUE TITLE
DE State Admin Issue

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#248]
Trying to create a course outline from the state admin, using several libraries or just one, I receive this error message.  
![image](https://user-images.githubusercontent.com/21039374/27561278-81da2bd6-5a95-11e7-89e6-2a63d9fbd3af.png)

![image](https://user-images.githubusercontent.com/21039374/27561300-97bf8388-5a95-11e7-8702-c0463664afb6.png)

**Comment by knovotney** [comment]
Any status on this?

**Comment by bguerrettaz** [comment]
I've looked into this, and that file, for that state doesn't exist, please see screenshot:

![image](https://user-images.githubusercontent.com/5695475/27793485-d56b9c34-5fc3-11e7-9419-3efdcc4ad85c.png)

You can see from this, that _DE doesn't exist.  I can create one from the others, if there isn't a ton of changes, probably 2-3 hours.

Blake

**Comment by dpentony** [comment]
@BrianPeterlin  - I don't understand. This is basic functionality that is part of any state's admin. Why not in DE?

**Comment by BrianPeterlin** [comment]
I will discuss with blake.  I need to get up to speed on this issue.

**Comment by knovotney** [comment]
Have we made any progress on this issue?

**Comment by BrianPeterlin** [comment]
Blake looked in the old MyCaert site and the files were not on that server either.  @dpentony did the functionality ever work?

**Comment by dpentony** [comment]
Yes

**Comment by BrianPeterlin** [comment]
Dan, I am not seeeing that it worked on in My Caert old
[](
http://mycaertold.cmititestbank.com/admin/login.asp?Confirm=TimeOut
)

**Comment by BrianPeterlin** [comment]
http://mycaertold.cmititestbank.com/admin/login.asp?Confirm=TimeOut

**Comment by dpentony** [comment]
I may have it mixed up with another state. However, this is basic functionality that is part of all state admin pages. This functionality is supposed to be there for all state admins. Take a look at the state admin pages for IL, MO, and FL. If the functionality works for those states, it should be there for DE. That is part of what we paid for when the state admin was first created.

**Comment by BrianPeterlin** [comment]
@dpentony 
ok, it seems like Darrell never built the functionality out and you paid for it.  CommonM@n will cover blake's expenses.

@bguerrettaz, you may begin work.

**Comment by dpentony** [comment]
Thank you. Please keep me posted on the progress.

**Comment by bguerrettaz** [comment]
I have added this page.  Can you please test and confirm functionality?  I
had to cater the page for DE, so I want to make sure it is working as
desired.

Thanks,
Blake

**Comment by knovotney** [comment]
Blake,

I just created a quick test course outline and it worked. Thank you.
