### ISSUE TITLE
Archiving Students Error Message

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#250]
On the admin page, we have the ability to archive both teachers and students. Generally, we do this once a year. I successfully archived 220 teachers, but when I tried to do so for students I get the following error message. Please advise.

Microsoft OLE DB Provider for SQL Server error '80004005'

The select list for the INSERT statement contains more items than the insert list. The number of SELECT values must match the number of INSERT columns.

/admin/ArchiveStudents.asp, line 11

**Comment by bguerrettaz** [comment]
Hi Dan,

I found the issue with the insert statement and have added the necessary
fields.  Can you please try this again?  I didn't test it myself because I
wanted you to be able to do the actual archiving.

Thanks,
Blake

**Comment by dpentony** [comment]
It appears to work now. 4,663 students were archived. Thanks.
