### ISSUE TITLE
Revise Pricing Tab on MYcaert Homepage

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#251]
Under the Pricing tab on the homepage, would there be a way for a pull down menu of states to appear and when they select their state, the appropriate order form would appear? We routinely run into cases where a state such as Indiana uses the order form that is posted under pricing. However, they really need to use the Indiana order form which has different prices. We would need to be able to link a PDF of a specific order form to a particular state. We need to do this because we don't want to show a teacher in Indiana that they are paying higher prices for the same libraries as teachers in WI.

**Comment by bguerrettaz** [comment]
Yes, this would be possible.  I would create a drop down menu with all of
the states and would link to the correct PDF, once they select the state?

Should only take 3-5 hours to build all of that.

Blake

**Comment by dpentony** [comment]
Could we link more than one PDF under a particular state? 
We'll talk among ourselves and get back to you.

**Comment by dpentony** [comment]
Could we link more than one PDF under a particular state?

**Comment by bguerrettaz** [comment]
I would have to create a list of states and for each state create a sub-menu with 1:many links for the different forms.

It could be done, new estimate for all of this logic would be 5-7 hours.

Blake

**Comment by dpentony** [comment]
@bguerrettaz  - we will probably move forward on this, but let's wait until we get a few of the other open issues resolved. I will let you know when to proceed.

**Comment by dpentony** [comment]
We want to do this but must waiting until we see some of the money the state owes us. I will close the issue for now but plan to address it in the fall.
