### ISSUE TITLE
Adding a zip code field to ADDTEACHER & EDIT TEACHER

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#253]
Blake,
Could you give us an estimate on adding a zip code field in both the ADD Teacher page and the Edit/Delete Teacher page?  In order to match reports in Quick books we would like to be able to have this information easily viewed on the teacher accounts page.  Many of the schools in MYcaert have addresses already entered with a zip code, but we cannot view it unless we go to the Edit/Delete School page.  

Eventually we would want to add a field to the Expiring accounts report, so I am not sure how that will impact it.  Can you take a look and let us know?

**Comment by bguerrettaz** [comment]
To add the zip code field to the add and edit/delete teacher pages and alter the table in the database, it would be 2-3 hours.

Do you want me to also estimate adding this field to the expiring accounts report?

Thanks,
Blake

**Comment by dpentony** [comment]
Yes please.

**Comment by bguerrettaz** [comment]
Just an hour to add zip code to the expiring teacher account report.

Blake

**Comment by dpentony** [comment]
We'll be in touch next week.

**Comment by mnichols13** [comment]
Blake - question about adding the zip code to some of the pages 

1. - We would want it in the add teacher page as well as edit teacher profile
2. - Could this be included in search for a teacher as well - this would be the first page that pops up with Edit/Delete teacher? so this would provide a 3rd option to search for teacher (school, name or zip)
3. - It would be helpful for it to be in the expiring account report as well.

Can you do all of this for the 2-3 hours you mention in a previous comment?

**Comment by bguerrettaz** [comment]
I should be able to do all of that for around 3 hours, maybe a bit over,
but not much.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake,
proceed with this request... 
thanks.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm all functionality.

Thanks,
Blake

**Comment by mnichols13** [comment]
this looks good - thanks!
