### ISSUE TITLE
Estimate for Google Analytics eUnit Downloads

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#256]
can we put the Google Analytics code on the eUnit Download page

http://mycaert.com/authenticationCheck.asp?FN=040114&Locale=eUnits&Org=eUnits/040114.pdf

**Comment by bguerrettaz** [comment]
Yes, probably just .5-1 hour

**Comment by knovotney** [comment]
Please move forward with this.

**Comment by dpentony** [comment]
Just wanted to point out that @knovotney said to proceed on this. I am not getting any emails when she posts to github. Are you? Also, she does not get email notices when someone posts on an issue.

**Comment by bguerrettaz** [comment]
Yes, I did receive hers and yours...I'm not sure why she's not getting
initial posts...might be worth reaching out to GitHub technical support?

**Comment by bguerrettaz** [comment]
Ok, after trying to embed the Google Analytics code into the authentication
page in different ways, none of them are working.

I researched it and the reason it doesn't work is because there needs to be
an HTML page backing the page to embed the code in Javascript before the
<head> tag.  This page is a 'streaming' page, where the PDF is 'streamed'
to the page in non-HTML.

From everything I'm seeing, I won't be able to add Google Analytics to that
streaming page.

Brian - any thoughts?

Blake

**Comment by knovotney** [comment]
I just wanted to check to see if any progress/resolutions had been determined after Blake's findings.

**Comment by bguerrettaz** [comment]
Brian - any thoughts?

**Comment by BrianPeterlin** [comment]
I will dig into it

**Comment by knovotney** [comment]
Just checking on this...any ideas?

**Comment by BrianPeterlin** [comment]
Blake and i are meeting today to discuss options

**Comment by bguerrettaz** [comment]
Brian was able to find an API that we can utilize.  I'm working on
implementing it tonight and tomorrow, hoping to have it completed by
tomorrow evening.

I'll send it out as soon as I'm done and tested.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
I have completed the API call to Google Analytics for the authentication
page (eUnit/LP/PPT downloads).  When you go to google analytics, when you
see authenticationcheck, that's this page.

Please let me know if you have any questions.

Thanks,
Blake

**Comment by BrianPeterlin** [comment]
Is it passing any info about the specific eunit being accessed?

**Comment by knovotney** [comment]
As I view it, I only see the "authentication check". 


-------- Original Message --------
Subject: Re: [MyCaert/Issues-Enhancements] Estimate for Google Analytics
eUnit Downloads (#256)

**Comment by bguerrettaz** [comment]
It's not dynamic (meaning, its not passing what eUnit/LP/PPT), it's just
showing that the page was hit and someone was viewing one of those three
mediums.

Is the desire to know that information at the detailed level?  I would
imagine you'd want it rolled up to at least the eUnit, PPT and LP level?
If you had each individual PDF, you'd have many, many different one's and
not one view.

Let me know what is desired and I can make changes.

Blake

**Comment by knovotney** [comment]
Blake, Will it take a lot of time for the option of each PDF? Kathy NovotneyMarketing Directorwww.mycaert.comLike us on Facebook! Follow our Blog!CAERT, Inc.PO Box 50Danville, IL 61834Phone: 217-446-0500 ext. 134  


-------- Original Message --------
Subject: Re: [MyCaert/Issues-Enhancements] Estimate for Google Analytics
eUnit Downloads (#256)

**Comment by bguerrettaz** [comment]
No, I don't think so.  I think I can do it in about an hour or so.

Blake

**Comment by knovotney** [comment]
Please proceed. 


-------- Original Message --------
Subject: Re: [MyCaert/Issues-Enhancements] Estimate for Google Analytics
eUnit Downloads (#256)

**Comment by bguerrettaz** [comment]
I have completed the changes to Google ANalytics, showing each file that is downloaded.  It will now appear like this:

![image](https://user-images.githubusercontent.com/5695475/30789098-b6c9dcfa-a168-11e7-83b3-62e92959b842.png)

Showing a page hit per PDF/PPT that is accessed.  If the same one is accessed multiple times, it will show the number of hits.

Thanks,
Blake

**Comment by knovotney** [comment]
Thank you, Blake. It looks exactly like I had hoped. We look forward to gleaning information from this.

**Comment by bguerrettaz** [comment]
Great!
