### ISSUE TITLE
Teacher Cannot Access Test Results - May Be Part of 258

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#259]
Marty Speth in WI is unable to access the current school year results for his Root Anatomy test. It is under his Botany course. He gets a Gateway 502 Error:

![image](https://user-images.githubusercontent.com/5790325/31233506-71c68084-a9b2-11e7-926e-9036986690db.png)

Please advise.

**Comment by dpentony** [comment]
The error message occurs when trying to access ANY test results, not just Root Anatomy.

**Comment by BrianPeterlin** [comment]
i would try this again.  I suspect the database was running slow and the page timed out.  It might be ok now.

**Comment by BrianPeterlin** [comment]
adding the cores should speed the page up

**Comment by dpentony** [comment]
I tried again and still got the error message.

@BrianPeterlin  - please call me this afternoon. I want to make sure we understand this issue so that we can better inform our customers of the cause and the timeline for getting it corrected.

**Comment by mnichols13** [comment]
Corinne Galvan in IL is having this issue when trying to pull test results from Intro to AFNR and Ag Exploration.   She says the school has Fiber Optics and that they should not have connection issues.  She was trying to pull quiz data for Lesson 4.1 (Intro to AFNR) when she does this she gets the Cloud Flare error message attached. 
![image](https://user-images.githubusercontent.com/5790342/49394609-00c57e80-f6fa-11e8-992a-5227662be237.png)

**Comment by bguerrettaz** [comment]
@Brian Peterlin <bpeterlin@cmiti.com> - what are your thoughts on this?

**Comment by mnichols13** [comment]
any progress ?  or comments?

**Comment by bguerrettaz** [comment]
I’m working on putting buffers in place so that will hopefully resolve this issue.  I’ll reply back when completed.

**Comment by bguerrettaz** [comment]
This should be better now, I put in a response buffer and tested to make
sure it was cycling through correctly.  If the user still has this issue,
please ask for the exact URL they encounter this.

Thanks,
Blake

**Comment by mnichols13** [comment]
thanks - Teacher is happy.
