### ISSUE TITLE
Changing "Free 30 Day Trial" to "Free Trial" Estimate

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#260]
We are considering changing Free "30-Day Trial" to "Free Trial". What would be the estimate to do this?

The Trial request screen would also need any wording reading 30-Day removed.

**Comment by bguerrettaz** [comment]
Just an hour.

Blake

**Comment by dpentony** [comment]
Please proceed.

**Comment by bguerrettaz** [comment]
This is complete.

Blake

**Comment by knovotney** [comment]
Thank you.
