### ISSUE TITLE
Global Update IL Ag Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#261]
The IL Ag Subscription is set to expire on 12.1.17. We need to globally update it to expire of 6.1.2021. This involves changing the master deactivate date on all accounts set to expire 12.1.17. We also need you to change the expiration dates on the lesson plans, Eunits, and CSAT for any libraries set to expire on 12.1.17 EXCEPT Agriscience (ASB) and Ag Mechanics and Technology (AMT). These two libraries should not have their expiration dates changed.

**Comment by bguerrettaz** [comment]
I will work on this first and let you know when it's complete.

Blake

**Comment by bguerrettaz** [comment]
This update is complete.  Please confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks.

**Comment by dpentony** [comment]
We are running into lots of IL teachers that did not get updated. I will send you an Excel file of who those teachers are. Any idea why they did not get updated? Can you fix their accounts in bulk? We will fix individual ones if they contact us.

**Comment by mnichols13** [comment]
Also the pop up box appears when syncing the dates - can this be removed as well?

**Comment by mnichols13** [comment]
I have noticed that on the teachers that were not updated properly, their deactivation date is 7/1/2018 rather than 12/1/2017 - so it didn't match.   I believe that is the deactivate date for CTE not AG, so I am not sure exactly how that happened.

**Comment by bguerrettaz** [comment]
It looks like the reason these weren't updated is because their deactivate
dates didn't match the others in the group.  I found 100 Ag teachers that
had a deactivate date of July 1st, 2018 when I made these chances, not
12/01/2017 like the rest.

When I do these updates, I search for three criteria, state, Ag or CTE and
deactivate date given by you.

Do you want me to update these 100 teachers?  If so, do I change their
deactivate date to 06/01/2021 like the rest and all of the same
lesson's/eUnit's?

Any thoughts on how these got a different deactivate date?

Thanks,
Blake

**Comment by dpentony** [comment]
I am guessing that there was a wrong date for when the FCAE staff added new teachers via the state admin. Please proceed with the 100 teachers as we continue to be contacted.

**Comment by dpentony** [comment]
@bguerrettaz - we are getting lots of requests to fix the issue and we are handling them on an individual basis as they are received. If you think you cannot get the rest of them updated tonight, please let me know.

**Comment by bguerrettaz** [comment]
I will get it fixed tonight.  Do you want me to target a specific date or just make sure all active ag teachers have the 06.01.2021 date with the libraries you indicated originally?

**Comment by dpentony** [comment]
Please make sure all active teachers have access until 6.1.2021 to all the libraries I previously indicated. Thanks.

**Comment by bguerrettaz** [comment]
This is complete.  Please spot check a few just to confirm.

Thanks,
Blake
