### ISSUE TITLE
Can't See Custom Lessons in Course Outline

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#263]
We had a teacher in the national state call to tell us he had added custom lessons to a course outline and is not able to see them in the outline. He can however, see them listed when he goes to re-order the lessons in the outline, but despite this fact, there is no way to access the custom lesson file.

I was able to replicate the issue under my IL Ag account. I have a saved course outline called 8.11.14 test. It is the first outline listed under MY Courses. I added two custom lesson files to the outline. One was a Word doc and one was a PDF. When you look at the course outline itself, the lesson plans are not listed. However, if you go to re-order lessons in the outline, you can see the lesson titles listed (see below). Regardless, there is no way to actually get to the custom lesson files you added to the course outline. Please advise.

![image](https://user-images.githubusercontent.com/5790325/33148404-5d723704-cf91-11e7-84d4-e697bfe57242.png)

**Comment by bguerrettaz** [comment]
I'll take a look and see what the differences are in the query and report
back.

Thanks,
Blake

**Comment by dpentony** [comment]
@bguerrettaz  - were you able to determine what is causing this?

**Comment by bguerrettaz** [comment]
Yes, I was able to see the issue.  When I look at the data, the custon-outline page has a more complex query, because of the data that is displayed on the screen (the reorder page is much more simplistic and doesn't require as much data displayed).

You can see from this query that the LessonID field is NULL for the last three outlines, the ones in which you added, which means its never been set:

![image](https://user-images.githubusercontent.com/5695475/33300638-0f997e32-d3b7-11e7-8b18-b2575aef4332.png)

Since this field is NULL, its not pulling it into the custom-outline page.  This is most likely the same reason this is occurring for the teacher.

When someone adds a custom outline, don't they need to select a corresponding lesson?  

Please let me know your thoughts.

Thanks,
Blake

**Comment by dpentony** [comment]
No, they do not need to select a corresponding lesson. The purpose of the "Add Custom Lesson to Course Outline" link allows teachers to load a lesson plan not in MYcaert into a course outline consisting of MYcaert lessons. It was developed to allow teachers to include their own lesson plans into the outline. Once loaded, that custom lesson plan file shows up in the course outline and in the exported course outline. This is something that has worked fine in the past. We need to determine why it is not working now.

**Comment by bguerrettaz** [comment]
I don't see anything that has changed in a while, but I can work on making
sure those are included.  Right now, they are excluded if they don't have a
corresponding lessonID.

Thanks,
Blake

**Comment by dpentony** [comment]
@BrianPeterlin - Simply put, we want that functionality back. We paid for it when we created v2.0 and it is no longer there. Thus, we want it back since we already paid for it.

I'd also be interested in learning how it disappeared in the first place.

**Comment by BrianPeterlin** [comment]
Not sure when it stopped working

Maybe blake will know more once he puts the fix in

**Comment by bguerrettaz** [comment]
I looked at the code and GitHub to try and see if we made any changes to
this code and didn't find anything.  We've done work on the course outline
page, but not the custom course outline page.

I had to write two queries and merge them (union).

I have tested this and it looks to be working correctly now.  Please test
and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by dpentony** [comment]
@bguerrettaz  - We received the message below from an IL ag teacher. He is saying that the lessons in the regular course outline view do not appear in the same order as those he in the Roorder Custom Outline page. Since he thinks it happened in the last day or two, we're guessing it is a result of the change you made last night.

The lessons listed in my course outlines been mixed up from the order I had them in before. This just happened today or yesterday. When you go to the "Reorder in Custom Outline" page they appear in the order I had them. But on the regular page, even after you save the custom outline, they are mixed.

**Comment by bguerrettaz** [comment]
This is resolved.  The order by statement (for sorting) was missing an
attribute.

Please test and confirm.

Blake
