### ISSUE TITLE
Clean up old course titles for teachers

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#264]
Teacher: Van Kirkwood - Missouri has a lot of old junk showing up that needs cleaned up.  

Save these course outline titles:
Ag Communications
Ag Construction
Ag Science I
Ag Science II
Animal Science 2017-18
Conservation

Please delete all other course outline titles that are showing up in these four areas
Manage Course Rosters
Edit Quiz - assigning to a new course
Assigning E-units and PPts
Adding a new student

**Comment by mnichols13** [comment]
Blake, when can you get this done?

**Comment by bguerrettaz** [comment]
This is complete, although, there were two each of Ag Science I and II, and
I didn't know which one to remove.

Thanks,
Blake

**Comment by mnichols13** [comment]
I don't know that it matters, which one.  Just remove one of each please.

**Comment by bguerrettaz** [comment]
Done, thanks.

**Comment by mnichols13** [comment]
looks good, thank you.

**Comment by mnichols13** [comment]
Could you please clean up - delete these old quiz class/empty course outlines?
Teacher:  Jeff Maierhofer in IL
Ag account:  password:  seneca

akdfad
Animal Science
Asexual Reproduction
District Parliamentary Procedure CDE
Section 7 CDE Exams
Soil & Plant Science

**Comment by bguerrettaz** [comment]
Hi, this is complete.  Please verify.

**Comment by mnichols13** [comment]
looks good

**Comment by mnichols13** [comment]
Could you please remove the course outline titled Advanced Electricity and Hydraulics from the Rigby FFA teacher account in Idaho - this is a duplicate title that **does not** show up in the Course outlines, but does show up in other places: manage course rosters, editing quizzes, adding students, maintain assigned E-units & ppts.

username: Rigby_FFA
pw: FFA2017

**Comment by mnichols13** [comment]
Blake - is it possible to get this done today?

**Comment by bguerrettaz** [comment]
This is complete.  Thanks

**Comment by mnichols13** [comment]
thanks.

**Comment by mnichols13** [comment]
Can you please remove the following course outline titles from Hoosier Hills Area Vocational Center account - teacher Emily Russ.  

These show up in the drop down boxes in seven places: 
Manage course rosters
Add Students
Edit Students
Assign E-units/ppts
Maintain E-units/ppts
Create a quiz
Edit a quiz

**She has five good course outlines, some titles are very similar, so please use caution.** 

Animal Science South
Indiana ALS Plants
Indiana Plant and Soil Science
Intro
Landscape
Martinsville
Natural Resources Management
Plant & Soil Science

**Comment by bguerrettaz** [comment]
To confirm, these are the course outlines to REMOVE:
Animal Science South
Indiana ALS Plants
Indiana Plant and Soil Science
Intro
Landscape
Martinsville
Natural Resources Management
Plant & Soil Science

**Comment by mnichols13** [comment]
yes these mentioned titles are the ones to delete. thank you

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
For Kevin Garling Indiana teacher at Lowell High School - please remove the following course outline titles. 
Fund of Ag 06
Fund of Ag 07
Fund of Ag 08
Fund of Ag 09
Fund of Ag 10
Fund of Ag 11
Hort 06
Hort 07
Hort 08
Hort 09
Hort 10
Hort 11
Indiana Natural Resources
Landscape Mgmt 06
Landscape Mgmt 07
Landscape Mgmt 08
Landscape Mgmt 09
Landscape Mgmt 10
Landscape Mgmt 11
NRM 06
NRM 07
NRM 08
NRM 09
NRM 10
NRM 11
NRM 16
Test Acad State Outline

These show up in the drop down boxes in:
Manage course rosters
Add Students
Edit Students
Assign E-units/ppts
Maintain E-units/ppts
Create a quiz

**Comment by bguerrettaz** [comment]
This is complete, please confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
Please remove Landscape Mgmt 19 from Kevin Garling's account.  I have renamed the good one Landscape Mgmt 19 good outline.

**Comment by mnichols13** [comment]
Blake,
When a teacher deletes a course outline it needs to be deleted from all menus.   Please provide the estimate for a correct fix so on this.  It is a recurring issue that we would like to deal with.

**Comment by bguerrettaz** [comment]
Roughly 2-4 hours to fix/test this.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake,
We would like to proceed with the fix.  Can you give me an idea of when you can finish this?

**Comment by bguerrettaz** [comment]
I'm hoping to have this completed by mid week.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Hi - in testing this, the logic is already here to do this fix...when I
tested it, I went to 'My Saved Course Outlines' and tested deleting a
course outline:

[image: image.png]

Once I did that, it deleted from the two tables that I normally have to
clean up for these requests.  Is this where you normally do this cleanup?

Is there another place to cleanup course outlines that is missing this
logic?

Thanks,
Blake

**Comment by mnichols13** [comment]
The places that old course outlines show up are:
Manage Course Rosters
Edit Quiz - assigning to a new course
Assigning E-units and ppts
Maintain E-units and ppts
Adding a new student

**Comment by mnichols13** [comment]
Blake, were you able to check these other tables?  Is this complete?

**Comment by bguerrettaz** [comment]
Yes, I checked all of those locations, am confused as to why this wasn't
already working.  I deleted the 8.22.14 test course outline from Dans
profile and it deleted from the appropriate tables and no longer shows up
in any of those locations.

Can you run a similar test...using the delete course outline link:

[image: image.png]

When doing this, please let me know which teacher you used, and which
course outline you deleted.

Thanks,
Blake

**Comment by mnichols13** [comment]
its completely possible that the majority of these issues are from course outlines that were created in what we call MYcaert 1.0.   Does that change any of the logic?

**Comment by bguerrettaz** [comment]
I don't think so, as the delete course outline link has all of the logic to
delete it from the two core tables, which drives all of those screens you
sent me before.

**Comment by mnichols13** [comment]
I don't really have an answer except to say that this is a constant issue where teachers have course outlines that do not exist under the blue MY COURSES tab, however they show up every other place.  You can look at my CTE account as an example.   
username:  mindycte pw: ellencte 
You have my permission to add/delete/change anything you want in this account, there is nothing that I need.  
Under the Manage Course Rosters you see a title "DRAFTING"  but it does not exist under the blue MY COURSES tab.  Same thing for "GREEN CONSTRUCTION".  There there is actually the complete opposite situation as well.  If you look under the blue MY COURSES tab - the course named Computer Concepts and Software Applications does not show under the Manage course rosters.  So something is not right - these courses should not exist under one menu and not the other.   

We need to get to the root cause of the issue.  Let me know what I can do to help.

**Comment by bguerrettaz** [comment]
Hi - I conducted the tests with your account and was successfully able to
use the delete course outline link to delete the course outlines and  these
are no longer showing up in any of the locations.  Can you please test the
same thing on your end to confirm?

My assumption is, anyone that tried to cleanup those course outlines in the
past , before the logic was in place had these issues, but I'm not able to
emulate those issues on my end.  When you test this right now, are you
still having issues with them still showing up in those locations?

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake,
1.  Question:  Have made some recent changes to correct this going forward?   

2.  I still see the issue in my account where there is a course named Culinary Arts under the blue MY COURSES tab, but I am unable to assign students to this course.   Why is this?

3.  Is our only solution moving forward to continue to send you teachers who have course outlines that linger in the extra menus?

4.  Here is one from the weekend:   James Rupp needs these four removed from his account
Animal Plant and Soil Science -  Revised
Farm Business Management
Revised Business
Small Animal Care & Management

**Comment by mnichols13** [comment]
Blake,
When can you clean up James Rupp's old course outline titles?  Is tonight possible?

**Comment by bguerrettaz** [comment]
To answer your questions below:
1. No code changes recently made to this
2. My assumption with this is that these are 'lingering' courses out there
from before this change was added in the code (not sure when this was
done).  If you delete a course outline today, it cleans it up
appropriately, but if there are lingering courses out there, there is no
good way to clean this up (other than having me manually delete them from
the database).  I could create that interface on the admin console, if this
is of interest to you.
3.  Answered above.
4.  I will clean this up tonight.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
That request for the teacher is complete.

**Comment by mnichols13** [comment]
What is the estimate for adding the interface on the admin console?

**Comment by mnichols13** [comment]
Blake, 
Please provide an estimate on adding the the interface on the admin console.

**Comment by bguerrettaz** [comment]
Hi - it would be 6-8 hours for adding this interface to the admin console.

Thanks,
Blake

**Comment by mnichols13** [comment]
Blake,
Please proceed with this work to add the interface to the admin console.

**Comment by mnichols13** [comment]
What is the status of this work?

**Comment by bguerrettaz** [comment]
I've sent a few messages regarding this work, have you not been seeing all
of my replies?  This is my last one:

Below, I've found 3 examples, please verify that for each teacher, the
course outlines listed would be correct for cleaning up.

Chad Cook - Username: ccook@lamonte.k12.mo.us
Courses that need deleted:
ag science 1 (woods)
Agricultural Science I
Contest
Hunter's Safety
JH Agriculture
JH Woods
SHOP

Ryan Ellis - Username: Ryan_Ellis
Courses that need deleted:
Animal Sciene I : Small Animals
Floriculture
Introduction to Agriculture

Brad Hartweg - Username: bradhartweg
Courses that need deleted:
Agricultural Business Management
Agricultural Leadership
Agricultural Machinery Service 2016
Agricultural Mechanics and Technology 2016
Agricultural Metal Fabrication 2016
Agricultural Sales and Marketing
Agronomy
Animal Science
Introduction to the Agricultural Industry 2016
Natural Resources Management and Conservation 2014

Once these are validated I can finalize the query.

**Comment by mnichols13** [comment]
This is the first that I saw it..  Do you see it posted twice above or just once?  

Let me take a look at this now..

**Comment by bguerrettaz** [comment]
I only see it posted once.  Thanks for taking a look.  If you validate
those are correct, then I can wrap up the rest by EOW.

**Comment by mnichols13** [comment]
I can confirm that these are course outlines that would need to be cleaned up.  Thank you.

**Comment by bguerrettaz** [comment]
Hi - I have completed the development of this.  I have placed this
interface in the edit teacher area on the admin side:

[image: image.png]

Titled: 'Cleanup Course Outlines'

Once you click on that and confirm, it will cleanup the courses and give
you the message in red.

Can you please test the three I sent you through this interface to confirm
it works correctly?

Thanks,
Blake

**Comment by mnichols13** [comment]
I checked Ryan Ellis.  I forgot to write down what he had before I cleaned them up, but here are the results:
![image](https://user-images.githubusercontent.com/5790342/72454442-7cf81580-3786-11ea-82e1-69a75825eba1.png)

In conclusion:
Any course titles that are listed under  MY COURSE OUTLINES should show up in all other menus.
As you can see something is not quite right.  I am not going to proceed with any other accounts yet, until you can take a look.

**Comment by bguerrettaz** [comment]
Hmm, where I'm struggling with this is, I've done this cleanup many times
over the years in the same way, and now I've just taken that method and
automated it from an interface so you would have the ability to do it ad
hoc and by teacher without needing me to do it.

What you show here is evident, the code in those different locations pulls
the data in many different ways from different locations.  I'll take a look
into this, but just wanted everyone to know that my intention with this new
interface was to automate what I've been asked to do many times and I'm not
sure how this situation is different.

More to come.

Blake

**Comment by bguerrettaz** [comment]
As I look into your results, that situation seems like an outlier.  To
break it down, there are two tables where this data is pulled from, they
should be in sync ideally, they aren't in a lot of cases.  The 'reliable'
table we've always used to base our cleanup on has been tblCourseOutline.
The other table, tblQuizClass, is the secondary table that generally needs
cleaned up.

In the analysis I'm seeing, it only happens ~500 times out of all of the
teachers in your system where tblCourseOutline actually has more courses
than tblQuizClass.  More often, tblQuizClass has many more because in the
past it wasn't cleaned up correctly.  That's what I've implemented, a
cleanup for that.  What you're seeing is going the other direction, which I
didn't account for (not sure we should since the record occurrence is so
small, at least in my data pull).

Can we do your testing on one other teacher in that same graph/excel
format?  Don't clean this teacher up through the new interface, if you
could, just do the analysis you did on Brad Hartweg.  I'm showing that he
needs the following courses cleaned up:

Agricultural Business Management
Agricultural Construction and Technology 2016
Agricultural Leadership
Agricultural Machinery Service 2016
Agricultural Mechanics and Technology 2016
Agricultural Metal Fabrication 2016
Agricultural Sales and Marketing
Agronomy
Animal Science
Introduction to the Agricultural Industry 2016
Natural Resources Management and Conservation 2014

This teacher doesn't have the same situation as the prior one we've
tested.  So what I'm looking for is if we were to cleanup this teacher,
what would your analysis look like.

Does all of that make sense?  Because there are so many different code
bases doing the same/similar thing, this is an extremely messy problem, but
bad data or data quality is always messy.

Thanks,
Blake

**Comment by mnichols13** [comment]
I agree this is messy, and of course this teacher is unique because he has no current students and no quizzes..   but I think this is what you are looking for. 
![image](https://user-images.githubusercontent.com/5790342/72467702-1d5b3380-37a1-11ea-8577-d4aae047e433.png)

**Comment by mnichols13** [comment]
I went ahead and did the matrix for Chad Cook as well.   

![image](https://user-images.githubusercontent.com/5790342/72475353-57800180-37b0-11ea-84f8-c739dcd1e8bb.png)

**Comment by bguerrettaz** [comment]
Thanks - ok both of the last two teachers play out correctly.  For Brad,
the traditional cleanup (the one I've already implemented) would work
fine.  For Chad, he would need both the traditional way and the way I've
captured in a secondary query.  As far as the first teacher Ryan, we may
need to manually change it as his profile is jacked a bit by looking at
your chart.

Do you want to test a few more teachers out in chart format and then
compare them against what my two cleanup methods would look like or do you
feel comfortable since two of them play out?  If you'd like to pick 3-4
more, I'm happy to run them through the methods without actually making the
changes.

I have a feeling that no matter what we do, not all teachers will be
perfect, just because of bad data.

Please let me know what you think.

Blake

**Comment by mnichols13** [comment]
I wouldn't mind picking out 2 or 3 more to see how they play out.

**Comment by bguerrettaz** [comment]
Ok, agreed, I'd feel better about these changes if you wouldn't mind.
Please let me know once you've had a chance to do that.

Blake

**Comment by mnichols13** [comment]
Are you able to identify these for me?  I really don't have any way to search this kind of thing.

**Comment by bguerrettaz** [comment]
Good point :) Let me find a few

**Comment by bguerrettaz** [comment]
Here are three:

6900 Tammy Ravel
4180 Matthew Bax
1908 Ag Dept Uhlenkamp & Brandt

**Comment by mnichols13** [comment]
I have completed these three additional accounts.  In the process, I realized that I needed to add one more thing.  The data is different on the Edit Quiz page one and the Edit Quiz - parameters page.  So I went back and updated the other ones we looked and then I moved some columns.. Just wanted to give you a heads up on that.  
[CLEANup.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/4077884/CLEANup.xlsx)

**Comment by mnichols13** [comment]
Any update on this project?

**Comment by bguerrettaz** [comment]
Hi - I have ran the simulated code against the accounts in the spreadsheet.  I've highlighted all of those that would be deleted (cleaned up) in yellow. 
[CLEANup.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/4109230/CLEANup.xlsx)

I'm not sure we'll get to a perfect state, but this looks like its much closer.

Please let me know what you think.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Sent an update on this issue, sending this to make sure you get it.

Blake

**Comment by mnichols13** [comment]
got it!  I'll take a look

**Comment by mnichols13** [comment]
The problem I see with this is that there are a few highlighted courses that are in the MY COURSES column.  We cannot delete anything that has a valid course outline. 
For example:  Ryan Ellis - Intro to AG should NOT be cleaned up
Chad Cook - Exploratory AG should NOT be cleaned up
Tammy Revel -nothing highlighted should be cleaned up
Matthew Bax - Copy of Agricultural Science I (10/28/2010 4:13) - should NOT be cleaned up

In all of these cases, the exact opposite needs to happen, they need to actually show up in the other menus and they do not.  

Ughhh this is such a mess..  


Copy of   Agricultural Science I (10/28/2010 4:13)
--




Copy of   Agricultural Science I (10/28/2010 4:13)
--

**Comment by bguerrettaz** [comment]
Yes, agreed, the data is a complete mess and I'm actually at a loss for how
to programmatically do this.

It sucks to say that we spent quite a bit of time on this, but I feel that
we could spend MUCH more time on this to try to get close to right, and
with this data, it may be better to clean these up one off like we have
been doing.

Again, I understand its not ideal or good, I just don't know how to move
forward with this...

Blake

**Comment by mnichols13** [comment]
let me talk to Dan and we'll try and have a decision on how to proceed early next week

**Comment by bguerrettaz** [comment]
Sounds good, thanks.

**Comment by mnichols13** [comment]
If I understand correctly we could use the clean up method that you have created, it just may not catch everything that needs to be cleaned up.  Is this right?   We know for sure the 2nd method does not work.    I guess we will continue to deal with the ones that need a manual cleanup through Github communication.  

My remaining concern is these course outlines that were created, but you cannot see them in the menus.  This is a separate issue in my opinion.  These are new course outlines created in 2.0 that for some reason teachers cannot assign materials to.   

Agreed?

**Comment by bguerrettaz** [comment]
I agree, I believe that's a separate issue.  I can implement the cleanup
method as we've tested, knowing there are some gaps, if we're all in
agreement?

**Comment by mnichols13** [comment]
yes as long as its the original method.. we don't want good course outlines deleted.

**Comment by bguerrettaz** [comment]
Sorry, what do you mean original method?  Do you mean the way I was doing
it manually?  That is the way its currently being done in the new interface
on the admin console.

**Comment by mnichols13** [comment]
Yes that sounds correct - the new interface that you created.  realizing there are some gaps..

**Comment by bguerrettaz** [comment]
Ok, then its good to go, I've already deployed that method to that
interface/link in admin under Edit Teachers.
