### ISSUE TITLE
Add New Library to Free Trial Request Form

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#266]
We need you to add a new library to the Free Trial Request at http://mycaert.com/free-trial-request.asp. The new library is Next Gen-Plant Science. It should appear immediately after the Natural Resources and Environmental Systems library.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by mnichols13** [comment]
We need you to add a new library to the Free Trial Request at http://mycaert.com/free-trial-request.asp. The new library is Next Gen-Animal Science/Animal Biology. It should appear immediately after the Next Gen-Plant Science - Plant Biology library.

**Comment by dpentony** [comment]
@bguerrettaz - please hold off on this request for now. FCAE can't make up their mind what they want to call the library.

**Comment by dpentony** [comment]
Please proceed with Mindy's original request. That is: We need you to add a new library to the Free Trial Request at http://mycaert.com/free-trial-request.asp. The new library is Next Gen-Animal Science - Animal Biology. It should appear immediately after the Next Gen-Plant Science - Plant Biology library.

**Comment by bguerrettaz** [comment]
Hi - this is complete.

Thanks,
Blake

**Comment by mnichols13** [comment]
thanks looks good.

**Comment by mnichols13** [comment]
Please update these three available lesson libraries in the free trial section.  
Remove Agribusiness Management and replace with Agribusiness (5E outline)
Remove Middle School Library/Agricultural Literacy and replace with Middle School Agriscience (5E Outline)
Remove Horticulture and replace with Horticulture (5E Outline)

**Comment by mnichols13** [comment]
@bguerrettaz

**Comment by bguerrettaz** [comment]
These are updated and complete.   Please test and confirm.

Blake

**Comment by mnichols13** [comment]
looks good.
