### ISSUE TITLE
Changing the way libraries appear in drop down

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#267]
Currently when adding a question the lesson libraries are alphabetized by the library code rather than the library name.   Our new lesson libraries Next Gen Animal and Next Gen Plant Sciences have the codes NGAS and NGPS respectively.   They are mixed in with the Nevada and North Carolina libraries.   

How much work would it be to change the way these appear so that they alphabetize by library name instead?

**Comment by mnichols13** [comment]
![image](https://user-images.githubusercontent.com/5790342/35245190-576f2dae-ff88-11e7-9027-93d892cffa3d.png)

**Comment by bguerrettaz** [comment]
Just a half-hour to an hour.

Blake

**Comment by dpentony** [comment]
Please proceed.

**Comment by mnichols13** [comment]
thanks, looks good
