### ISSUE TITLE
Copying a course outline Indiana only? - TITLE not changing on all pages - 

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#268]
I had a tutorial with an Indiana teacher this morning.   We copied a state course outline over and changed the name taking out the "copy of state course outline" portion.  When we did this, it did not change the name of the course under the following pages:
Manage course rosters
Add a Student
Assign materials

We were unable to assign materials because even though we added students under the new course name, the system did not recognize that we had students.  It was looking for the old name.    This made the course outline useless. 

This needs to be fixed ASAP.

When I tried to replicate this in IL I did not have the same issue, everything worked fine.

**Comment by bguerrettaz** [comment]
Hi,

I tested this with my user account in IN and changed the name and DID see
the changes in the three pages you mentioned once I copied.

I wasn't able to recreate the issue you were seeing.  I also looked in the
code and didn't find anything specific to Indiana.

If you're able to recreate, can you please tell me which username/password
and the steps you took so I can recreate?

Thanks,
Blake

**Comment by mnichols13** [comment]
Laura Searcy  - Cascade Indiana 
course outline: Indiana Power Structures

**Comment by bguerrettaz** [comment]
Ok, I was finally able to recreate this issue and pin it down to a reason.
It comes down to a special character.  The course outline that you are
trying to copy contains an ampersand (&), which is considered a special
character and is breaking the code.

All other course outlines that I copy and rename work correctly.

We have two options:

- Change all of the code to account for this special character
- Change the name of the course outline to remove that special character

Please let me know how you'd like me to proceed.

Thanks,
Blake

**Comment by mnichols13** [comment]
Sounds like it would be easier to change the course outline name

**Comment by bguerrettaz** [comment]
Yes I agree.

**Comment by dpentony** [comment]
@bguerrettaz - is there an easy way for you to change the name of the course outline on the back end? Unlike in a teacher profile, there is no way to rename a course outline via the state admin. The only way to do it would be to recreate the entire outline without the ampersand in the title.

What would it take to add the renaming of an outline functionality to the state admin side?

**Comment by bguerrettaz** [comment]
Yes, I can change the name of the course outline in the database.  Should I
just replace '&' with 'and'?

Regarding your question about renaming course outlines on the admin side, I
can put in this functionality, but keep in mind that anyone that has copied
a course outline in the past would retain the same name, this renaming
functionality wouldn't change copied course outline names.  Just wanted you
to be aware.

Would this be on the state admin only or both state and global?

**Comment by dpentony** [comment]
Please replace the "&" with "and".

Thanks for making us aware of the the repercussions of the change. 

What's your estimate for adding the functionality to only state admins?

**Comment by bguerrettaz** [comment]
Probably around 3-5 hours.  I'd have to create a new page for this and
update database entries.

Blake

**Comment by dpentony** [comment]
OK. Please make the change as soon as possible in the database to solve the problem with the teacher in Indiana. Then, please move on to adding the functionality to state admins.

**Comment by bguerrettaz** [comment]
Thanks. I had the query already written for the change to the course
outline name, just waiting for confirmation from you.  That is complete.

I'll work on the state admin capabilities.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
This change is complete on the state admin side.

Please test and confirm functionality.

Thanks,
Blake
