### ISSUE TITLE
Problem Adding Test Questions via State Admin

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#269]
I created a test via the DE State Admin called DE Plant Science I Example. After creating the test, I am unable to enter in any questions whether I pick them from the CAERT question bank or try to key in my own. The error message I get is:

Please advise. I have a conference call on February 13 where I need to show how this works.

Microsoft OLE DB Provider for ODBC Drivers error '80004005'

[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

/admin/csat/DE/StateConnection.asp, line 8

**Comment by dpentony** [comment]
It appears the question I added did get saved even though I got the error message. However, still no luck in adding one from the CAERT question bank.

**Comment by bguerrettaz** [comment]
This was an issue with the connection parameters for the state of DE.
This should be resolved now, please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
