### ISSUE TITLE
Student login report not working

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#272]
Under the MY STUDENTS tab teachers have an option to run a student login report.  It does not seem to be working.  We get the following error instead.

![image](https://user-images.githubusercontent.com/5790342/38373915-007a5ac8-38b8-11e8-84dc-08f5f50deaa0.png)

**Comment by bguerrettaz** [comment]
Brian - thoughts?

**Comment by dpentony** [comment]
Yes, it is happening under other teacher profiles.

**Comment by mnichols13** [comment]
Can I get an update on this?  Any progress?

**Comment by bguerrettaz** [comment]
Brian - any thoughts on the timeout?

**Comment by BrianPeterlin** [comment]
Another option is to put in the code to buffer the results out, i think we did that on other reports

**Comment by dpentony** [comment]
Brian, what are you doing to get this working?
