### ISSUE TITLE
Deleting/Hiding Old IL Learning Standards

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#273]
Note: This kind of relates to issue 167 which we never pursued. It is coming at the request of ISBE:

When using the "align question" feature in CSAT, the old IL Learning Standards show up at the top of the page and the user has to scroll down to view/align to CCSS and NGSS.
 
A lot of old math, science, etc. standards still remain in that section.  Can we remove math, science, ELA but keep the Social Science, Fine Arts, etc?  Can we move the alignment to these standards to lower on the page - below CCSS and NGSS?

An estimate on the number of hours involved would help us in responding to ISBE.

**Comment by bguerrettaz** [comment]
Would this be a one-time removal or is this something you'd want to be able
to administer on the admin console?

**Comment by dpentony** [comment]
One time removal or they can be hidden.

**Comment by bguerrettaz** [comment]
If its for removal from that drop down only on the admin side for maintain
alignments, 2 hours should cover it.

Here's what I'm understanding:

- Remove Math, Science and ELA only from the admin maintain IL alignments
page

Is that correct?

**Comment by dpentony** [comment]
That is not correct. It is on the user side. When an IL user adds a test question, they have the ability to align to a state standard. This is where we want to delete or hide the old Il standards from the pull down menu.

**Comment by bguerrettaz** [comment]
Got it, so you're referring to only this page:

![image](https://user-images.githubusercontent.com/5695475/38739630-13d4bcdc-3efb-11e8-892a-bb7b75f66b3d.png)

**Comment by dpentony** [comment]
Please wait. I have to run it by FCAE first.

**Comment by bguerrettaz** [comment]
No problem
