### ISSUE TITLE
Extend IL CTE Subscription

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#275]
IL has paid for an extension of the subscription for all CTE teachers to until 4/1/2019. We need to change the expiration dates on all CTE (non-ag) accounts in IL from 7/1/201 to 4/1/2019. All expiration dates for the lessons plans, Eunits, and CSAT components that the CTE subscribers currently have access to also need to be changed to 4/1/2019.

Also, we need to add access by all CTE teachers to the lessons, Eunits, and CSAT for two new libraries. These two libraries are Web and App Development and Cyber Security. Their expiration dates should be the same as all the other - 4/1/2019.

**Comment by bguerrettaz** [comment]
This has been completed.  This is by far the most complicated upgrade, especially when adding new libraries, so please spot check accordingly.

Also, I added Cyber Security, but everyone already had Web and App Development.

Thanks,
Blake

**Comment by dpentony** [comment]
IL has paid for an extension of the subscription for all CTE teachers to until 3/31/2020. We need to change the expiration dates on all CTE (non-ag) accounts in IL from  4/1/2019 to 3/31/2020. All expiration dates for the lessons plans, Eunits, and CSAT components that the CTE subscribers currently have access to also need to be changed to 3/31/2020.

**Comment by dpentony** [comment]
@bguerrettaz - would you please hold off on this until I give further notice? ISBE is playing games with the new contract. I do not want to incur any charges from you until I have a signed contract. It may be late March when I give you the go ahead and then we would need you to update it within a couple of days in advance of the April 1 expiration.

**Comment by bguerrettaz** [comment]
Sounds good, just let me know.

Blake

**Comment by dpentony** [comment]
Thanks. I have a meeting on March 26 at ISBE where I hope to get this issue resolved. I apologize for the short timeline. It will only give you a few days to update the subscription before it expires April 1.

**Comment by dpentony** [comment]
@bguerrettaz - at this point, we are going to update the CTE subscription for 3 months until 7.1.2019. Please proceed as described below. Please do this before the current subscription expires on 4.1.2019.

IL has paid for an extension of the subscription for all CTE teachers to until 7.1.2019. We need to change the expiration dates on all CTE (non-ag) accounts in IL from 4/1/2019 7/1/2019. All expiration dates for the lessons plans, Eunits, and CSAT components that the CTE subscribers currently have access to also need to be changed to 7.1.2019.

**Comment by bguerrettaz** [comment]
Good morning - this work has been completed.  Please spot check and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
We have almost 350 teachers that have a master de-activation date of 07/01/2021.  I'm not sure how this happened, but because their master de-activation date was wrong, now their lesson libraries did not get updated and are still set at 04/01/2019, so now they cannot see their materials.   Please make the needed change on these teachers.

**Comment by mnichols13** [comment]
We have almost 350 teachers that have a master de-activation date of 07/01/2021. I'm not sure how this happened, but because their master de-activation date was wrong, now their lesson libraries did not get updated and are still set at 04/01/2019, so now they cannot see their materials. Please make the needed change on these teachers.

**Comment by mnichols13** [comment]
Blake any update on this?

**Comment by bguerrettaz** [comment]
Want to make sure, do you want to leave their master deactivation dates at
0701/2021 or have it changed to 04/01/2019?  I found 291 teachers.

**Comment by mnichols13** [comment]
neither 
The master deactivate date and the lesson libraries should both be 07/01/2019

**Comment by bguerrettaz** [comment]
This is complete.  Thanks

**Comment by mnichols13** [comment]
There are another 44 teachers with a master deactivate date of 07/01/2021 - these are AG teachers that should have a master deactivate date of 06/1/2021 to match their lesson libraries.  This one is not as urgent, as they can see their materials, however they will not update properly when the time comes if we don't get these fixed.

**Comment by mnichols13** [comment]
Do we have an update on this?

**Comment by bguerrettaz** [comment]
This is complete.

Thanks,
Blake

**Comment by mnichols13** [comment]
When a new teacher is added for IL CTE, they are not getting the two newest lesson libraries:  
WEB and APP development
Cybersecurity

These have to be manually added.  Can you take a look?

**Comment by dpentony** [comment]
@mnichols13 - we do this. I will call shortly to discuss.

@bguerrettaz - please also change the master deactivate and those for all current libraries to 4/1/2021. ISBE has paid for a CTE subscription until then.

**Comment by bguerrettaz** [comment]
As I wrap this up, I want to confirm that you want all IL, CTE teachers
libraries (Lesson Plans, eUnits and CSAT) deactivate date updated to
4/1/2021.  Teachers master date as well?

**Comment by dpentony** [comment]
Correct

**Comment by bguerrettaz** [comment]
Thanks for the confirmation.  I have ran everything to make these updates.
Please spot check to confirm.

Blake

**Comment by mnichols13** [comment]
Not a huge deal, 37 teachers did not update.  I wonder if there is a reason why?  

[didnotupdate.xlsx](https://github.com/MyCaert/Issues-Enhancements/files/3339686/didnotupdate.xlsx)

**Comment by mnichols13** [comment]
I found 37 teachers, but they look to be all AG teachers with the wrong master date.  I'm thinking we need to just fix these manually.   Otherwise everything looks good with the update.
