### ISSUE TITLE
Problem Editing Illinois School

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#277]
Via the global admin, I am trying to edit a school. The school is Liberty Middle School. When I click on the Edit link, I get the following error message. Please advise.

SELECT State, RegionID, SectionID, Region, [Section] FROM tblStateFilter WHERE (State = 'IL') AND (Region = 'All Regions') AND (Section = 'All Sections')
ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/School/EditSchool.asp, line 48

**Comment by dpentony** [comment]
Any progress on this?

**Comment by bguerrettaz** [comment]
Yes, I worked on this last night, but wanted to finish testing this
morning.  The reason this was failing was there was no record in the
database for 'All Regions' and 'All Sections', like other states have.

I have corrected the issue, please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment]
Looks good. Thanks.
