### ISSUE TITLE
HIGH PRIORITY - Unauthorized CSAT Access

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#28]
While updating Mike McConnell's account in WY, we noticed he is getting access to CSAT when he should not be. His access to CSAT expired in December 2012. However, we noticed that he was giving quizzes as recently as last month even though the expiration dates in his CSAT fields were set for December 2012.

We assume the expiration dates for the CSAT components override the radial button to "Allow CSAT Access". So, even though the Allow Access radial button is checked, the teacher should not have access to CSAT since his access expired in December 2012. Regardless, we were able to create quizzes and edit quizzes.

As a further test, we changed the radial button to Prohibit CSAT Access. After doing so, all of the dates in the CSAT fields were erased. So, we lost his history of the dates he formerly had access to CSAT. 

Despite all of the changes, it still appears he is able to access old tests and to make changes to them. Since he is not paying for CSAT access, we do not want him to have access to these old tests.

**Comment by dpentony** [comment]
I am not sure if this previous issues relates to the current problem, but we have discovered a couple of cases where teachers are getting access to lesson plans even after the expiration date on the libraries has passed. Obviously, this is not good for our botton line!

Two examples:

1. Troy Talford in WI - His access to the Biotech library expired on 1/1/2015. However, he can still access the lesson plans. His Eunit access expired on the same date but he cannot access them.

2. Arica Schlough in WI - Same situation. Her access to three lesson libraries expired on 1/1/2015. However, she can still access the lessons in all three libraries but she cannot access the Eunits which also expired on that date.

While you are at it, can you change the text that appears in the box when they click on a component that has expired. An example is when either of the above teachers clicks on the Eunits. The box that comes up says: 

![image](https://cloud.githubusercontent.com/assets/5790325/5761226/b2c2b5ee-9c9f-11e4-8ae4-8ffc2b2b01bc.png)

That is not good English. It sounds like we are from China. We need that message to be: "You are no  longer licensed for Eunits/Lessons."

**Comment by bguerrettaz** [comment]
I'm looking into this issue, looks like it could be two different issues,
I'll update when I get further into it.

Blake

**Comment by bguerrettaz** [comment]
Here's what I'm seeing when I click on the course outline for
Biootechnology for Talford:

[image: Inline image 1]

Same for the other teacher.

Do you mean, you want this screen to be restricted from the start if they
don't have valid subscriptions?

[image: Inline image 3]

I have also fixed that popup message, but keep in mind this is state
specific (you can tell by looking at the URL and it has a state identifier
in it), so this is complete just for WI.

Blake

**Comment by mnichols13** [comment]
Troy Talford should not see Biotechnology at all on his homescreen.  His access is expired...

**Comment by bguerrettaz** [comment]
Ok, I'll have to write code around that.  It looks like that's never been
accounted for from the home screen's perspective.

**Comment by mnichols13** [comment]
What?  thats crazy... when a teacher has a library expired it should not show up.  This is the way it has always been.  Do we need to talk on the phone?

**Comment by bguerrettaz** [comment]
Let's try this, can you send me a user that works correctly and I'll
compare the two.

**Comment by mnichols13** [comment]
Beth Kolodzinksi - WI 
She has five lesson libraries checked on the ADMIN page
Two are expired:  Agrsicence Revised and Biological Science in AG (expired 1/1/2015, 12/1/2013)
Three are active:  Horticulture, Animal Plants & Soils, Adv Life Science (paid to 2/1/2016)

On her homepage she can only view the three active libraries

**Comment by bguerrettaz** [comment]
Ok, I had to really dig to find out what is happening here.

There is no date check for the home page, it simply looks at the lesson
plan list that is attached to a teachers profile and displays all of those
CD's.  This lesson plan list is only updated from the admin console.  To
test this theory, I went into Taldrop's profile, simply hit save and then
went back into his profile and Biotechnology was gone.

So the unless someone goes into a teachers profile all the time and hits
save, nothing is updating that Lesson Plan list which means they'll have
access to those libraries until someone does go into his profile on the
admin side and hits SAVE.

This is clearly a hole in logic that has been missed.

I suggest that we put login in place on the homepages (there are two
different code sets for the home page) and put date checks into make sure
that they are not getting access to expired CD's.

You can test this theory with another teacher that would have just had one
expire.  First login in as them, see if the expired CD is listed, if it is,
then go into the admin console and hit save.  That expired CD will now be
gone from their homepage.

Please let me know what you'd like me to do.

Blake

**Comment by dpentony** [comment]
What is your estimate for adding the necessary logic?

**Comment by bguerrettaz** [comment]
Since I've already spent some time researching the issue and testing
different avenues, I'd say to get it added would be 3-4 hours.

**Comment by dpentony** [comment]
Please proceed

**Comment by dpentony** [comment]
Can yo provide an update on this item?

**Comment by bguerrettaz** [comment]
Yes, I worked on this first since it seemed highest priority.

This issue is resolved.

Please test and confirm.

Thanks,
Blake

Hours: 4

**Comment by bguerrettaz** [comment]
What is the next in priority out of the list?

**Comment by mnichols13** [comment]
looks good for Beth and Troy... I'm assuming that since their accounts look right that it is fixed.
