### ISSUE TITLE
Excel Report for IL CTE Users

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#280]
Can you provide me with an Excel file listing all active IL CTE users? Essentially, I need a file that lists the info when you go to Edit/Delete Teacher and choose IL. However, I only need those with a CTE focus and whose status is active.

We cannot do this ourselves. When we try, the page only lists a small portion of the teachers. There is no way to export the entire file to Excel.

Please advise on your timeline for this.

**Comment by bguerrettaz** [comment]
Hi,

Please find the extract you requested attached.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Thank you!

**Comment by dpentony** [comment]
Thanks.
