### ISSUE TITLE
Add Fields to Maintain/Edit Teacher for IL

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#282]
FCAE has contacted us about wanting to include more information on the IL Ag and CTE teachers as new teachers are added or existing ones are edited. Specifically, this information would require the addition of several new fields when adding or maintaining a teacher. These new fields are:

Change subject to a drop down by adding additional fields to replace Ag or CTE:  
> Agriculture
> Business
> Family/Consumer Science
> Health
> Industrial Technology
> Administrator
> College
> University
> K-8 Teacher
> Other
> 
> -Add Grade with drop down to 
>  -PreK-4
>  -5-6
>  -7-8
>  -9-12
>  -13-14
>  -13-16
>  -All grade levels

1. What is your estimate as to how many hours thos would take.

2. We do not have the information for existing teachers and would be adding it as we gather it. Right now, teachers are only classified as Ag or CTE. Would the addition of these new fields impact how they are currently classified? We would not want it to.

**Comment by bguerrettaz** [comment]
Currently there is a subject field and a grade field, should those be
replaced with those drop downs?

I would imagine, we could leave the Ag or CTE classifications untouched and
just edit the subject and grade fields on edit and add teacher screens.

Am I understanding that correctly?

Thanks,
Blake

**Comment by dpentony** [comment]
Your understanding is correct at this point.

**Comment by bguerrettaz** [comment]
Ok, 3-5 hours for both the add and edit teacher pages.

**Comment by bguerrettaz** [comment]
Definitely.

**Comment by dpentony** [comment]
FCAE has decided that they do not want to do this, so I'm closing the issue.

**Comment by dpentony** [comment]
FCAE has asked again for an estimate on adding several fields to the state admin pages for IL each teacher. See below:

State login page, I would like to see these changes:

-Change subject to a dropdown by:  Primary
Agriculture
Business
Family/Consumer Science
Health
Industrial Technology
Guidance Counselor
Administrator
College
University
K-8 Teacher
Other

-Change subject to a dropdown by:  Secondary
Agriculture
Business
Family/Consumer Science
Health
Industrial Technology
Guidance Counselor
Administrator
College
University
K-8 Teacher
Other


-Grade with dropdown and change to 
 -PreK-4
 -5-6
 -7-8
 -9-12
 -13-14
 -13-16
 -All grade levels

- EFE Number with dropdown box:
10
--
20
30
40
50
60
65
70
90
100
110
120
130
140
150
160
170
185
190
200
220
230
240
250
265
280
290
300
310
320
330
340
350
370
380
390
400
410
425
430
450
460
470
480
490
495
500
520
525
535
540
550
560
570
580
590

- Update box showing date and time of last update to page.


- Icon to download the database anytime to Excel.

**Comment by bguerrettaz** [comment]
Comments below in yellow.

On Tue, Mar 5, 2019 at 9:21 AM dpentony <notifications@github.com> wrote:

> FCAE has asked again for an estimate on adding several fields to the state
> admin pages for IL each teacher. See below:
>
> State login page, I would like to see these changes:
>
> -Change subject to a dropdown by: Primary
> Agriculture
> Business
> Family/Consumer Science
> Health
> Industrial Technology
> Guidance Counselor
> Administrator
> College
> University
> K-8 Teacher
> Other
>
> -Change subject to a dropdown by: Secondary
> Agriculture
> Business
> Family/Consumer Science
> Health
> Industrial Technology
> Guidance Counselor
> Administrator
> College
> University
> K-8 Teacher
> Other
>
For the changes to subject field, add dropdowns and database field to
capture primary and secondary (repurpose current for primary) - 4-5 hours
