### ISSUE TITLE
Test Parameter - # of Views Allowed

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#283]
When you create a **NEW** quiz, there is a parameter to set the number of submissions, but not one to set the number of views by students. The number of student views is not a parameter you can set when first creating a quiz. See below:

![image](https://user-images.githubusercontent.com/5790325/48569608-d38a6b00-e8c7-11e8-8880-a4a1a580acc6.png)

However, when you go to Edit (Existing) Quiz>>Edit Quiz Parameters, this is the only location where you can set the number of student views. See below:

![image](https://user-images.githubusercontent.com/5790325/48569800-501d4980-e8c8-11e8-8942-ee533ddccdef.png)

What would it take to get the number of student views parameter to be included with those you set when you **FIRST** create a new quiz?

**Comment by dpentony** [comment]
Please proceed.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good
