### ISSUE TITLE
Alternate Titles for Same Library in Deifferent States

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#285]
ISBE is giving FCAE grief over the inclusion of the terms "Next Gen" in two libraries we've recently released - Next Gen Animal Biology and Next Gen Plant Biology. They have just asked us to simply title them Animal Biology and Plant Biology.

We've been advertising the libraries with the terms "Next Gen" in the title for a year. If we take it out now, teachers will not know what to look for on the trial request or order forms.

Illinois is the only state where the term Next Gen cannot appear. Is there any way to make those two libraries appear simply as Animal Biology and Plant Biology in Illinois when the teacher logs in, but in all other states the libraries would appear as Next Gen - Plant Biology and Next Gen - Animal Biology?

I realize we could create two totally new libraries with Next Gen in the title and upload the exact same lessons which we'd make available to teachers in other states, but I was hoping there was an easier way.

Please let me know our options.

**Comment by dpentony** [comment]
Have you been able to give this some thought?

**Comment by bguerrettaz** [comment]
Yes, unfortunately, I'm not sure how we would do that without changing all
of the pages that show the title of those libraries.  We would have to put
logic in, if this state, call it this, if all of these other states, call
it this.

We could do that, but I'm guessing it would be a large number of pages...

**Comment by dpentony** [comment]
Thanks. I will move them away from this possibility.
