### ISSUE TITLE
Information on student needed - amt of time on a test

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#286]

**Comment by mnichols13** [comment]
Marty Speth in WI wants to know how long a student had 3 tests opened on Feb 18th.  Is it possible to get this information?  He wants to prove to the parent that the student does not read the exam, but simply clicks answers.  
Course: Greenhouse crops
Student: John Sundberg
3 exam names: 
Understanding Hort GHouse
Horticulture Safety
Classifying and Naming Plants

**Comment by bguerrettaz** [comment]
Hi - I've taken a look through all of the tables and unfortunately we don't
capture that level of detail (neither when they start and when they finish
nor when each question is selected and submitted).

Let me know if you have any other questions.

Thanks,
Blake
