### ISSUE TITLE
Combine IL Ag & CTE Subscriptions

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#287]
FCAE is investigating giving every IL Ag & CTE teacher access to every Illinois library (both ag & CTE). Currently, the ag teachers have two accounts - one for the ag libraries and one for the CTE libraries. Whereas, all of the other CTE teachers have only one account that allows them access to only the non-ag CTE libraries. This is how the state wanted it set up when we originally did the IL state subscription.

1. Can the two current accounts for each ag teacher be combined into a single account under their current ag profile?

2. What happens if an ag teacher has students and tests under each profile? Could they be combined into a single ag profile?

3. Giving access for all teachers to every library in IL will mean that there landing page would list 30+ different libraries. Could a new landing page be designed so that upon logging in, it would show Ag and CTE? If they click on the Ag icon, a page would display all the ag libraries. Same goes if they clicked on the CTE icon.

Please give this thought and let me know of potential problems. Also, a new landing page might be affected by the possible addition of fields to the teacher profile page being considered under issue #282. Ultimately, we will need to get an estimate from you for the above work.

**Comment by bguerrettaz** [comment]
I think this could be done, but you would want to extensively test it after
I were to do the changes for test accounts.

It would be manual for the testing, I'd have to write some scripts/SQL for
the full lot of teachers if it tests out correctly.

Are we talking about two different (new) landing pages?

For the testing of merging accounts, I think it would be in the 8-15 hours
range (there's a lot to it, hence the broad range)
For the scripting/SQL for full merge of all teachers, 5-10 hours range
For each new landing page 6-8 hours, for each new page.  12-16 for 2 new
landing pages.

Thanks,
Blake
