### ISSUE TITLE
ADD 3 new libraries to ALL ILLINOIS AG teachers ** URGENT **

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#288]
**HOW SOON CAN YOU DO THIS?  The request was for it to happen today.  Would it be possible to get it done in the next 24 hours?** 

We need to add access for all ILLINOIS AG teachers to the lessons, Eunits, and CSAT for three new libraries. Their expiration dates should be the same as all the other - 6/1/2021. 
(NGPS) Plant Biology 5E
(NGAS) Animal Biology 5E
(HC5E) Horticulture 5E outline

thank you

**Comment by bguerrettaz** [comment]
Hi - I will work on this today and/or tonight.

Blake

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

**Comment by mnichols13** [comment]
It looks good.  Thanks for your quick action on this one.
