### ISSUE TITLE
Update New Jersey State Subscription on or before June 28, 2022

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#289]
The state subscription for New Jersey's ag teachers is set to expire on July 1. They have just renewed for a 3-year period. Please update all deactivate dates associated with the NJ teachers to 7/1/2022.

**Comment by dpentony** [comment]
What's the status on this request?

**Comment by bguerrettaz** [comment]
I have completed the query and test, but wanted to confirm before
executing, this is for all three libraries and the teacher profile, correct?

**Comment by dpentony** [comment]
There are 15 libraries, not just three. The account deactivate date and the deactivate dates for all 15 libraries (lessons. Eunits, & CSAT) need to be updated to 7/1/2022. See my profile under NJ. I updated it manually. The rest of the NJ teacher profiles should match mine.

**Comment by bguerrettaz** [comment]
Sorry, I didn't mean libraries, I meant lesson plans, eUnits and CSAT's.
I'll finish this up this morning.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
Blake, The new Plant Biology and Animal Biology lesson libraries were supposed to be added.   It looks like these two were missed, only 13 were updated rather than the 15 that Dan mentioned.

**Comment by dpentony** [comment]
What is the status on this?

**Comment by bguerrettaz** [comment]
Hi, this is complete.

**Comment by dpentony** [comment]
Looks good. Thanks.

**Comment by mnichols13** [comment]
looks good - thanks.
