### ISSUE TITLE
Adding Pre-existing students

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#290]
Aaron Heartt teaches at Mercer, IL. He is trying to add pre-existing students to his account. These are students who were already set up by another teacher (Michael Chausse) at his school. He chooses MY Students tab>>Add Students and then click the Yes button on Add Existing Student:

![image](https://user-images.githubusercontent.com/5790325/63288068-6f933980-c281-11e9-8121-8412a820eaf0.png)

He then selects and existing student (Kaelynn Boruff). However, when he chooses that student and it prepopulates the fields with the student's info, he gets a message saying the user name is already being used. Does that mean when the second teacher uses the pre-existing student button, they have to come up with a second user name for that student? I can't recall what the pre-existing student button is for is it does not allow their existing user name/password to be used. That would force the teacher to create a second set of logins for the student which is something they are trying to avoid. 

Any thoughts?

If there is no way around having to create a second set of logins for the student, we may need to consider hiding the pre-existing check box because it seems somewhat useless.

**Comment by bguerrettaz** [comment]
@Brian Peterlin <bpeterlin@cmiti.com>  - do you remember who built this
functionality?  Darrell?

I wanted to see if they remembered how it was supposed to function before
going into all of the code and reverse engineering.

Blake

**Comment by dpentony** [comment]
Any input from Brian on this?

**Comment by dpentony** [comment]
Since Brian never replied, I am closing this for now.
