### ISSUE TITLE
IL AG teachers cannot see Natural Resources library

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#291]
Blake,
It appears that there was a glitch when our IL AG teachers were updated this summer.   It is not across the board, but a pretty common problem.  When the teacher logs into their account,  they cannot see the Natural Resources library on their home page.  However, when we check the dates on their account everything looks good.  If we simply save and close this fixes the problem.   One example that you could look at is Jacalyn Meisner at Blue Ridge HS.   Please take a look and see what we can do to fix this for ALL teachers.   Can we do an update without changing dates or libraries?  Do you have another idea?

**Comment by mnichols13** [comment]
Now I have a teacher that from the admin page looks totally normal and updated.  When she logs in instead she has no Natural Resources, no Physical Applications in AG and two buttons for the new Hort library.  This is crazy Jennifer McFadden in IL
![McFadden](https://user-images.githubusercontent.com/5790342/64210955-43bfa880-ce6a-11e9-9089-39d1ad9c4157.JPG)

**Comment by mnichols13** [comment]
also have another teacher with no Natural Resources or Physical Applications in AG.  Jennifer Waters

**Comment by bguerrettaz** [comment]
Hi - I was able to hunt down the issue.  There were 247 teachers with
duplicates in their library list on their teacher record in the database.

I had to write scripts to correct all of these.  I'm not sure how two/three
libraries were being duplicated, but my guess is that those libraries were
manually added before I bulk added?

Either way, I backed up the teacher table and made all of the changes.  Can
you please confirm that this resolves the issues and if not, which one's
remain?

Thanks,
Blake

**Comment by mnichols13** [comment]
I didn't mean to confuse the issue with the duplicate libraries.   Do you think this fixed the issue with the Natural Resources and Physical Science libraries being missing?  

I did check the three teachers mentioned in this post and they all look correct, however it sounded like you were more focused on the duplicates so I wanted to be sure that both issues were addressed.   
Unfortunately we don't know if a teacher has an issue until they contact us with missing libraries, so these three are the only ones I can check at this point.

**Comment by bguerrettaz** [comment]
Yes, I think this accomplished both issues, I tested for both.  When I
removed the dupes, they went away and the missing libraries were shown.  I
think it has to do with how the dupes were interpreted in code.

**Comment by mnichols13** [comment]
ok, so far I have spot checked 8- 10 teachers and they all looked good.  Thank you for your quick action on this.  If we hear of others, I'll reopen.
