### ISSUE TITLE
Student quizzes not showing up - two locations

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#292]
Kevin Garling, Indiana teacher has several quizzes that do not show in two menus, one for the student and then one on the teacher page.   

When (some) students login to their home page and click the available quizzes they do not show up.  If the student clicks into the calendar on list view, they show up.  

When Kevin (teacher) chooses the Edit Quiz menu and selects the appropriate course outline, nothing shows up under this page.  If you page through "all" course outlines you can locate them and see them.  Why is the sort not working? 

Course outline:  Landscape Mgmt 19: 
Quiz names: 
 **Land 2019 quiz over 107 an 108**
**Land 2019 small hand tools** 
One student who cannot see the quiz: Haley Alexander
One student who can see the quiz:  Aa aaGarling (test student put in by me)

Course outline:  Horticulture 19
Quiz names: 
Hort poinsetta 2019
2019 Hort poinsetta 
One student who cannot see the quiz: Trinity Anderson
One student who can see the quiz:  Aa aaGarling (test student put in by me)

Thanks in advance for digging through his account.   I encouraged him to clean up old course outlines and such.  I will be listing the ones to delete in the other github post.

**Comment by bguerrettaz** [comment]
I 'think' I have this issue resolved.  His profile is a mess, not sure how
that all happened, but it took a while to dig through all of the
issues/code.

Can you please test again and see what you find?

Thanks,
Blake

**Comment by mnichols13** [comment]
We are now getting complaints that all students can see all quizzes, not just the courses that they are assigned to ...

in IL Michelle Wiseman 
quiz name Agriscience Fair Projects
all students can see this

This is not right.

**Comment by mnichols13** [comment]
also the case in Kevin Garling's account

**Comment by mnichols13** [comment]
how quickly can you resolve this?  before tomorrow???

**Comment by bguerrettaz** [comment]
Yes I will back out student changes within an hour

**Comment by bguerrettaz** [comment]
The changes are backed out on the student side.

Did the students see all courses for their teacher or all quizzes
completely?  I didn't see that in my testing, so I want to make sure I
understand the issue.

This teacher's profile is a mess, so I questioned trying to put code in to
fix his specific issues initially.

**Comment by mnichols13** [comment]
When you ask all courses - do you mean all materials assigned?  like E-units and PPTs?  

The complaint was that the students could see all quizzes for all classes.  

Did I answer your question?

**Comment by mnichols13** [comment]
same teacher, different issue - Kevin Garling cannot assign E-units to Landscape Mgmt 19 
![image](https://user-images.githubusercontent.com/5790342/66141660-aae78e80-e5c9-11e9-896d-5d417dbd091e.png)

**Comment by mnichols13** [comment]
if possible please look today at Kevin's account and give some recommendations on what we need to do here.  I know you said his account was a mess.

**Comment by mnichols13** [comment]
There were two outlines names Landscape Mgt 19 that was causing this issue.  Once we removed the 2nd outline it seems to have solved this issues.
