### ISSUE TITLE
IL Landing Page

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#293]
Functionality for IL teachers

IL Ag teachers will be given access to the CTE libraries. IL CTE teachers will be given access to the Ag libraries

Create a Lesson Plan Builder landing page to replace http://www.mycaert.com/InnerHomepage.asp

Remove the profile heading for Agriculture and CTE in the MyCaert Admin, give the ability to associate a library with 1 or many program areas

1. Ag
2. Business Education
3. Family and Consumer Science
4. Tech Ed
5. Health Sciences

Note: the program area names could change over time, so a separate table for the program areas should be created with a key to link them to libraries

The new landing page for the Teachers should display the programs areas
Ag
Business Education
Family and Consumer Science
Tech Ed
Health Sciences

Provide the ability to expand and collapse the program areas. Expanding a program areas shows the associated libraries under for the program.

Provide the ability to select various libraries across the program areas

Provide the ability to submit and move to the next phase of building the Course Outline where the Units are selected
http://www.mycaert.com/Teachers/course-outlines/lesson-plan-library/CD_SelectUnits.asp

@dpentony

**Comment by dpentony** [comment]
Your time estimate for the above described work is 20 to 40 hours, correct?

Also, how long after we give you the go ahead would it take to complete the work?

**Comment by BrianPeterlin** [comment]
20-40hrs to complete

Completion estimate would be end of October, assuming approval and green light given by October 1st
