### ISSUE TITLE
Renaming course titles, deleting course titles not working ADAM STALEY issues

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#295]
Adam Staley - National state (OHIO)   has a course outline that he created but was unable to assign any materials to it.   He had named it 606 AgScience #2 plant, hort, animal science.   I told him that the hashtag oftentimes creates issues so I renamed it.   When I renamed it and took out the hashtag it didn't work properly.  Typically when a course outline is renamed, the students all stay with it.  This time it shows the new name under the blue MY courses tab, but under Manage course rosters the old title still existed.  Then I tried to copy the course outline to see if I could manually move the students over.   I manually added six students back into the course, however it still does not work.   If you try and go the assign E-units to the course, it just simply spins.   I do see that he has 143 lessons in the this course outline so I would expect it to be slow, but not completely non-functioning.   Please take a look

**Comment by mnichols13** [comment]
The teacher has deleted the outline.  I suggested that he just start over.   However it continues to be an issue that when a course outline is deleted that the title hangs around and doesn't delete completely.  What would it take to fix this?  for this teacher, Adam Staley -please delete the following: 

605 Agricultural Science #1 AFNR
606 AgScience #2 plant, hort, animal science

**Comment by mnichols13** [comment]
Can you please take care of this issue.  Delete the course outlines requested

**Comment by bguerrettaz** [comment]
This is complete.

Blake
