### ISSUE TITLE
MY COMMUNITY - added category

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#297]
Blake,
Please provide an estimate for adding a new category for the MY Community uploads
We would want it to be listed as "Videos".

This would be an area that teachers could search as well.

**Comment by bguerrettaz** [comment]
Hi - 3-4 hours for both the front end (user side) and the admin side.

I'm assuming this doesn't include an 'interface' for users to view the
videos, just a way to search and download those videos, correct?

Thanks,
Blake

**Comment by mnichols13** [comment]
Just to clarify - that is 3 - 4 hours total?  That is correct, just a search tool.

**Comment by bguerrettaz** [comment]
Yes, that's correct.
