### ISSUE TITLE
Quizzes not showing up correctly under Course Outline Title

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#298]
Under the Indiana Agriculture and Technology School
Teacher tried to copy all of her outlines and quizzes and rename them for the Spring semester.  All of them worked except Intro to AG - The copied outline is Intro to AG Semester A
There should be 8 quizzes that show up under each outline with identical titles - however some show up under Intro to AG twice instead of just once.  

Can you see why this is happening?  She would like it fixed today.  

Please see what you can do.  This is the teacher that we ruined her final exam from the upgrade over Christmas break.   Her opinion of us is pretty low at this point.

**Comment by bguerrettaz** [comment]
What is the teacher's name?

**Comment by mnichols13** [comment]
Wamsley and Wolfe

**Comment by bguerrettaz** [comment]
Sorry, you referenced one teacher in your original email, is the exact same
issue/outlines an issue with both teachers?

**Comment by mnichols13** [comment]
Intro to Agriculture (Wolfe)

**Comment by mnichols13** [comment]
The issue is just with the quizzes associated with Intro to Agriculture Semester A

**Comment by bguerrettaz** [comment]
Is this the quiz in question:

![image](https://user-images.githubusercontent.com/5695475/71946145-97caf880-318e-11ea-9f8e-4ed7a88340c5.png)

**Comment by bguerrettaz** [comment]
Here are all of the quizzes listed for this teacher and quiz class:

![image](https://user-images.githubusercontent.com/5695475/71946626-fc3a8780-318f-11ea-8ba8-c50ab7801d10.png)

I believe renaming: Introduction to Agriculture (Wolfe) Semester A (1/7/2020 2:57:31 PM)  to Introduction to Agriculture (Wolfe) SEMESTER A will fix the issue, but need confirmation that is what the issue is.

Can you please confirm?

**Comment by mnichols13** [comment]
She originally named it Intro to Ag Semester A none of the quizzes were showing, so I renamed it and tried to move them over, but just made a big mess.    So no I do not believe that will fix it.

**Comment by mnichols13** [comment]
it looks much better - at least now the student can see the quizzes that they need

**Comment by bguerrettaz** [comment]
Ok, so anything else needed from me at this point?

**Comment by mnichols13** [comment]
I just don't understand why the Intro to Agriculture Semester A is showing up under the original course outline 
![image](https://user-images.githubusercontent.com/5790342/71949897-dc5c9100-319a-11ea-9542-bdb086554cab.png)

**Comment by mnichols13** [comment]
There should be 7 quizzes and one final exam under each course outline - it looks like the Intro to Ag Semester A shows up both places.

**Comment by bguerrettaz** [comment]
OK, so I think removing that one with the date and time in the quiz class
title would take care of it, agreed?

**Comment by mnichols13** [comment]
Honestly I would prefer you do nothing at this point.  She went in last night and copied the quizzes over and seems happy with everything this morning. 

Please just leave it as is unless I reopen it.  

thanks!

**Comment by bguerrettaz** [comment]
Not a problem, thanks.
