### ISSUE TITLE
Missing test questions in PSAA

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#299]
An angry teacher emailed us late last night wanting to create a quiz from the PSAA lesson library, but could not find questions pertaining to several of the lessons.  Is there anyway you can go back and see from the back ups if these questions were there at one time?  Maybe as far back as 3 - 5 years?  This is a portion of what we are seeing.   It just doesn't make sense that these questions have never been there.  This is one of our older libraries, and we feel like they had to be there at one time.  

![image](https://user-images.githubusercontent.com/5790342/73286697-9e60f480-41bd-11ea-96fd-3217cb6e2b36.png)

**Comment by bguerrettaz** [comment]
Hi - here is all of the data related to PSAA in the database.  There are
two tabs, current data and data from a back 6-7 years ago:

https://docs.google.com/spreadsheets/d/1Q9lzyCZ7Y1e3Q1JuAwrfT65JWeZO6XIkWJqHWsGMn5c/edit?usp=sharing

Let me know if you have any questions.

Thanks,
Blake

**Comment by mnichols13** [comment]
Why do all of the columns say "NULL"?  I'm not seeing a difference in data from 2013 and today.

**Comment by bguerrettaz** [comment]
NULL is appropriate in this setting, you're looking at raw data, so that is
to be expected for certain columns/rows.

Yes, agreed, there is no different in either current or 7 years ago, which
means we don't have anything else stored that we can retrieve to bring back.

**Comment by mnichols13** [comment]
Ok thank you for the explanation and looking into this for us.
