### ISSUE TITLE
New student entry - defaults to ALL COURSES assigned not NO COURSES 

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#300]
When a teacher enters a new student but does not assign them to a course outline, the field is blank under EDIT STUDENTS.   I would have assumed this meant that the student had access to nothing.  However, Mary Fischer in NE called today and told me that these students that she has yet to assign can actually see everything that she has created/assigned.   

Can you please give us an estimate on what we need to do to change this so that it defaults to "nothing" rather than "all".

**Comment by mnichols13** [comment]
When can you take a look at this?

**Comment by bguerrettaz** [comment]
Hi - I actually tested this and when I add a student and don't select
anything here (viewable courses):
[image: image.png]

It doesn't enter anything into the database and I wasn't able to see
anything when I logged in as that student.

Can you send me back a scenario (links, what you entered, etc.) so I can
test with that?  I'm assuming she used the 'Add Student' link, not doing
this from the state admin side?

Thanks,
Blake

**Comment by mnichols13** [comment]
Mary Fischer - ND
Login as student Dillon Bowman - not assigned to anything - he can open her quizzes that are all assigned to a course. 
![image](https://user-images.githubusercontent.com/5790342/78557180-eca1fd80-77d5-11ea-9a35-bbf4a45fb312.png)

**Comment by bguerrettaz** [comment]
Ok, it took some digging to actually find what change would need to be made.

As designed, quizzes are displayed if they are directly assigned to a quiz
class.  If there is no selection when adding a student, the code on the
quiz page defaults to all quiz classes, which doesn't seem right.

I can make the change to 'none' if no quiz class is selected, but this may
impact other users that are used to it always being all?

When I change the code to do 'none' this works as I would imagine it
should, but again, don't know if it'll break other users.

Thoughts?

**Comment by mnichols13** [comment]
Let me double check with Dan on this one and I will let you know.  I think we will want to change it.. but I would rather make sure.

**Comment by bguerrettaz** [comment]
Thanks

**Comment by bguerrettaz** [comment]
Any action needed on this?

**Comment by mnichols13** [comment]
please go ahead and make the change that if a student is not assigned to a quiz class that they see nothing rather than ALL.

**Comment by mnichols13** [comment]
please complete this over the weekend if possible

**Comment by bguerrettaz** [comment]
Hi Mindy - I've made the change and tested.  Can you please confirm
functionality and let me know if there are any issues?

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good Blake, thank you
