### ISSUE TITLE
E-unit due dates are off one day for student home page

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#302]
When a teacher assigns an E-unit or Powerpoint and uses the due date fields, the due date seems to be one day off-sorta...  This is what is happening..

Maggie Folk, Byron Middle School said her students were not able to view the E-unit under the Section entitled View Assigned E-units.   When I signed in as one of her students and tried to pull up the E-unit from the assignment links, it shows 0 Eunits.  However if I click on the calendar due date, then I'm able to see and open the E-unit.  

What would it take to fix this date issue under the main section?  Add one day?  

Time estimate? 

![image](https://user-images.githubusercontent.com/5790342/81421714-83d0dc80-9117-11ea-9ce3-23d821d70037.png)

**Comment by bguerrettaz** [comment]
From the looks of it, 2-3 hours, but I'll need an example that I can use,
so another teacher/student that this is occurring to.

Thanks,
Blake

**Comment by mnichols13** [comment]
teacher:  Mindy Nichols   username:  MindyAG pw: 

course outline:  A Forestry Plan
assigned 3 Eunits
![image](https://user-images.githubusercontent.com/5790342/81603475-05cd3980-9394-11ea-9bdd-b0c89beaa7ea.png)


When a student (Lauren Adams) logins into their account the only way that they can see the E-unit due today is to click through the calendar.. it does not show up on the home landing page

![image](https://user-images.githubusercontent.com/5790342/81603568-2bf2d980-9394-11ea-98ce-201b466ba5e6.png)

![image](https://user-images.githubusercontent.com/5790342/81603620-42009a00-9394-11ea-8ffa-d3879e9c697c.png)

**Comment by bguerrettaz** [comment]
Hi - I was able to complete this and test it, but please confirm
functionality.

Thanks,
Blake

**Comment by mnichols13** [comment]
works!  thank you.
