### ISSUE TITLE
posting a video to the help tab

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#305]
What format does a video need to be in to post properly?  the one I have is .mov file

Or is there a size limit?

**Comment by mnichols13** [comment]
If we record it via Ring Central as a webinar, can we post that?

**Comment by BrianPeterlin** [comment]
posted to http://www.mycaert.com/content.asp?CID=4248DE035C807E8A88EF3AC1CCAF6927C769D5AA54FB3053

**Comment by BrianPeterlin** [comment]
@dpentony posted to http://www.mycaert.com/content.asp?CID=4248DE035C807E8A88EF3AC1CCAF6927C769D5AA54FB3053

**Comment by mnichols13** [comment]
thanks for your speedy help

**Comment by mnichols13** [comment]
Can you fix the spelling on this? 
![image](https://user-images.githubusercontent.com/5790342/90689850-50cdd700-e236-11ea-81b5-6fc76aea48c0.png)

**Comment by bguerrettaz** [comment]
This is complete.

Blake

**Comment by mnichols13** [comment]
thx
