### ISSUE TITLE
MY HOME button in BLUE BAR

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#307]
Can I get an estimate on what it would take to remove the word HOME and the actual house icon from the blue bar  - this does not take the user back to their HOME page - it logs them out.  This has become very evident as I have spent more time on the phone with potential customers.
I am not sure of the original intent of this?

![image](https://user-images.githubusercontent.com/5790342/87345571-e11d4b80-c515-11ea-9d0b-822015b22734.png)

**Comment by bguerrettaz** [comment]
Is there anything you'd like to replace it with? Or have it link somewhere
else?  I won't take too much to repurpose.  To remove means changing the
layout of the bar but even that is ~2 hours.

Please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
Would it be easier/cheaper to simply change the word from HOME to LOGOUT ?

**Comment by bguerrettaz** [comment]
It would, but it actually doesn't truly log you out.  If you click that,
and then go back and navigate to other areas of the site, you're still
logged in.

That doesn't mean we can't change the wording, just wanted to let you know.

Blake

**Comment by mnichols13** [comment]
interesting - but it really isn't the teacher HOME page - and unless they know to hit the back button - it appears as though they need to login again.

What if we made both HOME buttons operate the same?  The gold MY HOME is the "teacher" home page the other one is what I consider the login home page.

**Comment by bguerrettaz** [comment]
That's doable.  When you're not logged in, you'll go to the home page.  If
you are logged in, you'll go to your teacher home page...is that correct?

**Comment by mnichols13** [comment]
Yes that sounds reasonable.   If the teacher is logged in no matter which HOME button they select it will take them to the page listing their materials and course outlines.  

what is the time estimate on that?

**Comment by mnichols13** [comment]
please proceed with this request

**Comment by bguerrettaz** [comment]
Hi - this is complete.  Please confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
awesome.. soo much better.

appreciate this.
