### ISSUE TITLE
Google Single Sign On for Students - Self Service (estimate needed)

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#311]
give the ability for students to turn on Google Single Sign on for themselves. (need estimate)

**Comment by bguerrettaz** [comment]
This will require a database change to store preference by student, email,
etc. and an interface in their profile to set this up, plus testing.

Estimate of 15-20 hours or so.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks. I will share this info with our board and get back to you.

**Comment by mnichols13** [comment]
How much extra would it be to add the ability for teachers to see the google enabled and google email that has been entered previously on the EDIT STUDENT PAGE - 

it only shows on the ADD STUDENT PAGE - teachers have to individually edit each student to see the information

**Comment by bguerrettaz** [comment]
Should only take 1-3 hours to get that included and laid out correctly on
the page.

**Comment by dpentony** [comment]
Please move forward on these two aspects  - changes to the Edit Student Profile page and on the teacher's Edit Student Page. Based on your estimate, we are looking at between 16 and 23 hours. We're hoping this can be done prior to the start of school.

While you are at it, is there any reason to retain the first student email field under the teacher's Edit Student Page? We're not sure if this serves any purpose. It might be prudent to just hide it.

**Comment by bguerrettaz** [comment]
Hi - I have completed all development and testing of the google sign-on
self service.  The changes have been made to the edit profile interface for
the students and two columns were added to the edit student page on the
teacher side.

Please test and confirm these changes.

Thanks,
Blake

**Comment by dpentony** [comment]
Thanks.with Mindy being gone this week, it may take a while for us to do full testing.

**Comment by bguerrettaz** [comment]
No problem, thanks

**Comment by mnichols13** [comment]
I thought we were removing the first email column?  it is still there and it serves no purpose, but to just to confuse.

**Comment by mnichols13** [comment]
Also needs removed on the student page or we will have problems..

![image](https://user-images.githubusercontent.com/5790342/90810863-4587b380-e2e9-11ea-94df-8f104f95282d.png)

**Comment by bguerrettaz** [comment]
I actually left 'regular' email there for those that have an email, but not
a Google Email.  If that doesn't make sense, I can work to remove email
from those two locations.

**Comment by mnichols13** [comment]
please remove the "regular" email on both the teacher page and student page

**Comment by bguerrettaz** [comment]
Ok, are we sure that 'email' isn't used in other places?  Meaning if we
remove it, whatever is 'hooked' to that field in the database will never be
able to be accessed or changed again.  I'll just be removing the front-end
fields, not the database field, but just wanted to make sure there was
nothing else that used this email before removing it.

Good to remove?

**Comment by mnichols13** [comment]
can you simply "hide" it?

**Comment by bguerrettaz** [comment]
Yes, I can hide it in both locations.  If I hide and not remove, I'll just
need to make sure I make all of the necessary changes to align everything
on the page correctly.  For example, I just simply hide, they'll be a gap
in spacing and on the teacher side, it will not align in the table.

I can work on hiding this.

Blake

**Comment by bguerrettaz** [comment]
Hi - I have hidden email in both locations.  Please note that the spacing
is a bit weird on the teacher edit side, this is due to the code for this
page being super nested, which means it will take quite a bit of time to
get it right.

Thanks,
Blake

**Comment by mnichols13** [comment]
I'm confused as to where you removed the 2nd location ?  I see that it has been removed on the student page.   But this was the main location that is confusing when adding a student.

![image](https://user-images.githubusercontent.com/5790342/91048436-4d916d00-e5e1-11ea-82d5-922741aa811f.png)

**Comment by bguerrettaz** [comment]
Ok, I removed from the student edit profile and the teacher edit student, I
can also do add student.

**Comment by mnichols13** [comment]
still waiting on this to be removed from the ADD STUDENT page

**Comment by bguerrettaz** [comment]
Hi - this is complete.  Can you please confirm?

Thanks,
Blake

**Comment by mnichols13** [comment]
confirmed.
