### ISSUE TITLE
Google Classroom share not working

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#312]
The share link to post E-units/ppts for Google classroom is not working.  I have had two teachers email me and I have tested it as well.  

I'm not sure if it previously worked?  I just created a classroom on Saturday and had not played around until this morning.  

But it takes the student to the Mycaert sign in screen even if they are logged in already.   

Was something changed in the last few days?

**Comment by bguerrettaz** [comment]
Hmm, nothing has changed in the live code, I'm redesigning the code for
performance concerns and should wrap that up soon.  I just tested it and I
get redirected to the correct google share link...

**Comment by bguerrettaz** [comment]
![image](https://user-images.githubusercontent.com/5695475/88689327-f2db2300-d0bf-11ea-9264-9caca0f4f9bc.png)

**Comment by mnichols13** [comment]
it looks right until you go into google classroom and try to open the assignment
then it just directs you to the homepage

**Comment by bguerrettaz** [comment]
I just tested both PPT and EUnit after posting an assignment each and I was
directed to the EUnit PDF and the PPT downloaded on click from google
classroom.  Keep in mind, that if you haven't authenticated to MyCaert for
a certain time (I think its set to time out after 20-30 minutes) you'll be
redirected to the login page to re-login, then you'll be taken to that
document.

My assumption is that you had no active interactions with MyCaert website
and your login timed out.

**Comment by mnichols13** [comment]
are you viewing it as the teacher or student? - I did not wait 20 minutes -

**Comment by mnichols13** [comment]
I created a google classroom account. 
I have one student - my husband, Tony.  I created a MYcaert single sign on login for him.
I log into Mycaert as Tony Nichols
I open a new tab and go to Google classroom to open the assignment.
When I click the e-unit I get the Mycaert sign in screen even though I have another tab open and Mycaert is active. 

What am I doing wrong?

**Comment by bguerrettaz** [comment]
Hmm, your steps seem correct.  I just tested with my student account and it
worked correctly.  Are you in private or incognito browser mode?  If so, it
may not work correctly.

@Brian Peterlin <bpeterlin@cmiti.com> - can you also test this?

**Comment by mnichols13** [comment]
not private or incognito

however I am using IE 11

**Comment by bguerrettaz** [comment]
Ahh, that might be the issue.  I think when we built this we stipulated IE
not being able to do auto login with Google.  I could be wrong, but that's
ringing a bell.  Can you try with Chrome/Firefox?

**Comment by mnichols13** [comment]
I have tried it in Firefox, the E-units download, I cannot get them to open in a new tab.

The teacher who initially contacted me is using CHROME and she cannot get it to work.

**Comment by bguerrettaz** [comment]
Her issue may be related to her login timing out.  I'm not able to
recreate this in Chrome or Firefox (I agree about Firefox downloading the
E-Units, that's how it handles that).  If you work with her and validate
those items and still have the issues, it would be good to have screenshots
or a quick recording of her steps.

**Comment by mnichols13** [comment]
works in Chrome for me, I figured it out - hopefully after struggling through now I can help the teachers.
