### ISSUE TITLE
typographical error on website

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#314]
Under the Indiana Plant and Soil Science library Agriculture is spelled wrong here. Can you fix?
![image](https://user-images.githubusercontent.com/5790342/89472095-3fb89c80-d745-11ea-89df-ca612ce2020b.png)

**Comment by mnichols13** [comment]
what is the update on this??

**Comment by bguerrettaz** [comment]
This is complete, can you please confirm?

**Comment by mnichols13** [comment]
thx
