### ISSUE TITLE
FREE TRIAL ERROR - TAKE OFF knovotney

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#316]
The free trial request is blowing an error, apparently knovotney@caert.net was never removed.  Please remove it ASAP.
From: MAILER-DAEMON@p3plsmtp11-01-26.prod.phx3.secureserver.net <MAILER-DAEMON@p3plsmtp11-01-26.prod.phx3.secureserver.net>
Sent: Thursday, August 6, 2020 1:02 PM
To: SRS0=8dZx=BQ=hotmail.com=adrianna.segura@bounce.secureserver.net <SRS0=8dZx=BQ=hotmail.com=adrianna.segura@bounce.secureserver.net>
Subject: failure notice
 
Your mail message to the following address(es) could not be delivered.
This is a permanent error. Please verify the address(es) and try again.

<knovotney@caert.net>:
68.178.213.203 does not like recipient.
Remote host said: 550 5.1.1 <knovotney@caert.net> Recipient not found.  <http://x.co/irbounce>
Giving up on 68.178.213.203.

--- Below this line is a copy of the message.

Return-Path: <SRS0=8dZx=BQ=hotmail.com=adrianna.segura@bounce.secureserver.net>
Received: (qmail 6807 invoked from network); 6 Aug 2020 18:02:57 -0000
Delivered-To: support@caert.net
Precedence: bulk
Received: (qmail 6805 invoked by uid 30297); 6 Aug 2020 18:02:57 -0000
Received: from unknown (HELO p3plibsmtp03-12.prod.phx3.secureserver.net) ([68.178.213.107])
          (envelope-sender <adrianna.segura@hotmail.com>)
          by p3plsmtp11-01-26.prod.phx3.secureserver.net (qmail-1.03) with SMTP
          for <support@caert.net>; 6 Aug 2020 18:02:57 -0000
Received: from p3plsmtpa06-01.prod.phx3.secureserver.net ([173.201.192.102])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 256/256 bits)
        (Client did not present a certificate)
        by CMGW with ESMTP
        id 3kDCk5ZfG9aXr3kECknGaM; Thu, 06 Aug 2020 11:02:57 -0700
X-CMAE-Analysis: v=2.3 cv=FZ9JO626 c=1 sm=1 tr=0 cx=a_idp_nop
 a=EFLathxt8wSTzybmobbTsw==:117 a=TfMT3PZAMVUJtSIIguTo6w==:17
 a=t_5Nobi5V04A:10 a=9rJQC_r-iTwA:10 a=x7bEGLp0ZPQA:10 a=ML_pXgaiIt4A:10
 a=y4yBn9ojGxQA:10 a=69EAbJreAAAA:8 a=P2DT9mWr1idY9GTv55oA:9 a=Bii_OIlCWL4A:10
 a=WhGSnzGDVAsA:10 a=pHzHmUro8NiASowvMSCR:22 a=nt3jZW36AmriUCFCBwmW:22
Received: from MyCaert-2 ([199.255.165.17])
        by :SMTPAUTH: with ESMTPA
        id 3kECknWM0vSDs3kECk6HRw; Thu, 06 Aug 2020 11:02:56 -0700
X-CMAE-Analysis: v=2.3 cv=HsoI5HbS c=1 sm=1 tr=0
 a=TfMT3PZAMVUJtSIIguTo6w==:117 a=TfMT3PZAMVUJtSIIguTo6w==:17
 a=t_5Nobi5V04A:10 a=x7bEGLp0ZPQA:10 a=ML_pXgaiIt4A:10 a=69EAbJreAAAA:8
 a=P2DT9mWr1idY9GTv55oA:9 a=Bii_OIlCWL4A:10 a=WhGSnzGDVAsA:10
 a=pHzHmUro8NiASowvMSCR:22 a=nt3jZW36AmriUCFCBwmW:22
X-SECURESERVER-ACCT: noreply@caert.net
From: "Adrianna Segura" <adrianna.segura@hotmail.com>
To: "MyCAERT Web Contact" <support@caert.net>
Cc: tshelton@caert.net,
 peterlin3@gmail.com
Reply-To: adrianna.segura@hotmail.com
Subject: MyCAERT Web Contact
Date: Thu, 06 Aug 2020 13:02:56 -0500
Message-ID: <20200806-13025675-11ec@MyCaert-2>
X-MimeOLE: AgEd Library
MIME-Version: 1.0
Content-Type: text/html
X-CMAE-Envelope: MS4wfM9frsJL9+DMtLcvzefQEeqtP82gS+Nees6WvvyQvcjo+sheeFqpJFUPqy4Cyz5z89f7hJn2qXpIvLECZTA0iQj98SgFpO8wLtYy+Vaovu7Ss44qa7nf
 d42iROYICwvpuFQfVxufhsEpXxp5C/10mK1jx4PnVVd+JMBhBYf0xz0r1n6otiA/AOpUY4azIXVZmgodvrOV/KcIKNoktItTEayZMmXlYlICDPEqM25v/Odo

<font color=maroon><B>New Web Contact Request!</B></font><BR><BR>You have revieved a new Contact Request.<BR> Name: Adrianna Segura<BR> Email: adrianna.segura@hotmail.com<BR> State: Texas<BR> School: DHS<BR> Profile: Agriculture<BR> Question:<BR> I've tried to request a free trial but the email keeps getting kicked back. Any suggestions? <BR> <br><br>_______________________________________________<br><font color=maroon><B>Powered By CommonMan Innovative Technologies, Inc.</B></font><BR></body></HTML>

**Comment by bguerrettaz** [comment]
How do users get to the free trial request?  I can't see it on the website
anywhere...I know where it is in the code, but I'm more just curious as to
how I'm so blind...

**Comment by dpentony** [comment]
@bguerrettaz  - we have the ability to hide the free trial link. Mindy happened to do that right before she left on vacation for this week. There is a Manage Free Trial link on the admin page. You can unhide when you need to look into this, but please remember to re-hide it when you are finished.
![image](https://user-images.githubusercontent.com/5790325/89793733-d4c3e880-daeb-11ea-8397-c07c375c1f6f.png)

**Comment by bguerrettaz** [comment]
That's right, now I remember that.  Thanks, just couldn't remember.

**Comment by bguerrettaz** [comment]
So this is the only email its going to, which means that Kathy's email is
within this group: support@mycaert.com

@Brian Peterlin <bpeterlin@cmiti.com> - can you remove her email from this
distribution list?

Thanks,
Blake

**Comment by dpentony** [comment]
These emails also go to Mindy, Tim and me. The problem is that they also still go to Kathy's old caert email address. So, when a customer uses the free trial link, they get an error. This makes them wonder if their request went through. So, they end up sending multiple requests.

The rest of us get the trial request. It is just that Kathy's email still being included within the support@mycaert.com makes the customer believe the request did not go through.

**Comment by bguerrettaz** [comment]
Yes, agreed.  Brian will need to remove it from that group, I'm not sure
how he manages them.

**Comment by BrianPeterlin** [comment]
fixed
