### ISSUE TITLE
MySTUDENT tab - Edit Student Error Message

### ISSUE THREAD

**Issue by DouglasFalk** [MyCaert/Issues-Enhancements#318]
Here is the error message. under MySTUDENT, Edit student

Microsoft VBScript runtime error '800a000d'
Type mismatch: '[string: ""]'
/Teachers/students/select-student-edit.asp, line 896

Reported tonight by a teacher 8/12/2020

**Comment by dpentony** [comment]
@bguerrettaz - I believe this issue and 319 are related. It is present in multiple teacher accounts in different states. Could it relate to the google functionality we just installed allowing students to enter their gmail address?

**Comment by dpentony** [comment]
Examples include Eric Emmons and Liz Alloway in IL and Marty Speth in WI. As it is the time of year when teachers are adding/editing students, this is urgent.

**Comment by BrianPeterlin** [comment]
@bguerrettaz , the server looks ok.

**Comment by bguerrettaz** [comment]
Looks like it was a data issue and the new changes caught it with certain
teachers.  I've put a way to handle it in the code.  Can you please confirm
its resolved?

**Comment by bguerrettaz** [comment]
Just replied to 319, this should be resolved.

**Comment by dpentony** [comment]
Thanks for the quick fix!
