### ISSUE TITLE
update my students to put them in their new classes for this year and add new students but I keep getting an error. 

### ISSUE THREAD

**Issue by DouglasFalk** [MyCaert/Issues-Enhancements#319]
Name: Liz Alloway
Email: lalloway@bluffs-school.com
State: Illinois
School: Bluffs High School
Profile: Agriculture
Question:
I am trying to update my students to put them in their new classes for this year and add new students but I keep getting an error. I have tried it on Explorer and Chrome and get the same message. I have also turned off the pop-up blockers on both. When I try to edit a student and save it I get this message: Microsoft VBScript runtime error '800a000d' Type mismatch: 'CInt' /Teachers/students/select-student-edit.asp, line 156 I also am not able to see all my students that should be on my account. There are a bunch missing. I have reached out to our computer guys in case there is something they need to do on our end but wanted to reach out to you guys as well. Thank you for any help you can offer me! Thanks, Liz

**Comment by DouglasFalk** [comment]
10am on Aug 13 - Edit Student seems to b e working now,  I will continue to monitor.   Thanks for the speedy recovery Blake.

**Comment by bguerrettaz** [comment]
Sounds good - glad it was a quick fix.

Blake
