### ISSUE TITLE
Brian - What would it cost to have a popup message, popup on MyCAERT.com homepage for teachers to read????

### ISSUE THREAD

**Issue by DouglasFalk** [MyCaert/Issues-Enhancements#324]
Brian - What would it cost to have a popup message, popup on MyCAERT.com homepage for teachers to read????

Thanks Doug Falk

**Comment by dpentony** [comment]
Brian, specifically, we are wondering about a pop-up that would appear once a year that would force teachers to update their profile. They would login and then see the pop-up that would force them to edit their profile to insure we have current email, etc.
