### ISSUE TITLE
South Carolina Teachers

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#328]
@bguerrettaz , can you provide a count of distinct South Carolina Teachers that have logged into MyCAERT in the last year?

Similarly, can you provide a count of all distinct Teachers that have logged into MyCAERT in the last year?

**Comment by bguerrettaz** [comment]
Sure, here are those counts:

- 170 distinct SC teachers have logged in between 11/10/2019 and 11/10/2020
- 2389 distinct teachers (all states) have logged in between the same dates

Thanks,
Blake

**Comment by BrianPeterlin** [comment]
@dpentony can this be closed?
