### ISSUE TITLE
Kevin Garling account Indiana - students cannot see assigned eunits

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#329]
Kevin Garling Indiana
Assigned e-units to Horticulture 2020
e-units have no dates assigned and are made active
students assigned to the course cannot see them

Please advise..

**Comment by mnichols13** [comment]
can you look at this today?

**Comment by bguerrettaz** [comment]
Hi - I took a look at this and logged in as a student in that course and
was able to see the e-units:

[image: image.png]

Is it a different student(s) or am I missing something?

Thanks,
Blake

**Comment by mnichols13** [comment]
not sure what happened, but yes they are showing up now.
