### ISSUE TITLE
Archiving Teachers

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#337]
Does the archive of teachers only apply to those who are marked "inactive"?

Would it be possible to include teachers who have not logged in for "x" period of time.  I'm not sure if we would want that to be 2 years or 3 years.   Just posing the question right now to see if it is possible.

**Comment by bguerrettaz** [comment]
Hi - currently, this functionality archives teachers that has a deactivate
date more than 2 years from current date (the day someone runs the archive).

To answer your question, yes, we could also add functionality to archive if
they haven't logged in for a certain amount of time.

Thanks,
Blake

**Comment by mnichols13** [comment]
please provide estimate on added functionality

**Comment by bguerrettaz** [comment]
2-3 hours

**Comment by mnichols13** [comment]
Another question.
Is it possible for you to go in and delete IL CTE accounts that have not logged in for 24 months?  

Please provide estimate.

**Comment by bguerrettaz** [comment]
Yes, this is possible. An hour or two.
