### ISSUE TITLE
AG Business 5E

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#344]
We have a new lesson library AG Business 5E - when searching for items in the lesson library nothing comes up.

**Comment by mnichols13** [comment]
Do you need a file of the key terms for the library?  Or is this something that you are able to do for us?  Please let me know if we need to provide more information.

**Comment by bguerrettaz** [comment]
Yes, some key terms would be helpful for the search criteria.

**Comment by mnichols13** [comment]
Did we provide this before?  Dan thought we followed some sort of procedure previously for the new HORT library a few years ago.

**Comment by bguerrettaz** [comment]
Let me look back at those tickets, I can't remember off hand

**Comment by bguerrettaz** [comment]
Hi Mindy - I've updated the searching indexes.  Can you please test and
confirm?

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good
