### ISSUE TITLE
Add Indiana Teachers

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#346]
One account per school
- Username would be SchoolnameAG  (AdamsCentralAG)
- Password can be the same for all INMS22
- I would like to have both/all teacher emails in the account, separate with a comma 
- It would be great to have their last names in the account as well. 
- Mindy to provide the list
- **Must complete by 12/15**
- Mindy to provide the list
- Note: Schools are already added, we just need to add the accounts
- Active Date will be the current date through 2/1/2023
- Give them access to the "Indiana Middle School 5e" Outline

**Comment by mnichols13** [comment]
I'm almost finished with the list, since I had to add several schools as well as change each school to identically match the Indiana list, it is taking me longer than anticipated.

**Comment by mnichols13** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Mindy\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Mindy\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



School | First name | Last name | Username | Password | Email
-- | -- | -- | -- | -- | --
Adams   Central HS | Michael A | Jones |   |   | jonesm@accs.k12.in.us
Adams   Central HS | Ingrid | Kohlhagen |   |   | kohlhageni@accs.k12.in.us
Angola   HS | Neasa | Kalme |   |   | nkalme@msdsc.us
Argos   JR/SR HS | Lynette | Markley |   |   | lmarkley@argos.k12.in.us
Arsenal   Tech HS/STAR Academy | Moriah | Seifert |   |   | seifertm@myips.org
Attica   HS | Macon | Beck |   |   | mbeck@attica.k12.in.us
Beech   Grove HS | Clinton | Bullock |   |   | cbullock@bgcs.k12.in.us
Beech   Grove HS | Nichole | Kirk |   |   | nkirk@bgcs.k12.in.us
Beech   Grove HS | Cierra | White |   |   | cwhite@bgcs.k12.in.us
Beech   Grove MS | Craig | Witte |   |   | cwitte@bgcs.k12.in.us
Blue   River Valley JR/SR HS | ZoeAnn | Chernowsky |   |   | zoeann.chernowsky@brv.k12.in.us
Boonville   HS | Rebecca | Saltzman |   |   | rsaltzman@warrick.k12.in.us
Bremen   HS | Chad | Berger |   |   | cberger@bps.k12.in.us
Bremen   HS | Autumn (Peterson) | Schaffer |   |   | apeterson@bps.k12.in.us
Brownstown   Central HS | Blake | Hackman |   |   | bhackman@btownccs.k12.in.us
Carroll   HS - Fort Wayne | Cindy | Raker |   |   | cindy.raker@nacs.k12.in.us
Carroll   HS - Fort Wayne | Jacob | Bacon |   |   | jbacon@warrick.k12.in.us
Central   Noble HS | Jamie | Earnhart |   |   | earnhartj@centralnoble.k12.in.us
Central   Noble HS | Karin | Koontz |   |   | koontzk@centralnoble.k12.in.us
Churubusco   HS | Phil | Allen |   |   | allenp@sgcs.k12.in.us
Clay   City HS | Pat | Powell |   |   | powellp@clay.k12.in.us
Clay HS   - South Bend | Rose | Calhoun |   |   | rcalhoun@sb.school
Clinton   Central HS | Mallory | Curwick |   |   | mallory.curwick@clinton.k12.in.us
Clinton   Central HS | Damion | Watters |   |   | damion.watters@clinton.k12.in.us
Cloverdale   Middle/HS | Chris | Kaufman |   |   | ckaufman@cloverdale.k12.in.us
Cloverdale   Middle/HS | Katelyn | Myers |   |   | kmyers@cloverdale.k12.in.us
Columbia   City HS | Skylar | Campbell |   |   | campbellsj@wccsonline.com
Columbia   City HS | Sarah | Furthmiller |   |   | furthmillersaa@wccsonline.com
Columbus   East/North HS | Sara | Searcy |   |   | searcys@bcsc.k12.in.us
Crawford   County HS | Andrew | Howell |   |   | ahowell@cccs.k12.in.us
Crothersville   HS | Linda | Myers |   |   | lmyers@crothersville.k12.in.us
Danville   Community MS | Laura | Crosby |   |   | lcrosby@danville.k12.in.us
Decatur   Central High School (Indianapolis) | Abby | Clark |   |   | aclark@decaturproud.org
Delphi   Community HS | Taylor | Plank |   |   | plankt@delphi.k12.in.us
East   Central HS | Roy | Johnson |   |   | rjohnson@sunmandearborn.k12.in.us
East   Central MS | McCord | Snider |   |   | masnider@sunmandearborn.k12.in.us
East   Noble HS | Michael | Arnold |   |   | marnold@eastnoble.net
Eastbrook   HS | Cora | Hill |   |   | chill@eastbrook.k12.in.us
Eastbrook   HS | Kevin | Pluimer |   |   | kpluimer@eastbrook.k12.in.us
Eastern   Greene JR/SR HS | Cassie | Lehmann |   |   | clehmann@egreene.k12.in.us
Eastern   Hancock HS | Diana | Arellano |   |   | darellano@easternhancock.org
Eastern   Hancock HS | Sarah | Williams |   |   | swilliams@easternhancock.org
Eastside   HS | Lauren (Jacobs) | Hook |   |   | lhook@dkeschools.com
Edgewood   HS (Ellettsville) | Taylor | Ferguson |   |   | tferguson@rbbschools.net
Edgewood   MS (Warsaw) | Julie | Kincaid |   |   | jkincaid@warsawschools.org
Elkhart   Area Career Center | Ryan | Gortney |   |   | rgortney@elkhart.k12.in.us
Elkhart   Central HS | Eric | Jantzen |   |   | ejantzen@elkhart.k12.in.us
Elkhart   Memorial HS | Brenda | Mueller |   |   | bmueller@elkhart.k12.in.us
Fairfield   HS | Mallory | Baum |   |   | mbaum@fairfield.k12.in.us
Fishers   HS | Sam | Lawrence |   |   | slawrence@hse.k12.in.us
Forest   Park HS | Annette | Applegate |   |   | annette.applegate@sedubois.k12.in.us
Forest   Park HS | Olivia | Lamey |   |   | olivia.lamey@sedubois.k12.in.us
Forest   Park HS | Alex | Steftenagel |   |   | alex.steftenagel@sedubois.k12.in.us
Franklin   Community HS | Dan | Batta |   |   | battad@franklinschools.org
Franklin   County HS | Teri | Hornberger |   |   | thornberger@fccsc.k12.in.us
Brookville   Middle School | Teri | Hornberger |   |   | thornberger@fccsc.k12.in.us
Frankton   JR/SR HS | Stacy | Wainscott |   |   | swainscott@flcs.k12.in.us
Gibson   Southern HS | Jessie | Schermerhorn |   |   | jessie.schermerhorn@sgibson.k12. in.us
Hagerstown   HS | Christy | Herr |   |   | cherr@nettlecreek.k12.in.us
Hagerstown   HS | Jarrod | Hokey |   |   | jhokey@nettlecreek.k12.in.us
Hamilton   Comm HS | Kelsey | McMullen |   |   | kelsey.mcmullen@hcs.k12.in.us
Hamilton   Southeastern HS | Caroline (Kuhn) | Mills |   |   | cemills@hse.k12.in.us
Hamilton   Southeastern HS | Tom | Younts |   |   | tyounts@hse.k12.in.us
Hauser   JR/SR HS | Aleesa | Dickerson |   |   | adickerson@flatrock.k12.in.us
Hauser   JR/SR HS | Kelly | Dressler |   |   | kdressler@flatrock.k12.in.us
Huntington   North HS | Emily | Brite |   |   | EBrite@hccsc.k12.in.us
Huntington   North HS | Jamie | Buckland |   |   | jbuckland@hccsc.k12.in.us
Indian   Creek HS | Shalee (Daming) | Bradley |   |   | sbradley@nhj.k12.in.us
Indian   Creek HS | Joe | Dunn |   |   | jdunn@nhj.k12.in.us
Indian   Springs MS | Mandy | Grimm |   |   | grimmme@wccsonline.com
Indian   Springs MS | Travis | Olinske |   |   | olinskets@wccsonline.com
Indiana   Agricultural and Technical School | Amber | Wolfe |   |   | awolfe@indiana.ag
Indiana   Digital JR/SR HS | Olivia | Cummings |   |   | ocummings@k12.com
Indiana   Digital JR/SR HS | Ashley | Langreck |   |   | alangreck@k12.com
Indiana   School for the Blind & Visually Impaired | Elizabeth | Garvey |   |   | EGarvey@isbvik12.org
Indiana   Women’s Prison | Brenda | Gullett |   |   | bgullett@sbcglobal.net
Jac-Cen-Del   HS | Sarah | McGhee |   |   | smcghee@jaccendel.k12.in.us
Jasper   HS | Brianna | Lammers |   |   | blammers@gjcs.k12.in.us
John   Glenn HS | Tim | McLochlin |   |   | tmclochlin@jgsc.k12.in.us
Knox HS | Mel | Lenig |   |   | mlenig@knox.k12.in.us
Lakeland   HS | Rebecca | Peterson |   |   | rpeterson@lakelandlakers.net
Lakeland   MS | Thom | Taylor |   |   | ttaylor@lakelandlakers.net
Lakeview   Middle School | Julie | Kincaid |   |   | jkincaid@warsawschools.org
Lapel   HS | Stacy | Wainscott |   |   | swainscott@flcs.k12.in.us
LaPorte   Middle School | Whitney | England |   |   | wengland@lpcsc.k12.in.us
LaPorte   Middle School | Amber | Paquette |   |   | apaquette@lpcsc.k12.in.us
LaPorte   HS | Rebecca | Tuholski |   |   | rtuholski@lpcsc.k12.in.us
LaVille   JR/SR HS | Clinton | Watts |   |   | cwatts@unorth.k12.in.us
Lebanon   Community HS | Logan | Glassburn |   |   | glassburnl@leb.k12.in.ius
Lebanon   Community HS | Shelby | Lee |   |   | lees@leb.k12.in.us
Lebanon   Community HS | Hannah | McFauls |   |   | mcfaulsh@leb.k12.in.us
Lewis   Cass HS | Michael | Appleton |   |   | appletonm@lewiscass.net
Lewis   Cass HS | Heather | Smith |   |   | smithh@lewiscass.net
Lincoln   MS/HS | Alaina | Kessler |   |   | akessler@wwayne.k12.in.us
Logansport   Century Career Center | Jenni | Fishburn |   |   | fishburnj@lcsc.k12.in.us
Logansport   MS | Emily | Duvall |   |   | duvalle@lcsc.k12.in.us
Loogootee   HS | Doug | Mayfield |   |   | dmayfield@loogootee.k12.in.us
Maconaquah   HS | Dawn | Baker |   |   | bakerd@maconaquah.k12.in.us
Maconaquah   MS | John | Sinnamon |   |   | sinnamonj@maconaquah.k12.in.us
Madison-Grant   Jr/Sr HS | Courtney (Tate) | Lockwood |   |   | ctate@mgusc.k12.in.us
Manchester   HS | Gwen | Mize |   |   | gwen_mize@mcs.k12.in.us
Martinsville   HS | Jay | Marks |   |   | jay.marks@msdmartinsville.org
Martinsville   HS | Emma | Messmer |   |   | emma.messmer@msdmartinsville.org
McCutcheon   HS | Drake | Davis |   |   | dldavis@tsc.k12.in.us
McCutcheon   HS | Hannah (Lyon) | Doke |   |   | hglyon@tsc.k12.in.us
Medora   HS | Adam | Conklin |   |   | aconklin@medora.k12.in.us
Mitchell   HS | Jeanette | Martin |   |   | martinje@mitchell.k12.in.us
Monrovia   MS/HS | Tori | McCreary |   |   | tmccreary@m-gsd.org
Morgan   Township HS/Porter Career | Rachel | Stoner |   |   | rachel.stoner@eastporter.k12.in.us
Mt.   Vernon Jr. HS | Alicia | Schmidt |   |   | schmidtaa@mvschool.org
New   Castle HS | Noah | Brown |   |   | nbrown2@ncweb.me
New   Prairie HS | Mark | Stone |   |   | markstone@npusc.k12.in.us
New   Washington HS | Jeff | Johnson |   |   | jjohnson@gcs.k12.in.us
North   Central HS | Jamie | Huff |   |   | huffj@nesc.k12.in.us
North   Decatur HS | Katie | Stokes |   |   | kstokes@decaturco.k12.in.us
North   Decatur HS | Audrey (Neuman) | Wicker |   |   | awicker@decaturco.k12.in.us
North   Judson-San Pierre HS | Jonathan | Shively |   |   | jshively@njsp.k12.in.us
North   Judson-San Pierre HS | Lauren | Yacks |   |   | lyacks@njsp.k12.in.us
North   Knox HS | Josh | Chambers |   |   | jchambers@nknox.k12.in.us
North   Miami HS | Jim | Wildermuth |   |   | jwildermuth@nmcs.k12.in.us
North   Montgomery HS | Nancy | Bell |   |   | nbell@nm.k12.in.us
North   Newton JR/SR HS | Ron | DeYoung |   |   | rdeyoung@nn.k12.in.us
North   Newton JR/SR HS | Sabrina | Tarter |   |   | starter@nn.k12.in.us
North   Posey HS | Robyn | Bender |   |   | rbender@northposey.k12.in.us
North   Putnam HS | Janna | Oxford |   |   | joxford@nputnam.k12.in.us
North   Putnam HS | Kate | Skirvin |   |   | kskirvin@nputnam.k12.in.us
North   Putnam MS/HS | Heather (Goss) | Clingan |   |   | hclingan@nputnam.k12.in.us
North   White High School | Kari | Hoenert |   |   | khoenert@nwhite.k12.in.us
North   Woods HS | Amy | Beer |   |   | abeer@wanee.org
North   Woods HS | Grace | Allen (Klopfenstein) |   |   | goallen@wanee.org
North   Woods MS | Morgan | Alexander |   |   | mlalexander@wanee.org
North   Woods MS | Brandi | Henderson |   |   | bhenderson@wanee.org
Northeast   Dubois HS | Traci | Wineinger |   |   | twineinger@nedubois.k12.in.us
Northfield   HS | Makayla (Mobley) | Myer |   |   | myerm@msdwc.k12.in.us
Northwestern   JR/SR HS | Kylei (Klein) | Hickner |   |   | kylei.hickner@nwsc.k12.in.us
Norwell   HS | Kyle | Bailey |   |   | kyle.bailey@nwcs.k12.in.us
Oregon-Davis   HS | Kristin | Kubacki |   |   | kkubacki@od.k12.in.us
Orleans   HS | Hank | Carson |   |   | hcarson@orleans.k12.in.us
Owensville   Community MS | Tricia | Goodman |   |   | tricia.goodman@sgibson.k12.in.us
Parke   Heritage HS | Colton | McMullen |   |   | mcmullenc@ncp.k12.in.us
Parke   Heritage HS | Shannon | Witty |   |   | wittys@ncp.k12.in.us
Parke   Heritage MS | Hallie | Jones |   |   | jonesh@ncp.k12.in.us
Parke   Heritage MS | Natalee (Brann) | Laube |   |   | lauben@ncp.k12.in.us
Pendleton   Heights HS | Holly | Williams |   |   | hwilliams@smcsc.com
Penn HS | Brent | Laidig |   |   | blaidig@phm.k12.in.us
Penn HS | Leigha | Sparrow |   |   | lsparrow@phm.k12.in.us
Perry   Central HS | Carrie | Guillaume |   |   | cguillaume@pccommodores.org
Prairie   Heights HS | Laney (Kratz) | Koeppe |   |   | lkoeppe@ph.k12.in.us
Prairie   Heights HS | Ben | Leu |   |   | bleu@ph.k12.in.us
Prairie   Heights HS | Ron | Noll |   |   | rnoll@ph.k12.in.us
Princeton   HS | James | Bloebaum |   |   | jbloebaum@ngsc.k12.in.us
Randolph   Southern HS | Shianna | Fry |   |   | knolls@rssc.k12.in.us
Rensselaer   Central HS | Brenlyn | Hoover |   |   | brenlyn.hoover@rcsc.k12.in.us
Rochester   MS | Nikki | Overmyer |   |   | nikki.overmyer@zebras.net
Rossville   JR/SR HS | Brittany | Need |   |   | bneed@rcsd.k12.in.us
Southern   Indiana Career & Technical Center | Hollye | Schillinger |   |   | hollye.schillinger@evsck12.com
Seeger   Memorial HS | Jessica | St. John |   |   | jst.john@msdwarco.k12.in.us
Seeger   Memorial MS | Bailey | Crowder |   |   | bacrowder@msdwarco.k12.in.us
Seymour   HS | Sheridan | Elswick |   |   | elswicks@scsc.k12.in.us
Seymour   HS | Mikayla | Applegate |   |   | applegatem@scsc.k12.in.us
Shakamak   JR/SR HS | Kenna | Slough |   |   | kslough@shakamak.k12.in.us
Shelbyville   HS | Kay | Huntsman |   |   | khhuntsman@shelbycs.org
Shelbyville   MS | Kennedy | Lawson |   |   | kelawson@shelbycs.org
Shenandoah   HS | Emily | Burris |   |   | eburris@shenandoah.k12.in.us
Sheridan   MS | Mary Catherine | Dillon |   |   | marycatherinemills@gmail.com
Shoals   HS | Ben | Kent |   |   | ben.kent@shoals.k12.in.us
South   Adams HS | Jason | Shuck |   |   | jshuck@southadams.k12.in.us
South   Central JR/SR HS (Union Mills) | Kyle | McCallum |   |   | mccallum@scentral.k12.in.us
South   Central JR/SR HS (Elizabeth) | Nancy | Day |   |   | dayn@shcsc.k12.in.us
South   Dearborn HS | Mara | Jones |   |   | mara.jones@sdcsc.k12.in.us
South   Dearborn MS | Elizabeth | Knight |   |   | elizabeth.knight@sdcsc.k12.in.us
South   Spencer HS | John | Hurley |   |   | john.hurley@sspencer.k12.in.us
Southmont   JR/SR HS | Gary | Mosbaugh |   |   | Gary.Mosbaugh@southmont.k12.in.us
Southwestern   JR/SR HS (Hanover) | Wesley | Powell |   |   | wpowell@swjcs.k12.in.us
Sullivan   HS | Kevin | Cross |   |   | kcross@swest.k12.in.us
Sullivan   HS | Jeff | Miller |   |   | jmiller@swest.k12.in.us
Tri   Central HS/MS | Leah | Cruea |   |   | lcruea@tccs.k12.in.us
Tri-County   HS | Haley | Verhaeghe |   |   | verhaegheh@trico.k12.in.us
Union   City Community HS | Cindy | Nunez |   |   | cnunez@resc.k12.in.us
Union   City Community HS | Ron | Smith |   |   | rsmith@resc.k12.in.us
Union   County HS | Cassidy | Krom |   |   | cassidy.krom@uc.k12.in.us
Warsaw   Community HS | Breanna (Breske) | Bartman |   |   | bbartman@warsawschools.org
Warsaw   Community HS | Julie | Kincaid |   |   | jkincaid@warsawschools.org
Wawasee   HS | Jesse | Kimmel |   |   | jkimmel@wawasee.k12.in.us
Wawasee   HS | Mariah | Roberts |   |   | mroberts@wawasee.k12.in.us
West   Central JR/SR HS | Shaw | Haselby |   |   | shaselby@wcsc.k12.in.us
West   Noble HS | Khara | Kimmel |   |   | kimmelk@westnoble.k12.in.us
West   Noble HS | Amy | Newby |   |   | newbya@westnoble.k12.in.us
West   Noble HS | Rudy | Troxel |   |   | troxelr@westnoble.k12.in.us
Westview   JR/SR HS | Paul | Baker |   |   | bakerp@westview.k12.in.us
Westville   MS/HS | William (Bill) | Smith |   |   | wsmith@westville.k12.in.us
White   River Valley HS | Michaela (Alexander) | Fuller |   |   | mfuller@wrv.k12.in.us
Whiteland   Community HS | Hannah | Goeb |   |   | hgoeb@cpcsc.k12.in.us
Whiteland   Community HS | Katie | Ott |   |   | kott@cpcsc.k12.in.us
Whitko   HS | Matt | Dice |   |   | matt.dice@whitko.org
Winamac   Community HS | Tamara | Halleck |   |   | tammy.halleck@epulaski.k12.in.us



</body>

</html>

**Comment by BrianPeterlin** [comment]
@bguerrettaz any questions on this?

**Comment by bguerrettaz** [comment]
No, not at this point.

Blake

**Comment by mnichols13** [comment]
are you talking about for the last name field?  Or the username field? 

last name - you can just use the first one on the list
username we would like schoolnameAG

Does that answer your question?

**Comment by bguerrettaz** [comment]
Yep, it was for last name, and you answered it, thanks!

**Comment by bguerrettaz** [comment]
Hi - I'm not getting matches in the school database table for the following
schools:

Brookville Middle School
Carroll HS - Fort Wayne
Danville Community MS
Hauser JR/SR HS
Indian Springs MS
Indiana Agricultural and Technical School
Indiana Womenâ€™s Prison
Lakeview Middle School
Lapel HS
North White High School
Shakamak JR/SR HS
Sheridan MS
Tri-County HS

Could you please let me know what they should be and match them in
mycaert?  The admin console is probably the best place?

Thanks,
Blake

**Comment by mnichols13** [comment]
I've made the corrections in the MYcaert admin console so that they should all now match except
Indiana Women's Prison 

thanks!

**Comment by bguerrettaz** [comment]
I have fixed Indiana Women's Prison but there is one more that isn't
matching, looks like its misspelled:
[image: image.png]

Would you mind changing 'Middel' to Middle?

Thanks,
Blake

**Comment by mnichols13** [comment]
done

**Comment by bguerrettaz** [comment]
Hi all - this is not complete.  154 teachers were inserted into the
tblTeacher table.  All teachers from the same school were combined.

Please test a few to confirm functionality.

Thanks,
Blake

**Comment by mnichols13** [comment]
The activate date includes the time stamp.  
Can you remove the time stamp? The lesson library doesn't work with the time stamp.  When I remove it, there is no issue.

**Comment by bguerrettaz** [comment]
Sure thing - please test now, all teachers updated.

**Comment by mnichols13** [comment]
library does not show up on their home page, even though the activation dates are correct.  
![image](https://user-images.githubusercontent.com/5790342/145875431-9e10c57f-76f3-4821-a60b-30d155cce5ff.png)

**Comment by bguerrettaz** [comment]
Hi - this should be resolved now.  Can you please confirm?

**Comment by mnichols13** [comment]
thanks, it looks good!
