### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#347]
Schools are now sharing accounts and adding two email addresses to the teacher account.  They separate the account with a comma.

This is request is to update the Forgot Password system to handle two email addresses.

https://www.mycaert.com/ForgotPassword.asp

Example: danil

two emails in it: dpentony@caert.net, peterlin3@gmail.com

It currently does work if if "dpentony@caert.net, peterlin3@gmail.com" is searched.  It does not work if peterlin3@gmail.com is searched.

We would like the retrieve password to work if either email address is searched.

**Comment by bguerrettaz** [comment]
Hi - I believe I have this functionality working as desired.  Can you
please test and confirm?

Thanks,
Blake

**Comment by mnichols13** [comment]
It works, it came through twice on both emails though.  Which is not a huge deal, but I guess if you can correct that without spending a lot of time. ?

**Comment by bguerrettaz** [comment]
I've put in a small change if you could test it.  If it doesn't work, it
will be a larger change.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good.
