### ISSUE TITLE
Teachers have access to quiz questions for libraries they don't subscribe

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#348]
I've noticed for the Illinois teachers - who no longer get a state subscription - still have access to all of the quiz questions even when they don't pay for a lesson library. 

Example:  Josh Bullard in IL  
username:  Bullard
pw:  Foxrace44

He only pays for Middle School - however he is able to create quizzes from any of his old course outlines.  He should only be able to access the quiz questions from Middle School.  

Please fix.

**Comment by bguerrettaz** [comment]
I'm looking into this, I'll update on findings.

**Comment by bguerrettaz** [comment]
Hi - I'm not seeing where he has this access, could you give me your steps
so I can emulate?

Thanks,
Blake

**Comment by mnichols13** [comment]
When logged in as Josh, go to create a quiz, choose add questions by course outline and choose any of the questions from old created course outlines.   For example Ag Mechanics or Ag Business, neither of which he pays for. 

Also you can go to Edit Quiz.  Choose Ag Mechanics as the course outline, then click edit questions.   All of the quiz questions are visible.

**Comment by bguerrettaz** [comment]
Ok, I've looked into this quite a bit and unfortunately, quizzes currently
have no logic to see if the existing quizzes course outlines are still
available.  This is true both for add and edit.

So in this case, I don't see any new course outlines built from the new
lesson plan library that this user subscribes to, is that correct?

So all of that logic will need to be built into both add and edit quiz and
I would suggest some testing to make sure we don't break other users.

Please let me know what you think.

Blake

**Comment by mnichols13** [comment]
Blake,
At this point, I think we leave it as is.  It does affect that many users.   Thank you for looking into this.
