### ISSUE TITLE
New report on activate date

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#349]
I'm trying to run a report to figure out how many new customers we activated in 2021 and other years as well.   Could I get an estimate on running a report based upon the master activate date?  Currently I can run account expiration date reports to see when customers don't renew their accounts, but it would be helpful to know what new accounts we activated.

**Comment by bguerrettaz** [comment]
Hi - do you just want an excel report that I run or do you want the ability
on the admin console to run this report as needed?

What fields would you want in the report?   Assuming that the criteria
would look for all teachers with an activate date in all of 2021, correct?

**Comment by mnichols13** [comment]
I want the ability to run the report on the Admin console for any given month or year just as I can for the expiring teacher account report.
I would want the report to be very similar to this, with the following fields:
state
school
teacher
teacher activate date
teacher deactivate date
teacher email
zip code

![image](https://user-images.githubusercontent.com/5790342/153223342-0c97092a-0ceb-4d70-9926-8eff0a81004f.png)

**Comment by bguerrettaz** [comment]
Ok, thanks.  Probably around 4-6 hours to build that on the admin console.

**Comment by mnichols13** [comment]
Thank you, I'll be in touch.

**Comment by mnichols13** [comment]
please go forward with this request.

**Comment by mnichols13** [comment]
didn't mean to close

**Comment by bguerrettaz** [comment]
Hi - I have completed your report request.  The new report is located on
the Admin console under 'Orders and Expiring Accounts' --> 'New Customers -
By Date'.

Please let me know if you have any questions.

Thanks,
Blake

**Comment by mnichols13** [comment]
This seems to work really well and is exactly what I was looking for! Thanks!
