### ISSUE TITLE
Problem with home page display

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#351]
Not sure why the page is showing up so off centered, but I've noticed it on two teacher pages today.  Can you take a look ? that space inbetween was never there before

![image](https://user-images.githubusercontent.com/5790342/153496678-22c26412-4364-468d-b3ec-e455d97f80f0.png)

**Comment by mnichols13** [comment]
It looks the same on Firefox and Microsoft Edge..

**Comment by bguerrettaz** [comment]
Should be fixed now?

**Comment by mnichols13** [comment]
great - yes looks much better!
