### ISSUE TITLE
Estimate for remove or hide student information

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#353]
Under the student edit profile page there is an area for address/ city / state  / zip code and their phone number.

 What would be the estimate to just simply hide or remove these fields?

**Comment by bguerrettaz** [comment]
Just an hour or two for this as its not currently required, correct?

**Comment by mnichols13** [comment]
None of this is required, so  please go ahead and remove the fields as requested:  address, city, state, zip code and phone number

**Comment by bguerrettaz** [comment]
Hi - this is complete.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good, thanks!
