### ISSUE TITLE
Quizzes and Quiz questions available for old course outlines

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#355]
There seems to be an issue with IL, maybe other states?  We have a IL teacher who previously had all of our materials.  Now she only subscribes to one (Middle School lesson library).  However she can still create quizzes from old course outlines and still use all of her old quizzes.  She doesn't pay for these anymore, so she should not have access to anything except Middle School.

Teacher: Amanda Gough Kansas HS

**Comment by bguerrettaz** [comment]
Hi - I'm looking into this.

Blake

**Comment by bguerrettaz** [comment]
Ok, so there is a lot to unpack here.  There are three separate tables/concepts:- tblQuizClass- tblCourseOutlines- tblCDs
From an access perspective, this is managed at the tblCD level.  When looking at the following tables for this teacher, you can see the course outlines:

- tblQuizClass 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5695475/189199833-9ee63406-874b-4257-8985-e595964e276a.png">

- tblCourseOutline 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/5695475/189199767-c0b0fabc-3c8e-40bd-b3c8-84bcf166c473.png">

If you look at these tables, neither one of them have a hook or connection to the access of tblCD, therefore I believe this has always been this way (I believe we may have talked about it before as well)?

It would take a lot to fix this, and I'm not even sure how I'd do it without digging in more.  If I'm missing something, please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
Ok, not worth it.  thanks for looking .  It probably affects a very small number.
