### ISSUE TITLE
Changing the wording: SENDING A COURSE OUTLINE

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#356]
On the course outline page teachers have an option to send a course to another teacher.  The wording currently says EMAIL COURSE OUTLINE..  This is confusing to teachers.  Can you please change it to SEND COURSE OUTLINE?  

![image](https://user-images.githubusercontent.com/5790342/195450935-cbc1d82f-c945-42f0-a10a-becb2142e795.png)

**Comment by mnichols13** [comment]
On the next page, possibly add text: This course outline will appear under the saved course outlines in this teacher's account.

![image](https://user-images.githubusercontent.com/5790342/195451236-0e48debc-4dad-4f0e-9c24-ce86b1ad2662.png)

**Comment by mnichols13** [comment]
Finally - the last thing is that needs to be fixed is that it seems to "blow an error" everytime.. even though it actually does work.   Can you fix  it so it does not do this? 
![image](https://user-images.githubusercontent.com/5790342/195452020-5b5dfc8e-ef08-4f36-9bcb-e295b127dbab.png)

**Comment by bguerrettaz** [comment]
Hi - I have completed all of these changes.

Please let me know if there are any issues.

Thanks,
Blake

**Comment by mnichols13** [comment]
Excellent... one little tweak. 

This course outline will appear under the blue MY COURSES tab in **the receiving** teacher's account

**Comment by bguerrettaz** [comment]
Updated

**Comment by mnichols13** [comment]
Looks great.  Thanks!
