### ISSUE TITLE
Add links to how to videos

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#357]
Hello! I've updated the "How to" videos and uploaded them on the "Tutorial and Take a Tour" page. 
Could I get a quote for adding those links throughout the website in several locations?
Examples:
My Students tab - adding an option at the top saying "Need help? Watch a video here" with a link to the MyStudents video
Home page - adding a button towards the top left saying "First time logging in? Watch a video here" with a link to the First Time Logging in video

There are 3-5 other locations I'd like to add links, but want to know if this is doable first. Thanks!

**Comment by bguerrettaz** [comment]
Hi - for 3-5 locations, probably 3-4 hours or so.
