### ISSUE TITLE
Updating all Indiana teachers

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#359]
All AG accounts / teachers in Indiana currently have access to the Indiana Middle School 5E lesson library until 2-1-23.  We need to add one year to this, making the expiration date 2-1-24.   For many accounts, this date matches the master deactivation date, however there are some teachers who subscribe to other lesson libraries and may have a different master deactivation date.  

We would like help updating these teachers.  If necessary, we could update those accounts with the master activation date that is different (so something other than 2-1-23).  I just need to know from you what would work best.   Ideally we would have this completed by January 6, 2023.

**Comment by mnichols13** [comment]
Can you give me an update on this? Ideally we wanted it done by last Friday.  When do you think you can complete this?

**Comment by bguerrettaz** [comment]
Hi - I’ll aim to have this complete by EOW.BlakeSent from my iPhoneOn Jan 10, 2023, at 12:06 PM, mnichols13 ***@***.***> wrote:﻿
Can you give me an update on this? Ideally we wanted it done by last Friday.  When do you think you can complete this?

**Comment by bguerrettaz** [comment]
Hi - these updates are complete.  I've updated all records with a
deactivatedate of 02/01/2023 with 02/01/2024. There are a some left with
differing deactivate dates as an FYI.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
I thought this was just for that library...you're asking for me to update
the teachers deactivate date as well?  To be clear, all IN AG teachers with
that library would be updated to 2/1/24.  Is that correct?

**Comment by mnichols13** [comment]
All Indiana teachers with Indiana Middle School lesson library updated to 2-1-24 must have the master deactivation date updated to 2-1-24 as well otherwise they cannot login.

So yes, any Indiana deactivation dates of 2-1-23 must be updated to 2-1-24.  If the master deactivation date is something other than 2-1-23 then they most likely have additional lesson libraries and it should be left along.  IS THIS POSSIBLE? 

IF not I can go in and fix those.

**Comment by mnichols13** [comment]
the original request did ask for the master deactivation date to be changed.  Please advise when this can be completed.

**Comment by bguerrettaz** [comment]
Hi - this has been completed.

Thanks,
Blake

**Comment by mnichols13** [comment]
thank you!

**Comment by mnichols13** [comment]
@bguerrettaz @BrianPeterlin  - our Indiana teachers are going to need to be updated again.  Rather than paying you to do this every year - we would like to take this over.  I am guessing that this is all done through the ADMIN console that we already have access to.  Would it be possible to talk this through and then turn it over to us?

**Comment by bguerrettaz** [comment]
Hi Mindy - these updates actually have to be done in the SQL database.
These could manually be done in the admin console but it would take a very
long time for some of the states and would be laborious.

The process entails taking backups of all tables involved (I believe there
are 5 total), then writing the SQL update scripts to update all teachers in
the criteria (in this case, all IN Ag teachers) and then setting new
teacher expiration dates as well as all of the library subscription
tables/dates.

I'm not sure this could be passed to anyone unless they have a good deal of
SQL experience.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
No worries!  Please let me know the criteria and new dates and I can work
on this.

Thanks,
Blake
