### ISSUE TITLE
FREE Trial toggle button not working

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#360]
We are supposed to have the ability to turn the FREE TRIALS off, however it is not working.  Can you please take a look? 
![image](https://user-images.githubusercontent.com/5790342/210581412-a4f2628f-1b20-405e-b84c-fc85a68d3c2b.png)

**Comment by mnichols13** [comment]
![image](https://user-images.githubusercontent.com/5790342/211639551-dd2a275c-a320-4b15-a537-a58359cfe98e.png)

**Comment by mnichols13** [comment]
shows up no matter what we do on the ADMIN page - can you fix?

**Comment by bguerrettaz** [comment]
Hi - I've corrected this issue.  Can you please test and confirm?

Thanks,
Blake

**Comment by mnichols13** [comment]
tested and this looks good.
