### ISSUE TITLE
Cannot view all teacher accounts in ADMIN - limit 1000

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#361]
Currently our view is limited to 1000 viewable accounts under the National state for Edit/Delete teachers.   Can we get an estimate on what it would take for us to be able to view all accounts?  

![image](https://user-images.githubusercontent.com/5790342/212124951-bf7d02de-c494-48a6-aec2-5c6d83a235e5.png)

**Comment by bguerrettaz** [comment]
I believe this would only take 2-3 hours.

**Comment by bguerrettaz** [comment]
Hi - displaying more than 1000 is now complete.  You will now see all
results at once.

Also, that change is a little more involved to select a secondary value
after national user and can't be done in the same time as this change.  If
you'd like me to estimate it, please let me know.

Thanks,
Blake

**Comment by mnichols13** [comment]
okay, thank you.  It looks good, we can now see all the states.  If we decided we need the secondary change, we'll post a new Github.
