### ISSUE TITLE
Terms of Service agreement added to Free Trial Request

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#363]
Please provide an estimate.  We would like this completed by February 1 if possible. 

We would like to add a box to the Free Trial Screen at the bottom before the submit button.  This would be a terms of agreement form that the user would need to open, scroll through and mark a box agreeing to the terms.  Without agreeing the submit button for the Free Trial would not work.   
[FREE TRIAL Terms of Use.docx](https://github.com/MyCaert/Issues-Enhancements/files/10429458/FREE.TRIAL.Terms.of.Use.docx)

**Comment by bguerrettaz** [comment]
Estimate would be 4-5 hours.

**Comment by mnichols13** [comment]
we'll put this on hold for now and revisit at a later date.
