### ISSUE TITLE
Broken link to pricing tab

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#365]
From this page, https://mycaert.com/agricultural-lessons.asp

Customers receive a broken link to get to the pricing.  Is this something we can fix?

https://mycaert.com/pricings.asp

![image](https://user-images.githubusercontent.com/5790342/212956937-05778636-5693-479d-b9c1-f46ac7e1e02e.png)

**Comment by bguerrettaz** [comment]
This has been resolved.

Thanks,
Blake

**Comment by mnichols13** [comment]
thanks
