### ISSUE TITLE
Problems sending email to gmail addresses

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#367]
We are getting error messages when trying to send emails to good/known gmail addresses.  Here is an example.  Callie, Lindi and I have all experienced this in the past week.

This is an automatically generated Delivery Status Notification.

Delivery to the following recipients failed permanently:

* [lockwoodd300@gmail.com](mailto:lockwoodd300@gmail.com)

Reason: There was an error while attempting to deliver your message with [Subject: "RE: alignments for Middle School"] to [lockwoodd300@gmail.com](mailto:lockwoodd300@gmail.com). MTA [p3plwbeout27-01.prod.phx3.secureserver.net](http://p3plwbeout27-01.prod.phx3.secureserver.net/) received this response from the destination host IP - 142.251.2.26 - 550 , 550-5.7.26 This message does not pass authentication checks (SPF and DKIM both
550-5.7.26 do not pass). SPF check for [[caert.net](http://caert.net/)] does not pass with ip:
550-5.7.26 [216.69.139.46].To best protect our users from spam, the message has
550-5.7.26 been blocked. Please visit
550-5.7.26 https://support.google.com/mail/answer/81126#authentication for more
550 5.7.26 information. lp15-20020a17090b4a8f00b00219f65e19fcsi5522582pjb.170 - gsmtp

**Comment by bguerrettaz** [comment]
I think this one is on @Brian Peterlin ***@***.***> end as well.

**Comment by BrianPeterlin** [comment]
i updated the SPF, try now

**Comment by BrianPeterlin** [comment]
is this ok now?

**Comment by mnichols13** [comment]
seems to be okay now, thank you
