### ISSUE TITLE
Modify Rotating Banner on MyCaert.com

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#368]
Banner Images can be changed and should follow this format.

PNG File 980 x 352 pixels

Sample Atached

@LKocher @calliemcclay 
![banner04v2](https://user-images.githubusercontent.com/5776485/217699128-74fe659f-5481-4c3f-9aae-09f21830004b.png)

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***> - is this assigned to Darrell?  Want
to confirm so I don't miss the item.

**Comment by BrianPeterlin** [comment]
@bguerrettaz this is really for Callie at this point.  If she can provide us an updated graphic, we can update the site.

@calliemcclay, do you have an updated image?

**Comment by calliemcclay** [comment]
@BrianPeterlin @bguerrettaz we are working on it. Can I upload through the Admin portal under "Upload Banner Images"?

<img width="263" alt="Screen Shot 2023-02-24 at 11 39 08 AM" src="https://user-images.githubusercontent.com/100300840/221249712-2df2caeb-3613-4b90-80de-43bf5e62e0be.png">

**Comment by bguerrettaz** [comment]
Yes, I believe you should be able to.  Please let us know if you run
into any issues or if it doesn't work correctly.

Blake

**Comment by calliemcclay** [comment]
I uploaded them and they haven't shown up yet. Do you think it will take a while to change?
Also, we want to add another banner - I don't have the option to do that on my end.

**Comment by LKocher** [comment]
Let us know when the banners can be updated. @calliemcclay does need help with adding the fifth banner

**Comment by bguerrettaz** [comment]
I took a look at all of the backend code and it appears that it was only
built for 4 banner images.  So while the Banner Management --> Upload
Banner Images should work, it only allows 4 images.

Are you ok with 4 or do you want all of these pages to be changed to
support 5?

**Comment by calliemcclay** [comment]
Could you give us an estimate on how long it would take to add another banner image?

I tried to upload under Banner Management with 4 of them again, but it didn't work.

**Comment by calliemcclay** [comment]
No need to make the changes. I'll send you the 4 banners once approved.

**Comment by calliemcclay** [comment]
I’ve emailed the 4 banners to Blake, let me know if I can send anything else

**Comment by bguerrettaz** [comment]
Just to update this ticket, Callie and I spoke about the banner images and
Callie is working on new images without the 'more information' bubbles and
new links for the ones that require them.

Blake

**Comment by calliemcclay** [comment]
Here are the updated files - I've emailed them to Blake as well. Links are below
**Could we have access to edit the Sample Course Outline page listed under number 2? That page needs major updating.

1 (online assessments): https://www.youtube.com/watch?v=nUJT7jI6N9E 
2 (Standards-Based Lesson Plans): https://www.mycaert.com/sample-course-outline.asp
3 (E-Units & PPTS): https://mycaert.com/admin/authenticationCheck.asp?FN=030183&Locale=eUnits&Org=eUnits/030183.pdf 
4 (Google Classroom): https://youtu.be/QguJzxFkHpA 
![1](https://user-images.githubusercontent.com/100300840/228900340-0718c99b-5a7d-4a2f-ab64-2d7e439ec6dc.png)
![2](https://user-images.githubusercontent.com/100300840/228900342-ffbc5e62-edc9-486f-ae13-74b1c72f8599.png)
![3](https://user-images.githubusercontent.com/100300840/228900344-20d4d159-0a0b-4c7c-a6d6-d08749586757.png)
![4](https://user-images.githubusercontent.com/100300840/228900348-bb302acb-dffa-4266-93e5-7a79e72ad771.png)

**Comment by LKocher** [comment]
Please provide an estimate time when these updates can be complete

**Comment by BrianPeterlin** [comment]
@bguerrettaz , do you have an estimate on hours?

**Comment by BrianPeterlin** [comment]
@bguerrettaz, let's post the 4 and give them an estimate to add a 5th

**Comment by calliemcclay** [comment]
We just have 4 slides, don't need a 5th. Let us know if you need something else - I've sent over the images.

**Comment by BrianPeterlin** [comment]
@bguerrettaz, can you upload the 4?  I tried the console, but it does not work well with PNG images.

**Comment by bguerrettaz** [comment]
Yes, I'll try to get this done this week.

**Comment by calliemcclay** [comment]
I see they've been updated, thanks! But they don't have a transparent background, is there something else we need to provide?

**Comment by bguerrettaz** [comment]
Hi - yes, I've been working on this today and should be up and running.  I
believe you gave me transparent but its rendering it with a white
background?

**Comment by calliemcclay** [comment]
Hm, the ones I sent on email and on this feed show up with a transparent background on my screen.

**Comment by bguerrettaz** [comment]
Yeah I see them transparent when I download them too.  I'm not a graphics
guru so I really don't know what's going on or converting them to white
background.  I looked through the CSS and don't see anything there either.

**Comment by bguerrettaz** [comment]
I saw this out there:
https://www.quora.com/Why-does-my-PNG-have-a-white-background

Could you save the same images as both png's and jpg's as transparent and
let me try those?  I had to redo a lot of the sizing/links/etc. but I won't
have to do it all over again to just drop the new images.

**Comment by BrianPeterlin** [comment]
@bguerrettaz I think we need to allow it to accept PNGs.  When converting to JPEG we lose transparency capabilities.  Can you do that?

**Comment by BrianPeterlin** [comment]
Can this be completed by 5/30?

**Comment by bguerrettaz** [comment]
I've tried both the original pngs and jpegs, both have white backgrounds.

**Comment by calliemcclay** [comment]
Is there another way I can share the images? They are transparent on my screen in GitHub and when I sent them via email. I could share a Google folder? Let me know.

**Comment by BrianPeterlin** [comment]
[Archive.zip](https://github.com/MyCaert/Issues-Enhancements/files/11568656/Archive.zip)

**Comment by BrianPeterlin** [comment]
@bguerrettaz can we get this wrapped up by June 1st?

**Comment by calliemcclay** [comment]
Is there anything else needed on our end to load the images?

**Comment by bguerrettaz** [comment]
Just an fyi, we’re traveling until tomorrow afternoon so I will get as much of these tickets done before the 1st as possible.  Is there a priority order?Sent from my iPhoneOn May 26, 2023, at 9:15 AM, BrianPeterlin ***@***.***> wrote:﻿
@bguerrettaz can we get this wrapped up by June 1st?

**Comment by LKocher** [comment]
Ok. Priority:
#368
#369
#372
#384

**Comment by bguerrettaz** [comment]
Hi - I was able to find the issue with the background and have fixed it.
Please confirm.

Thanks,
Blake

**Comment by calliemcclay** [comment]
This is much better! The other "More Information" buttons are not showing up, are we able to add the ones I first created?

**Comment by bguerrettaz** [comment]
Hi Callie - I don't see any reference to more information in this ticket?
If we need to have more information on the image, we'll need to create the
images with that overlaid already.

**Comment by calliemcclay** [comment]
Do you want the buttons separate or in the banner image?

**Comment by bguerrettaz** [comment]
In the banner image itself would be best.  We'll want to make sure to
retain the transparent background so if you could zip the images and attach
that to the email, that would be great.

**Comment by calliemcclay** [comment]
Here you go - let me know if they need spaced differently.

**Comment by bguerrettaz** [comment]
It didn't attach to the ticket, could you send to my email instead?

**Comment by calliemcclay** [comment]
Yes - it's here, too.

[MYCAERT Website Carousels (5).zip](https://github.com/MyCaert/Issues-Enhancements/files/11614765/MYCAERT.Website.Carousels.5.zip)

**Comment by bguerrettaz** [comment]
These have been updated.

Thanks,
Blake

**Comment by calliemcclay** [comment]
Great, thanks Blake!
