### ISSUE TITLE
Change the Left Arrow

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#370]
On MyCaert.com

Change the Left Arrow from Take a Tour (http://www.mycaert.com/Video/) to a Request a Workshop (link to be provide)

Leave the Take a Tour tile above still point to http://www.mycaert.com/Video/

![image](https://user-images.githubusercontent.com/5776485/217700519-d3c5906a-422c-4fae-9460-9edf15ed0726.png)

Make the entire Agriculture Tile a Link, not just the view samples text
Make the entire Career & Technical Education Tile a link, not just the view samples text
Make the Middle Chevron: My Community (@calliemcclay to provide)
  Update that link from Sample Lessons to highlight MyCommunity
  Have samples of what’s available in MyCommunity where
  teachers can share assignments/worksheets/guided
  notes/teaching strategies
Right Chevron: What’s New
   Update landing page with Agribusiness guided notes, Middle School library, etc. @calliemcclay  to provide
![image](https://user-images.githubusercontent.com/5776485/217701496-2b2e9d80-f383-428a-b7c3-8b19ad51172d.png)

**Comment by BrianPeterlin** [comment]
@calliemcclay , can you provide the following

1. Request a Workshop - Forms Link
2. My Community - content needed
3. What's New - content needed or a link

**Comment by calliemcclay** [comment]
@BrianPeterlin @bguerrettaz 
Here is the request a workshop link: https://forms.gle/5Ugqgw4gce4bw1819
Is there a way we could have access to edit the My Community page and the what's new page? We would just be adding text and a couple images. 
We are wanting to keep the middle link to the Samples page, but change the content to MyCommunity.

**Comment by BrianPeterlin** [comment]
@calliemcclay are you able to provide us graphics for the three Chevrons?

**Comment by calliemcclay** [comment]
@BrianPeterlin only the text and links need changed on the chevrons. 
Left chevron - Request a Workshop (link is above)
Middle chevron - MYcommunity (link stays the same - we just need access to edit that page)
Right chevron - What's New (stays the same - we just need access to edit that page)

**Comment by bguerrettaz** [comment]
Hi - I will need images for both the new chevron's and the image above the
chevron's:
[image: image.png]
Take a Tour, View Samples (MyCommunity), etc. are all images.

I'm not sure how you want the middle image to go to MyCommunity as at this
point the user isn't logged in?

**Comment by LKocher** [comment]
no need for images for the chevron's, just need to change out wording, see @calliemcclay direction

**Comment by bguerrettaz** [comment]
Unfortunately the wording is baked into the image whenever it was created.
So I just need new chevron's with the updated working

Also, need to know about my questions on MyCommunity: I'm not sure how you
want the middle image to go to MyCommunity as at this point the user isn't
logged in?

**Comment by calliemcclay** [comment]
Ok, what is the image size needed?

The link needs to be: https://mycaert.com/content.asp?CID=9CDA291B0D09497BAB2AEA2806C7439B2CC171F034100867
We want access to edit this page and change the content. They won't login to MYcommunity - it'll just showcase what's included in MYcommunity. Does that make sense? We can schedule a phone call if needed.

**Comment by bguerrettaz** [comment]
Sounds good.  Here is the size of the current icons/images: [image:
image.png]

**Comment by calliemcclay** [comment]
The size or image isn't showing on my end, this is what it looks like. Can you share size again?


<img width="456" alt="Screen Shot 2023-03-15 at 8 41 53 AM" src="https://user-images.githubusercontent.com/100300840/225326598-2a6a8f33-a02f-4e1e-b7c3-3ce0776e4ec4.png">

**Comment by bguerrettaz** [comment]
No problem, here is the sizing:
![image](https://user-images.githubusercontent.com/5695475/225342930-3eece8b4-0432-440b-a592-5b343d30a2a4.png)

**Comment by calliemcclay** [comment]
Here are the chevrons - I did all three so they match. 
Left - Take a Tour: https://mycaert.com/content.asp?CID=BC68EDA199A19099932E4D44EF356A78FBEE300A4D4D1FA9
Middle - MYcommunity: https://mycaert.com/content.asp?CID=6FDBEC4B4DC68C998ED70D0350E45F639BC5BC5C08D8BB8A
Right - What's New: https://www.mycaert.com/content.asp?CID=9F4A88098427660AE1DD4EDB482B10F73AD013B0200EB634

![1](https://user-images.githubusercontent.com/100300840/228952648-e6f77ab2-77c8-424f-9c0d-cb228a28ef5a.png)
![2](https://user-images.githubusercontent.com/100300840/228952654-3f325c91-e9a8-49ab-bad0-9cbb93b7f3ea.png)
![3](https://user-images.githubusercontent.com/100300840/228952657-93c0091d-eece-4e20-9f43-ec51238453d1.png)
![4](https://user-images.githubusercontent.com/100300840/228952659-a0df3f8e-489d-40ca-9591-3e7dcfc461e0.png)
![5](https://user-images.githubusercontent.com/100300840/228952662-5353ebe7-138c-42ff-90a2-bcffc334c15c.png)
![6](https://user-images.githubusercontent.com/100300840/228952666-7f0bcc78-7365-4e69-9efa-729c8cd19253.png)

**Comment by bguerrettaz** [comment]
Hi - I was able to transfer all of these images over and make the necessary
changes.  Can you please test and confirm?

Thanks,
Blake

**Comment by calliemcclay** [comment]
Should I send them again with a white background so it doesn't have a black outline?

**Comment by calliemcclay** [comment]
They have a black outline - should I send again with a white background to fix that?

**Comment by bguerrettaz** [comment]
Hi - yes, white or transparent background.

**Comment by calliemcclay** [comment]
Great - let's try these.

![1](https://user-images.githubusercontent.com/100300840/230098950-500f26f2-de6b-4cfe-977f-ffdab2ded8ad.png)
![2](https://user-images.githubusercontent.com/100300840/230098953-47baa6f4-be85-4e2c-9791-5c53aa400d72.png)
![3](https://user-images.githubusercontent.com/100300840/230098954-584bf64c-b608-4024-ad18-f1eb7bdfa261.png)
![4](https://user-images.githubusercontent.com/100300840/230098955-6c48037d-4549-4a2f-9cad-c1b274e7f69a.png)
![5](https://user-images.githubusercontent.com/100300840/230098957-edd11ff3-7ab0-4da6-93f7-846d816c23bb.png)
![6](https://user-images.githubusercontent.com/100300840/230098959-5fbc39ec-4b5f-4133-a15e-970daf9718a4.png)

**Comment by bguerrettaz** [comment]
This is complete.

Thanks,
Blake
