### ISSUE TITLE
Site Footer Update

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#371]
Make the footer similar to to this for MyCaert.com, Teachers Logged In, Students Logged In
![Picture1](https://user-images.githubusercontent.com/5776485/217703819-80838662-6df3-4840-b5e6-7c5690f8c46c.png)

@calliemcclay  can provide needed links

**Comment by calliemcclay** [comment]
CEC logo should link to cuttingedgecurriculum.org 
MYCAERT logo should link to home page of mycaert.com
Facebook icon: https://www.facebook.com/mycaert.cec
Instagram icon: https://www.instagram.com/mycaert.cec/
YouTube icon: https://www.youtube.com/@mycaertbycec
**You can delete "Support" it's not needed**
Contact Us: https://mycaert.com/contact.asp
Terms of Use: https://mycaert.com/ContentFiles/110201791542AM.pdf
SOPPA Contract: https://mycaert.com/ContentFiles/5272021105807AM.pdf
Our Team: https://mycaert.com/content.asp?CID=48F994F5B0D7C8D88F195040B95BFB77023C7F0623CFC3F1
Career Profiles: https://www.mycaert.com/career-profiles/
Take a Tour: https://www.mycaert.com/content.asp?CID=BF48624C7594D613FBB13F4AA0FBED6C3328A5BE95DF4877
^^This header needs fixed on the "Tutorial and Take a Tour" page
Request a Quote: emailto: mnichols@caert.net Subject line: Request a MYCAERT Quote
Request a Free Trial: https://www.mycaert.com/free-trial-request.asp
View Agriculture Samples: https://www.mycaert.com/agricultural-lessons.asp
View CTE Samples: https://www.mycaert.com/cte-lessons.asp

Fonts: Bebas Neue (header) Montserrat (body)
Let me know if there's anything else I can provide with the footer!

**Comment by BrianPeterlin** [comment]
blake, @calliemcclay  can provide graphics, if you need any

**Comment by LKocher** [comment]
need to know status on this update

**Comment by bguerrettaz** [comment]
Ok, I believe I have most of all of this completed.  I. I have
implemented the new footer for non-logged in (mycaert.com), teachers and
students.

The only thing I believe I'm missing is the social media icons, can you
please send me the ones you'd like to use in the proper size?

Please let me know if you see anything missing, incorrect, etc.  If you
would like to change the background color, please let me know the hex code
of the color you'd like.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
Hi - I'm only seeing the blue facebook icon, but I think you want white
based icons?  If its easier, can you please send the three icons to my
gmail?  ***@***.***

**Comment by calliemcclay** [comment]
I emailed the social media icons yesterday - please let me know if you don't receive them. 
As for the footer... the color seems a bit harsh and doesn't match the rest of the page. Could you make it the same blue at the top of the MYCAERT home page? Looks like HEX: #093866
The font (Times New Roman?) seems off, could you try using Montserrat? If not, could you try a sans serif font?
I also noticed after clicking around, the items in the footer become underlined - is this something we can change? I've included screenshot below. 

<img width="319" alt="Screenshot 2023-03-16 at 8 40 44 AM" src="https://user-images.githubusercontent.com/100300840/225635115-70dcabe7-ed16-4882-9f32-aa50769601fc.png">

**Comment by bguerrettaz** [comment]
All of these have been corrected and/or changed.
-Social media icons complete
- Footer color change complete
- Font changes complete
- Underlined removed complete

Please confirm

Blake

**Comment by calliemcclay** [comment]
Thanks Blake. The font and color is better, but the spacing seems very tight. Could you increase the space between each link?
The social media icons also seem to appear a little fuzzy and not square. Could you fix this? Let me know if you need new images. 
Also, the underlining still seems to be happening - screenshot below. 

<img width="345" alt="Screen Shot 2023-03-17 at 10 06 44 AM" src="https://user-images.githubusercontent.com/100300840/225943662-73f6e259-838f-4d98-b56a-8ff5ef8a5460.png">
<img width="205" alt="Screen Shot 2023-03-17 at 10 06 54 AM" src="https://user-images.githubusercontent.com/100300840/225943713-6a3b98c0-721c-4e10-b63b-a25c09ff69bc.png">

**Comment by bguerrettaz** [comment]
Hi - I've increased the padding on all of the links and tried another
method to remove the underline.  Can you check now?

Also, I had to scale down those social media icons because they were very
large.  Could you give me icons of the size you'd like to see?  Otherwise,
if I have to scale, they'll get blurry.

Blake
