### ISSUE TITLE
Add link to Cutting Edge website

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#375]
Can we add a link to cuttingedgecurriculum.org to the CEC logo on the top left page on mycaert.com? Is this an easy add?
There should also be a link to the CEC website in the footer once that's updated.

<img width="466" alt="Screen Shot 2023-03-01 at 1 37 06 PM" src="https://user-images.githubusercontent.com/100300840/222245976-cc8816ff-2396-4ff6-b8c8-f4942b06b07f.png">

**Comment by bguerrettaz** [comment]
This is complete.  Please test logged in and logged out to assure you are
good with the functionality.

Blake

**Comment by calliemcclay** [comment]
It works, thanks Blake!

**Comment by calliemcclay** [comment]
@bguerrettaz just realized that the link to CEC website is also embedded in the "MYcaert v. 2.0" logo - can you change it to where the CEC logo links to CEC website and the MYcaert logo links to MYcaert home page?

**Comment by bguerrettaz** [comment]
Hi - this is complete for non-logged in, teachers and student header
images.  All should be correct now.

Please let me know if you see any issues.

Thanks,
Blake

**Comment by calliemcclay** [comment]
Looks good, thanks Blake!
