### ISSUE TITLE
Edit Content

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#377]
Callie, 

Lindi mentioned you wanted to edit content on some of the pages on mycaert.  Was it "What's new?"

Please let me know

**Comment by BrianPeterlin** [comment]
@bguerrettaz, do you know why What's New page does not show up in the editor?  https://www.mycaert.com/content.asp?CID=162009975981213B6934C2BA9C6F8332FCAE243C2FCA3D12

@calliemcclay, you can edit Sample Lessons by going here https://www.mycaert.com/admin.  You will be able to do the same with What's new, once blake fixes it.

Login: cmiti.com
Password: itimc

click Edit content
click Edit next to the Sample Lesson Page
![image](https://user-images.githubusercontent.com/5776485/225455956-06f7a665-553d-4a16-b4f1-9cd0560d46e9.png)

**Comment by bguerrettaz** [comment]
This has been fixed.
 Please confirm.

Thanks,
Blake
