### ISSUE TITLE
Middle School libraries not displaying correctly (reopened Jun 13)

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#378]
For both the Indiana Middle School 5E and the National Middle School 5E, the pages are not displaying correctly.    We recently finished entering the standards and it does not appear that the standards display is "wrapping".  see my screenshot - see A1-3

![image](https://user-images.githubusercontent.com/5790342/222749778-9c22e520-c574-42d9-9748-d78be344e8cc.png)

**Comment by bguerrettaz** [comment]
I was able to find the issue and correct it.  Please test and confirm.

Blake

**Comment by mnichols13** [comment]
I see no difference, not fixed.

**Comment by bguerrettaz** [comment]
What page(s) are you on where its not aligning?  I'm not seeing any issues
when I looked over several pages?
[image: image.png]

Could you walk me through how you get to the spot that doesn't look correct?

**Comment by mnichols13** [comment]
Click on the lesson library.
Choose problem area A.
Page that lists the lessons displays this way.

**Comment by mnichols13** [comment]
@bguerrettaz were you able to recreate and see the issue in problem area A

**Comment by bguerrettaz** [comment]
I found the issue and fixed it for this instance.  Unfortunately, these are
all individual state pages, so while its fixed for IN, if you encounter a
similar issue for another state, we'll need to fix each state that has the
issue.

Thanks,
Blake

**Comment by mnichols13** [comment]
It is not fixed.   And as mentioned in the original description: For **both the Indiana Middle School 5E and the National Middle School 5E,** the pages are not displaying correctly.    

Feel free to login and look at how the page displays   I have re-activated your Mycaert account so that you can review these on the teacher pages.  

username: bguerret
pw: yessir1

**Comment by bguerrettaz** [comment]
That's a great example.  The one I fixed was IN, the other was IL.  Both
are fixed now.

**Comment by mnichols13** [comment]
thank you.

**Comment by mnichols13** [comment]
Middle School 5E not displaying correctly in Missouri
teacher Brent Wright in MO

example of page when you click on any lesson 

http://www.mycaert.com/Teachers/course-outlines/lesson-plan-library/CD_SelectLessons_MO.asp

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/1c6592cb-ff74-4b3e-a0cd-3367087261d4)

**Comment by bguerrettaz** [comment]
This should be resolved.  please test and confirm.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks better
