### ISSUE TITLE
Change wording from CAERT, Inc to Cutting Edge Curriculum, Inc.

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#379]
When teachers post to the MY Community page, we need the wording changed on this page from CAERT, Inc. to Cutting Edge Curriculum Inc.
https://www.mycaert.com/Teachers/course-outlines/lesson-plan-library/MyCommunityPost.asp

![image](https://user-images.githubusercontent.com/5790342/224144982-cf9e2863-3381-444c-9aa4-26a8e66603b5.png)

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
thanks.
