### ISSUE TITLE
Change wording from "CD title" to "Library title"

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#380]
On Ag & CTE sample lesson pages, it says at the top, "Expand the CD Title below.."
Can you change to "Expand the Library Title below..."
This is on both Ag and CTE sample lesson pages. Screenshot below

<img width="396" alt="Screenshot 2023-03-16 at 8 56 37 AM" src="https://user-images.githubusercontent.com/100300840/225639765-34844b1f-0e1d-4e90-b9a6-48db164b7941.png">

**Comment by bguerrettaz** [comment]
This is complete.
