### ISSUE TITLE
Hide "Blog" tab

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#381]
Can we hide the "Blog" tab for now? Don't want to delete all together, just hide. 

<img width="1014" alt="Screenshot 2023-03-16 at 8 59 59 AM" src="https://user-images.githubusercontent.com/100300840/225640810-2703ae7a-f9da-4812-92ba-fce2128e21d3.png">

**Comment by bguerrettaz** [comment]
This is complete.
