### ISSUE TITLE
FREE TRIAL CHANGES

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#382]
We would like to make three changes to our free trial requests.   
1. Please remove all of the red text. 
![image](https://user-images.githubusercontent.com/5790342/226442117-e4d80e21-bc95-4803-a521-53e3e9d8ba72.png)

2.  Hide the box showing the lesson libraries available.  We are going to implement a free trial library instead.  
3.  Change the last item on the page 
from:   Yes, I would like to schedule a personal tutorial. Please indicate in the comments box the best time to contact you.  
to         Yes, I agree to phone tutorial of the Mycaert website.  I have provided my available day/time in the comment box above.

**Comment by bguerrettaz** [comment]
These changes are all complete.  I sent a trial request, please confirm
that looks good as well as the free trial page.

Thanks,
Blake

**Comment by mnichols13** [comment]
We are close to where we want to be.   After talking it through this morning.  Wondered about two more things. 

1.  Removing under referred by:   Received one of your emails and Saw a Facebook AD
2. Adding a REQUIRED box with this text: 
FREE TRIAL Terms of Use
Access to all materials in Mycaert.com is available via online subscriptions. Unless otherwise
noted, all materials (lesson plans, E-units, PPTs or test questions) on MYcaert.com are copyrighted by Cutting Edge Curriculum, Inc.( dba CAERT, Inc.). 
It is unlawful to download or use our materials beyond the FREE TRIAL time period given to you.   It is unlawful to share materials (lesson plans, E-units, PPTs or test questions) with non-subscribers via electronic means.  All customers/teachers and/or administrators are responsible for the maintenance and personal security of their logins.
Cutting Edge Curriculum, Inc. (dba CAERT, Inc.) reserves the right to refuse and/or terminate the subscriptions of those subscribers who violate our copyright.

**Comment by bguerrettaz** [comment]
Hi - these changes are now complete and I've added a new required field
where the user must check the box for free terms of use acceptance.

Please review and let me know if there are any other changes.

Thanks,
Blake
