### ISSUE TITLE
Can't change title on brochure - under Help tab

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#384]
We've uploaded the 2023 Brochure under the Help tab, but it won't let us change the title. I can go in and edit, but there is no where for me to click save or finished. Screen shot below

![Screen Shot 2023-03-31 at 9 56 37 AM](https://user-images.githubusercontent.com/100300840/229156650-df247eca-c7ee-42e1-bf2c-b3afd8ea2698.png)

**Comment by bguerrettaz** [comment]
For this, change the title, then to proceed, click 'Photos', then 'Downloads', then it will save once submitted:
![image](https://user-images.githubusercontent.com/5695475/229959860-ec6e0b14-aa41-4b14-8950-8f718c0ddf4f.png)

**Comment by calliemcclay** [comment]
That's not working on my end.

**Comment by calliemcclay** [comment]
@bguerrettaz can you change the title specifically to "MyCAERT Brochure"?
Thank you!

**Comment by BrianPeterlin** [comment]
goal is to complete by 6/1

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

Blake

**Comment by calliemcclay** [comment]
Can you please capitalize "CAERT" in MyCAERT? Otherwise, it looks great!

**Comment by bguerrettaz** [comment]
Hi - this is complete.

Thanks,
Blake
