### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#385]
New tagging:

<script async src="https://www.googletagmanager.com/gtag/js?id=G-E9CCL5YZFT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-E9CCL5YZFT');
</script>

![image](https://user-images.githubusercontent.com/5776485/232261389-c6f5981f-b4e8-48d7-9de0-1f50277d9003.png)

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***> what pages does this need to go on?

**Comment by calliemcclay** [comment]
@BrianPeterlin Can this report be made available to us monthly?
