### ISSUE TITLE
Sample Lessons - Broken Links

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#386]
Getting this message "Error 404 - Page not Found" on all links leading to the Ag Samples and CTE Samples page. 
Need fixed ASAP - presenting at a workshop this week. 

Links: http://www.mycaert.com/agricultural-lessons.asp
http://www.mycaert.com/cte-lessons.asp 

![Screen Shot 2023-04-18 at 9 48 00 AM](https://user-images.githubusercontent.com/100300840/232815491-edbc12cc-3f53-4223-b4ab-009a8d90be76.png)

**Comment by bguerrettaz** [comment]
I have fixed this, we shut this file off during all of the issues but don't
believe they contributed to the overall issues.  These are enabled now.

Blake

**Comment by calliemcclay** [comment]
Thank you!
