### ISSUE TITLE
Creating a Quiz as a Missouri teacher - fix broken links, menus

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#391]
Requested completion by July 10th: 

Three new items for **Missouri** that are all associated with creating a quiz. 
(1) Please remove the top option for adding quiz questions - highlighted item in screenshot
https://www.mycaert.com/Teachers/csat/EditQuiz.asp?TestID=125570
"NEW SELECT BY MISSOURI COURSE COMPETENCY" 
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/d11a3ded-8131-457f-a3a9-21a75fbdc0b4) 

(2) Change this option to Select by Standards, (remove Common Core)
https://www.mycaert.com/Teachers/csat/EditQuiz.asp?TestID=125570
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/b6967be4-e8ce-4edb-bd7d-e1a9bf179bf3) 

(3) Remove items 3 & 4 as highlighted, change the wording on #5 to Missouri Learning Standards instead of Missouri Expectations.
https://www.mycaert.com/Teachers/csat/MO/AddTestQuestions_QuestionBank.asp?TestID=125570#CommonCore
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/31b2c008-23ba-43cd-9e6b-ee918af94869)

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
@bguerrettaz  - I see that you completed one of the three items in this request.   Please review the 2nd and 3rd items and let me know if you have questions.

**Comment by bguerrettaz** [comment]
Hi - items 2 and 3 are now complete.

Thanks,
Blake
