### ISSUE TITLE
Add/Edit State Email Message for new Teachers

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#392]
This does function of sending an automated email does not work.  When adding a new teacher there is a box at the bottom that we can check.  The saved email message should go to the teacher.  This could be a nice time saver for us.   Please provide an estimate to fix. 
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/dbfb0e73-59bb-4533-a4b5-398a4c166350)

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/ebab027d-3cd6-4969-b458-73011a4f0536)

**Comment by bguerrettaz** [comment]
So it doesn't appear that this was designed to send email, just serve as a
template builder for email messages.  When looking through the code, it is
designed to add/edit email messages (templates) and store those in the
database.  There is no sending pages or code anywhere related to these.

Please advise.

Blake

**Comment by mnichols13** [comment]
no problem, thanks for looking
