### ISSUE TITLE
ERROR when bulk add students on website

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#393]
Request fix July 25,  2023 @BrianPeterlin @bguerrettaz  

As school starts next week for many teachers, this is a high priority.   When using the add students - bulk email link this error message appears:

teststudent@gmail.com

Persits.MailSender.4 error '800a000e'

AspEmail's premium features have expired. To continue using them, please visit www.aspemail.com to purchase a registration key.

/Teachers/students/SubmitMultipleStudents_BulkEmails.asp, line 137

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***> - this one is you I think.

**Comment by mnichols13** [comment]
looks better
