### ISSUE TITLE
AG Samples link doesn't work today - needs fixed ASAP

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#394]
@bguerrettaz @BrianPeterlin   URGENT - PLEASE FIX ASAP.  LINK DOES NOT WORK

ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/Includes/Inner_header.asp, line 78

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/770dbccc-c4b0-4eae-847c-934caae13d0a)

**Comment by bguerrettaz** [comment]
These links are all working for me:

[image: image.png]

**Comment by mnichols13** [comment]
ok, must be a caching issue for my one browser?  I have no idea...
