### ISSUE TITLE
Availability of quizzes from previous subscription available - should not be accessible

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#396]
@bguerrettaz @BrianPeterlin I have an IL teacher, Steve Sargeant who previously had access and has created a large number of quizzes.   Since IL State Board stopped paying for IL teachers, most do not use our system anymore.  Today we received an order for the newer Middle School library from him.  I set him up for access only for Middle School library and test questions, however when I went into his account and checked, he can still access all of the old quizzes.   **This needs to be corrected.**  He should not be able to access these when there are no checkmarks on the admin page next to the lesson libraries that he created these quizzes from.   His account is username:  SSargeant pw: Paige

**Comment by LKocher** [comment]
@BrianPeterlin we will need to discuss

**Comment by BrianPeterlin** [comment]
can you please send me a screen shot where you are seeing ALL Questions?

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5776485/32ee6bfc-ca85-4f1c-8401-56f60ad54798)


![image](https://github.com/MyCaert/Issues-Enhancements/assets/5776485/f5646a0a-60f9-473e-8730-eb711b7155d9)

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5776485/90c65b96-e503-48d1-ab14-a44106e2f7fe)

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5776485/1252722b-e0b4-4695-8d05-c631f1ba6f30)


once a quiz questions gets stored to their personal quiz library it is like we made a photo copy of it.  There is not a way to delete the copies the way it is currently designed.

**Comment by BrianPeterlin** [comment]
In Steve's case, he pulled questions from the bank.  Unfortunately, when the bank question gets copied to quiz, it does not store the associated library where the bank question originated from, so we can not delete the questions from the quiz.

The ability keep the association would require a significant amount of new functionality.

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5776485/ad138bfd-5800-479d-8251-6dc185eee28e)

**Comment by LKocher** [comment]
<img width="565" alt="image" src="https://github.com/MyCaert/Issues-Enhancements/assets/121973021/398c752f-4ffc-4733-b9e1-e4431e3ef960">
When you select "Add Questions by Course Outline"

**Comment by LKocher** [comment]
@BrianPeterlin - a glitch like this is something we need to add to our list when considering upgrades to the website

**Comment by mnichols13** [comment]
@BrianPeterlin how do we get to these General State Courses to keep them from showing up?  Is there a place on the Admin Console that I can do this? 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Mindy\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Mindy\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



ILadmin
--




</body>

</html>

**Comment by mnichols13** [comment]
@BrianPeterlin we tried this section - but it didn't work 
![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/fa0b7ce2-a32e-4a56-97b2-eb6abb055448)

**Comment by BrianPeterlin** [comment]
@bguerrettaz 

I see an issue

Loging as 

bppeterlin 
logoff12
IL

goto: https://www.mycaert.com/Teachers/csat/AddQuestionsCourseOutline.asp?TestID=125747

These question should not be accessible.  Maybe they should not exist at all????  They appear to be old questions.  This might be old data and logic.

**Comment by bguerrettaz** [comment]
Yes, it appears that this is old logic/data.  Should this link be removed
completely?
