### ISSUE TITLE
Cannot change students grade

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#397]
We have a teacher trying to fix their student's grade level under the My Students tab -> Edit Students, and it will not save their changes. 

This needs to be fixed ASAP. Thanks!

**Comment by calliemcclay** [comment]
Any update on this issue?

**Comment by bguerrettaz** [comment]
Hi - I just tested this with a couple of students and it worked correctly
for me.  If this is still occurring, can you please tell me the teacher and
student that is encountering the issue?

**Comment by bguerrettaz** [comment]
Hi - I have corrected the issues in the code and tested.  All looks to be
working now.  Please test and confirm.

Thanks,
Blake

**Comment by calliemcclay** [comment]
Fixed, thanks!
