### ISSUE TITLE
Cloudflare message - FIX ASAP

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#398]
Hello, we're have a teacher and all of his students getting Cloudflare messages when trying to login to MyCAERT. 
I have suggested he clear his cookies or cache and try again, waiting on update. 

Please fix asap! Schools will officially be back in session on Tuesday and we do not want any Cloudflare issues. 

Thanks!

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***>

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***>

**Comment by BrianPeterlin** [comment]
can he send the exact error number they are getting?

**Comment by calliemcclay** [comment]
This is the screenshot of the message he's getting. Him and his students are all getting this message - but only at home. 
He's going to talk with his local internet provider to see if they can help, too. 

![Screenshot 2023-09-01  170131](https://github.com/MyCaert/Issues-Enhancements/assets/100300840/8cede5ee-044f-4e91-bcbe-6dcc5be7f0b3)

**Comment by BrianPeterlin** [comment]
have him use this direct link

http://199.255.165.17
