### ISSUE TITLE
Changing the wording on the Account Expiring 30 day pop up notice

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#399]
Looking for an estimate to change the wording on the 30 notice pop up - Please advise what the charges would be

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/b004befa-13dd-43ba-8c0e-1a23cda27a94)

**Comment by bguerrettaz** [comment]
Just half of an hour.

**Comment by bguerrettaz** [comment]
This is complete.

**Comment by mnichols13** [comment]
thanks!  Looks good
