### ISSUE TITLE
Search by Lesson Key word search blowing an error message

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#400]
Keyword search is not working - teachers are asking when it will be back up.  Please advise ASAP

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/dd1d55e7-a8a4-4e33-9f5a-bd7edae1867e)

**Comment by bguerrettaz** [comment]
This is working now.  I rebuilt the index and tested.

Blake

**Comment by mnichols13** [comment]
great - thank you for your help.
