### ISSUE TITLE
Updating documents to MyCAERT Footer

### ISSUE THREAD

**Issue by calliemcclay** [MyCaert/Issues-Enhancements#402]
Hi! Can you please update the SOPPA Contract and Terms of Use links in the footer of mycaert.com ASAP?
Files are attached. Thanks!
[CEC_Terms_of_Use_03.04.2024.pdf](https://github.com/MyCaert/Issues-Enhancements/files/14496782/CEC_Terms_of_Use_03.04.2024.pdf)
[CEC_SSDPA_03.04.2024.pdf](https://github.com/MyCaert/Issues-Enhancements/files/14496783/CEC_SSDPA_03.04.2024.pdf)

**Comment by bguerrettaz** [comment]
Hi - this is complete.

Blake

**Comment by LKocher** [comment]
Done
