### ISSUE TITLE
Inquiry regarding allowing MO teachers to change their school 

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#406]
I would like an estimate on adding the ability for Missouri teachers to change their school in EDIT PROFILE.  We made this change in IL several years ago.  @bguerrettaz did you recall doing this?   The page in IL looks like this: 

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/d0a5af84-bd20-47fb-946a-6ef9287744a8)

The issue will be that some schools subscribe to extra libraries and we don't want them to take the libraries with them.   The subscription would have to stay with the school.  Please provide an estimate on if this is possible and how long it would take.

**Comment by bguerrettaz** [comment]
Aren't you able to already change the school for MO teachers?  Here is what
I see on the admin side:
[image: image.png]

**Comment by mnichols13** [comment]
only IL teachers can change their school - not Missouri

![image](https://github.com/MyCaert/Issues-Enhancements/assets/5790342/2cea7b86-6f27-481b-a65e-b7d00dce1d03)

**Comment by mnichols13** [comment]
@bguerrettaz reminder on this quote request.

**Comment by bguerrettaz** [comment]
I’d estimate 7-9 hours to make this change for MO teachers.Sent from my iPhoneOn May 6, 2024, at 7:04 AM, mnichols13 ***@***.***> wrote:﻿
only IL teachers can change their school - not Missouri
image.png (view on web)

**Comment by mnichols13** [comment]
The big difference between IL and MO is that IL always had access to everything.  This is not the case for MO, they only have limited access.  We have a few schools - less than 20 that pay for extra libraries.   We would need for the paid libraries to stay with the school and not go with the teacher.  Is this possible?  And does this add to the estimate ? Or do either of you have an idea on how we could do this differently ?  @bguerrettaz @BrianPeterlin

**Comment by mnichols13** [comment]
thank you for the estimate, I think we will go in a different direction on this.
