### ISSUE TITLE
Track a user's IP address - Reopened on Nov 13th with new request

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#407]
@BrianPeterlin @bguerrettaz We would like a quote for you to explore the possibility of tracking a particular user's login to an IP address.   This is just one Indiana user that we suspect may have plans to share the login over the summer and we would like to keep a close eye on this.   Please provide a quote and how quickly you could have this complete.

**Comment by LKocher** [comment]
We are going to use it to confirm the account is only being opened by the teacher who is the subscriber. What would it cost to track and individual subscriber weekly from May 20-July 27?

**Comment by bguerrettaz** [comment]
I'd need to put in the IP tracking, then log it in the database.  Then
write a report from May 20th-July 27th.

I'm estimating 6-7 hours for that.

Blake

**Comment by LKocher** [comment]
Proceed. Let me know when you need the specific subscriber

**Comment by bguerrettaz** [comment]
Hi - I have completed the code and database sync for the new IP address
functionality.  I'm assuming you want to report of a certain individual on
July 28th?

**Comment by LKocher** [comment]
Yes, do need username or email address

**Comment by bguerrettaz** [comment]
Both, but if you could include that in this ticket on July 28th or so, that
would be good.  I don't need it right now.

**Comment by mnichols13** [comment]
@bguerrettaz Would it be possible to get this information a total of three times on/before July 28th?  We are thinking possibly wk of June 3, wk of July 1 and then final on Aug 1 .  Thanks!

**Comment by bguerrettaz** [comment]
Yes, I can do that.  What is the information you want to see in the
report?  Also, what is the username?

**Comment by mnichols13** [comment]
List of IP addresses if more than one - dates if more than one - 
username:  mjohn2@ivytech.edu

**Comment by mnichols13** [comment]
@bguerrettaz do you have an update/information for us?

**Comment by bguerrettaz** [comment]
Yes, here are the results since we've implemented IP tracking:

<img width="479" alt="image" src="https://github.com/MyCaert/Issues-Enhancements/assets/5695475/0dbf9ea4-c7a4-4a7f-8ea2-2c730fc301f6">

The first IP address is a modern IP, the second is an older version.  So since we've started tracking, this user has only logged in three times from two different locations, both from Indiana from me looking them up.

**Comment by mnichols13** [comment]
@bguerrettaz 
please send us another report by the end of the week.  
List of IP addresses if more than one - dates if more than one -
username: [mjohn2@ivytech.edu](mailto:mjohn2@ivytech.edu)

**Comment by bguerrettaz** [comment]
Here is the newest report:
<img width="434" alt="image" src="https://github.com/user-attachments/assets/9fccc731-306c-4442-9f08-394ccdad74e4">

Looks like three total IP's across June and July.

**Comment by mnichols13** [comment]
Thanks Blake !

**Comment by mnichols13** [comment]
@bguerrettaz  we have four logins set up in the state of South Carolina for the state to do end of year testing.  We are suspicious that these logins have been shared freely among other teachers in the state.  Can you please provide a report with IP addresses that have logged in to these four accounts from the time period of Oct 29, 2024 to present day? 

State:  South Carolina

School: Ag Mechanic and Tech EOP School
Username: agmecheop
Password:  rolodex

School:  Environmental & Natural Resources Management EOP School
Username: enreop
Password:  rolodex

School: Horticulture EOP School
Username: horteop
Password:  rolodex

School: Plant & Animal Systems EOP School
Username: p&aeop
Password:  rolodex

**Comment by bguerrettaz** [comment]
Please see this report for a listing from October 29th-Now.

I have sorted by login ID.

Thanks,
[LoginReport_111824.csv](https://github.com/user-attachments/files/17808681/LoginReport_111824.csv)

Blake
