### ISSUE TITLE
Error message on a Quiz

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#413]
@bguerrettaz  Please look at this weekend! 

In IL - teacher Michelle Wiseman
Quiz name:  **Understanding the Stages of Pork Production.**  
When the student - Peyton Garris tries to open this a rather lengthy error message appears:

I was also able to replicate, I also tried to recreate the quiz and got the same error

![image](https://github.com/user-attachments/assets/f37859f6-5a1b-4052-913d-ceb755d63a48)

**Comment by bguerrettaz** [comment]
@Brian Peterlin ***@***.***> - this appears to be an issue with
disk space.  Can you take a look and allocate more?

**Comment by mnichols13** [comment]
adding disk space solved this.
