### ISSUE TITLE
Search by Vocab Terms

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#6]

**Comment by dpentony** [comment]
Can you check to be sure the vocab search is working for recently uploaded lessons? For example, we recently posted a lesson from Culinary Arts. It is CA:C2-1. If you do a search for some of the lesson's key terms such as  cross contamination or potentially hazardous foods, the search results do not list that lesson (CA:C2-1). So, it looks like the indexing may not be updating as we upload new lesson plans.

**Comment by bguerrettaz** [comment]
Yes, the index was out of date.

I re-indexed everything and setup a job to run every night at 2am to make
sure we are updating regularly.

Let me know if you have any other issues.

Blake

**Comment by dpentony** [comment]
Hmmm.... Could it be taking a while for it to update. The terms "cross contamination" and "potentially hazardous foods" are in CA: C2-1. When I enter them in the search, lesson CA:C2-1 does not show up in the results.

**Comment by bguerrettaz** [comment]
There were two indexes, it was pointed at the old one.  Please try again.

**Comment by dpentony** [comment]
Now it works. Thanks.

**Comment by dpentony** [comment]
I do not believe the indexing is occurring on a regular basis. We uploaded an entirely new library a month ago. It was the Ag Power (PSTS) library. However, the vocab search does not list it in the search results.

See your comments from above you made on Jan. 14:

"Yes, the index was out of date. I re-indexed everything and setup a job to run every night at 2am to makesure we are updating regularly."

**Comment by bguerrettaz** [comment]
I have reindexed everything.  I also checked the job and it was in a
'stuck' stage.  Please retest.  If you see this issue again, we'll have to
schedule the job in a different way.

Blake

**Comment by dpentony** [comment]
Looks good.

**Comment by dpentony** [comment]
WE do not think the search by vocab term is updating as we add new lessons and libraries. We recently added a library on Cyber Security and none of the lessons show up when we do a vocab search.

**Comment by mnichols13** [comment]
Do you have an update on this issue?

**Comment by bguerrettaz** [comment]
Yes, the job was 'stuck' and hadn't ran for a while.  I've researched the
error code and its a known bug with task scheduler.  There was a workaround
and I'm working on implementing that.  Should be done tonight.

Thanks,
Blake

**Comment by bguerrettaz** [comment]
This is complete.  It ran and 226 files were added to the index.

It is scheduled on Monday's at 2am.

Thanks,
Blake
