### ISSUE TITLE
REOPENED Need new graduation year to add 7th grade students

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#69]
We have a teacher who is teaching at the Jr High level that we requested we add 2020 to the class options when adding a student. 

thanks.

**Comment by mnichols13** [comment]
Blake - please add graduation years through 2025.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.

**Comment by dpentony** [comment]
@mnichols13 - if all looks good, please let the teacher know (David Swanson - MN) and close the issue.

**Comment by mnichols13** [comment]
looks good
