### ISSUE TITLE
Unable to cut and paste from Word: Creating a Quiz - type own question

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#72]
We had a teacher contact us trying to create a quiz, but is having difficulties with the cut and paste. 

I know that we used to be able to cut and paste from Word when creating a quiz - Type own question.  Now it is not working. I tried it on my account as well -  I even tried to use the eraser icon - clean - still gives me the error message: 

ERROR: The Question you entered exceeded the maximum 8000 characters allowed.  Please try again.

**Comment by dpentony** [comment]
It was later determine that the issue is with how MACs copy and paste from a Word document. The workaround for MAC users is to: When pasting into MyCaert, they will need to paste with the following keys (Shift+Command+Option+V).  This is different than the normal pasting in Mac (Command + V).
