### ISSUE TITLE
Copy Teacher does not work on ADMIN page

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#76]
I am trying to enter 19 student teachers - I tried using the copy teacher function and get this error message:  

SELECT State, RegionID, SectionID, Region, [Section] FROM tblStateFilter WHERE (State = 'PA') AND (RegionID = 0) AND (SectionID = 0)
ADODB.Field error '800a0bcd'

Either BOF or EOF is True, or the current record has been deleted. Requested operation requires a current record.

/admin/Teacher/AppendTeacher2.asp, line 131

**Comment by mnichols13** [comment]
I am trying to add KSU teachers, when I click copy, the only information that it saves is the activation date, no libraries copy over... can you fix?  These are in National state

**Comment by mnichols13** [comment]
The same thing happens when I tried to copy a Penn State teacher.

**Comment by dpentony** [comment]
Any progress on this item?

**Comment by bguerrettaz** [comment]
I did some analysis on this issue and here is what I found.  The teachers
that you are trying to copy have no lesson plan, eUnit or CSAT on this
teacher profile.  This is where that information for the copy function
comes from.  Here is an example of a teacher from Penn State that I looked
up in the database, notice that the three highlighted areas are blank.
That is true for the national teachers that I sampled.

Where should we go with this?

[image: Inline image 2]

**Comment by mnichols13** [comment]
I cannot see this image, but is it because the teachers I am trying to copy are inactive?   Because I wouldn't try and copy a teacher that has no libraries, there would be no point to that.

**Comment by bguerrettaz** [comment]
Can you give me an example of a teacher that you had this issue with so I
can use that in my testing?

Thanks,
Blake

**Comment by mnichols13** [comment]
Yes 
teacher: Ashley Tonn
school:  KSU Student

**Comment by bguerrettaz** [comment]
I just selected copy on teacher Ashley Tonn.  It appears that she doesn't
have any librabries to copy, am I missing something?

[image: Inline image 1]

**Comment by mnichols13** [comment]
![image](https://cloud.githubusercontent.com/assets/5790342/8958981/c209af18-35cd-11e5-8fa9-12739b455b05.png)

**Comment by mnichols13** [comment]
for some reason I cannot open your images - but I posted what I see on the admin page for Ashley Tonn.

**Comment by bguerrettaz** [comment]
Ok, I have made some changes and tested with that teacher and some teachers
that were working before.  I think it is good to go.  Can you please test a
few that weren't working and a few that were and confirm?  Thanks

**Comment by mnichols13** [comment]
looks good for Penn State and for KSU tried both and was successful - Thanks.
