### ISSUE TITLE
Google Classroom Integration - Assign eUnits/PPTs

### ISSUE THREAD

**Issue by BrianPeterlin** [MyCaert/Issues-Enhancements#87]
@bguerrettaz we would like to get an estimate on what it would take to integrate MyCaert with Google Classroom.  We are not sure what that means at this point, but I have one idea. Can you see what it would take to give the ability to assign eUnits and Powerpoints as Google Classroom assignments?  Basically in the saved course outline screen can we have a link to assign the eUnit or PPT as a Google Classroom assignment.  I believe google classroom events capture a due date, title, description, attachments and class.  I am not sure if there API allows this, but I am hopeful.

We will then need to review with @dpentony

**Comment by bguerrettaz** [comment]
@dpentony initial estimate to create a sharable unique, encrypted link from the saved course outline view, an interface into the system to make sure that the person clicking on that link is authorized and a database to support that is around 30-40 hours.

Please let us know if you'd like to start this work.

Blake

**Comment by dpentony** [comment]
Thanks. We'll take this under consideration and get input from our customers. I will leave this issue open for now.
