### ISSUE TITLE
Courses that are deleted are not being removed from Manage Course Rosters drop down

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#91]
When a teacher deletes a course outline it should no longer show up in the drop down menu of Manage Course Rosters.  This is not working correctly.  I deleted several course outlines this morning, but they still show up. 

Additionally, if I click to edit a student - say for example Bob Caert on my account (login ALL, pw 1234)  I still see under VIEWABLE COURSES some of the ones that have been deleted.  
ie. Business (CC Std Eng SL 3..., HC: Greenhouses,  Soils Spring 2014, Test Quiz Class)

So in these two places the courses are not updating correctly.  This is not a super high priority, but something that should be looked at soon.

**Comment by mnichols13** [comment]
Dean Slark has four old course outlines that no longer show up under the blue MY COURSES tab, but show in the drop down menus for Manage Course Rosters and Assign/Maintain ppts and eunits.  Please delete these titles:
Natural Resources
Horticulture/Plant Science
Intro to Agri-science
Middle School

**Comment by bguerrettaz** [comment]
This is complete.

Blake

**Comment by mnichols13** [comment]
thanks
