### ISSUE TITLE
IL Exported Course Outlines Missing a Column

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#98]
In Illinois, all lesson plans are aligned to the National AFNR Standards. When the course outline is exported to Word/Excel, there is not a column listing the AFNR alignments.

![image](https://cloud.githubusercontent.com/assets/5790325/4761064/14413b20-5af5-11e4-98dd-e48717fe8db7.png)

![image](https://cloud.githubusercontent.com/assets/5790325/4761092/4e718412-5af5-11e4-9a26-2a3974bb6807.png)

**Comment by mnichols13** [comment]
William Stowell in New York- National State reporting that the AFNR standards do not show up.  It looks like on this thread that we paid for this to be fixed, but why would they not be showing again?

**Comment by mnichols13** [comment]
My mistake - NY is not in the National State -   Please fix the state of NY, apparently it was not fixed when the rest of the states were done.     Can you do this over the weekend?

**Comment by bguerrettaz** [comment]
I have started work on this, but for some reason the NY course outline
export is badly formatted and needs work, plus the addition of the AFNR
standards.

I will continue work on this and update once complete.

Thanks,
Blake

**Comment by dpentony** [comment]
Any idea as to how much time you will have in this to fix it?

**Comment by bguerrettaz** [comment]
I've got about 2 hours into it now, hoping to get it done in 1-1.5.  3-3.5
total.

Blake

**Comment by dpentony** [comment]
Please proceed.

**Comment by bguerrettaz** [comment]
This is complete.  Please test and confirm.  One note on formatting.  You’ll notice a very minor deviation in the lines as you look down, not sure what’s causing that and didn’t want to spend time looking into it unless you wanted me to. 

I also added the lookup table to the bottom.

Thanks,
Blake

**Comment by mnichols13** [comment]
looks good - thanks!
